export type FinancialPartyType='customer'|'supplier';
export type FinancialTargetType='load'|'quarryPurchase'|'openingBalance';
export type PaymentStatus='Unpriced'|'No Payment Due'|'Unpaid'|'Partially Paid'|'Paid'|'Overpaid';
export type FinancialParty={id:string;name:string;type:FinancialPartyType};
export type PaymentEntry={id:string;targetType:FinancialTargetType;targetId:string;amountUsd:number;paymentDate:string;status:'Active'|'Cancelled';cancellationReason:string|null;cancelledAt:string|null;createdAt:string};
export type FinancialTarget={id:string;type:FinancialTargetType;partyId:string;partyName:string;partyType:FinancialPartyType;reference:string;recordDate:string;projectId?:string|null;projectName?:string|null;projectStatus?:string|null;itemName?:string|null;quantity?:number|null;unitSymbol?:string|null;totalUsd:number;paidUsd:number;remainingUsd:number;overpaidUsd:number;status:PaymentStatus;payments:PaymentEntry[]};
export type FinancialOverview={parties:FinancialParty[];targets:FinancialTarget[]};
export type OpeningBalanceDraft={partyType:FinancialPartyType;partyId:string;amountUsd:string;asOfDate:string;reference:string;notes:string};
export type PaymentDraft={targetType:FinancialTargetType;targetId:string;amountUsd:string;paymentDate:string};

export function localFinancialDate(date=new Date()):string{return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;}
export const emptyOpeningBalanceDraft:OpeningBalanceDraft={partyType:'customer',partyId:'',amountUsd:'',asOfDate:localFinancialDate(),reference:'',notes:''};
export function paymentStatus(totalCents:number,paidCents:number):PaymentStatus{if(paidCents>totalCents)return 'Overpaid';if(totalCents===0)return 'No Payment Due';if(paidCents===0)return 'Unpaid';if(paidCents<totalCents)return 'Partially Paid';return 'Paid';}
export function validateOpeningBalance(draft:OpeningBalanceDraft,parties:FinancialParty[]):string[]{const issues:string[]=[];if(!parties.some((p)=>p.id===draft.partyId&&p.type===draft.partyType))issues.push(`Select a ${draft.partyType}.`);const amountText=draft.amountUsd.trim().replace(',','.');const amount=Number(amountText);if(!/^\d+(\.\d{1,2})?$/.test(amountText)||!Number.isFinite(amount)||amount<=0)issues.push('Opening balance amount must be greater than zero with no more than two decimals.');if(!/^\d{4}-\d{2}-\d{2}$/.test(draft.asOfDate)||draft.asOfDate>localFinancialDate())issues.push('As-of date must be today or an earlier date in YYYY-MM-DD format.');return issues;}
export function validatePayment(draft:PaymentDraft,target:FinancialTarget|null):string[]{const issues:string[]=[];if(!target||target.id!==draft.targetId||target.type!==draft.targetType)issues.push('Select a financial record.');const amountText=draft.amountUsd.trim().replace(',','.');const amount=Number(amountText);if(!/^\d+(\.\d{1,2})?$/.test(amountText)||!Number.isFinite(amount)||amount<=0)issues.push('Payment amount must be greater than zero with no more than two decimals.');else if(target&&Math.round(amount*100)>Math.round(target.remainingUsd*100))issues.push('Payment cannot exceed the remaining balance.');if(!/^\d{4}-\d{2}-\d{2}$/.test(draft.paymentDate)||draft.paymentDate>localFinancialDate())issues.push('Payment date must be today or an earlier date in YYYY-MM-DD format.');return issues;}
