export type FuelMovementType='gauge'|'delivery'|'fill';
export type FuelMovementStatus='Active'|'Cancelled';
export type FuelEquipmentType='machine'|'truck';
export type FuelOption={id:string;name:string;detail?:string;startDate?:string;endDate?:string|null};
export type FuelPriceRecord={id:string;pricePerLitreUsd:number;effectiveAt:string;changedBy:string;reason:string|null;createdAt:string};
export type FuelSetup={suppliers:FuelOption[];machines:FuelOption[];trucks:FuelOption[];equipment:FuelOption[];projects:FuelOption[];vatRatePercent:number;currentFuelPrice:FuelPriceRecord|null;fuelPriceHistory:FuelPriceRecord[]};
export type FuelMovement={id:string;type:FuelMovementType;confirmedAt:string;litres:number;previousBalanceLitres:number|null;differenceLitres:number|null;supplierId:string|null;supplierName:string|null;equipmentType?:FuelEquipmentType;equipmentId:string|null;equipmentName:string|null;projectId:string|null;projectName:string|null;ticketNumber:string|null;odometerReading:string|null;reason:string|null;notes:string|null;fuelPriceHistoryId:string|null;pricePerLitreUsd:number|null;priceOverrideReason:string|null;consumptionCostUsd:number|null;subtotalUsd:number|null;vatRatePercent:number|null;vatAmountUsd:number|null;finalTotalUsd:number|null;paymentStatus:string;status:FuelMovementStatus;cancellationReason:string|null;cancelledAt:string|null;balanceAfterLitres:number};
export type FuelOverview={currentBalanceLitres:number;hasKnownBalance:boolean;latestGauge:FuelMovement|null;movements:FuelMovement[]};
export type ProjectEquipmentFuelUsage={equipmentId:string|null;equipmentName:string;totalLitres:number;totalCostUsd:number;unpricedLitres:number;fillCount:number;fills:FuelMovement[]};
export type FuelMovementFilters={projectId?:string;equipmentId?:string;type?:FuelMovementType|'all';status?:FuelMovementStatus|'all';fromDate?:string;toDate?:string};
export type FuelDeliveryDraft={recordDate:string;litres:string;supplierId:string;ticketNumber:string;pricePerLitreUsd:string;updateCurrentPrice:boolean;notes:string};
export type FuelFillDraft={recordDate:string;litres:string;equipmentType:FuelEquipmentType;equipmentId:string;projectId:string;odometerReading:string;pricePerLitreUsd:string;priceOverrideReason:string;notes:string};
export type FuelGaugeDraft={recordDate:string;actualLitres:string;reason:string;notes:string};
export type FuelPriceDraft={pricePerLitreUsd:string;reason:string};
export const emptyFuelDelivery:FuelDeliveryDraft={recordDate:localDateKey(new Date()),litres:'',supplierId:'',ticketNumber:'',pricePerLitreUsd:'',updateCurrentPrice:true,notes:''};
export const emptyFuelFill:FuelFillDraft={recordDate:localDateKey(new Date()),litres:'',equipmentType:'machine',equipmentId:'',projectId:'',odometerReading:'',pricePerLitreUsd:'',priceOverrideReason:'',notes:''};
export const emptyFuelGauge:FuelGaugeDraft={recordDate:localDateKey(new Date()),actualLitres:'',reason:'',notes:''};
export const emptyFuelPrice:FuelPriceDraft={pricePerLitreUsd:'',reason:''};

const decimal=(value:string)=>Number(value.trim().replace(',','.'));
const decimalFormat=(value:string)=>/^\d+([.,]\d+)?$/.test(value.trim());
export function validatePositiveLitres(value:string):number{const parsed=decimal(value);if(!decimalFormat(value)||!Number.isFinite(parsed)||parsed<=0)throw new Error('Litres must be a number greater than zero.');return parsed;}
export function validateGaugeLitres(value:string):number{const parsed=decimal(value);if(!decimalFormat(value)||!Number.isFinite(parsed)||parsed<0)throw new Error('Actual gauge litres must be a number zero or greater.');return parsed;}
export function validateFuelPrice(value:string,required=false):number|null{if(!value.trim()){if(required)throw new Error('Fuel price per litre is required.');return null;}const parsed=decimal(value);if(!Number.isFinite(parsed)||parsed<0||!/^\d+([.,]\d{1,2})?$/.test(value.trim()))throw new Error('Price per litre must be zero or greater with no more than two decimals.');return parsed;}
export function calculateFuelDelivery(litres:number,priceText:string,vatRatePercent:number){const price=validateFuelPrice(priceText);if(price==null)return{pricePerLitreUsd:null,subtotalUsd:null,vatAmountUsd:null,finalTotalUsd:null};const subtotal=Math.round(litres*price*100)/100;const vat=Math.round(subtotal*vatRatePercent)/100;return{pricePerLitreUsd:price,subtotalUsd:subtotal,vatAmountUsd:vat,finalTotalUsd:Math.round((subtotal+vat)*100)/100};}
export function calculateFuelFillCost(litres:number,priceText:string):{pricePerLitreUsd:number|null;consumptionCostUsd:number|null}{const price=validateFuelPrice(priceText);return{pricePerLitreUsd:price,consumptionCostUsd:price==null?null:Math.round(litres*price*100)/100};}

export function applyFuelLedger(movements:Omit<FuelMovement,'balanceAfterLitres'>[]):FuelMovement[]{let balance=0;return [...movements].sort((a,b)=>a.confirmedAt.localeCompare(b.confirmedAt)).map(movement=>{let previousBalanceLitres=movement.previousBalanceLitres;let differenceLitres=movement.differenceLitres;if(movement.status==='Active'){if(movement.type==='gauge'){previousBalanceLitres=balance;differenceLitres=movement.litres-balance;balance=movement.litres;}else if(movement.type==='delivery')balance+=movement.litres;else balance-=movement.litres;}return{...movement,previousBalanceLitres,differenceLitres,balanceAfterLitres:balance};});}

export function groupProjectFuelByEquipment(movements:FuelMovement[],projectId:string):ProjectEquipmentFuelUsage[]{
  const groups=new Map<string,ProjectEquipmentFuelUsage>();
  movements.filter(value=>value.type==='fill'&&value.status==='Active'&&value.projectId===projectId).forEach(fill=>{const key=`${fill.equipmentType}:${fill.equipmentId??`name:${fill.equipmentName??'Unknown equipment'}`}`;const current=groups.get(key)??{equipmentId:key,equipmentName:fill.equipmentName??'Unknown equipment',totalLitres:0,totalCostUsd:0,unpricedLitres:0,fillCount:0,fills:[]};current.totalLitres+=fill.litres;current.totalCostUsd+=fill.consumptionCostUsd??0;if(fill.consumptionCostUsd==null)current.unpricedLitres+=fill.litres;current.fillCount+=1;current.fills.push(fill);groups.set(key,current);});
  return [...groups.values()].map(group=>({...group,fills:[...group.fills].sort((a,b)=>b.confirmedAt.localeCompare(a.confirmedAt))})).sort((a,b)=>b.totalLitres-a.totalLitres||a.equipmentName.localeCompare(b.equipmentName));
}

export function filterFuelMovements(movements:FuelMovement[],filters:FuelMovementFilters):FuelMovement[]{return movements.filter(value=>(!filters.projectId||value.projectId===filters.projectId)&&(!filters.equipmentId||value.equipmentId===filters.equipmentId)&&(!filters.type||filters.type==='all'||value.type===filters.type)&&(!filters.status||filters.status==='all'||value.status===filters.status)&&(!filters.fromDate||localDateKey(value.confirmedAt)>=filters.fromDate)&&(!filters.toDate||localDateKey(value.confirmedAt)<=filters.toDate));}

export type FuelPeriodTotals={purchasedLitres:number;purchaseCostUsd:number;consumedLitres:number;consumptionCostUsd:number;unpricedFillLitres:number};
export type FuelCostBreakdown={id:string;name:string;litres:number;costUsd:number;unpricedLitres:number;fillCount:number};
export type FuelDashboard={today:FuelPeriodTotals;month:FuelPeriodTotals;projects:FuelCostBreakdown[];equipment:FuelCostBreakdown[]};
export function localDateKey(value:string|Date):string{const date=value instanceof Date?value:new Date(value);return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;}
function periodTotals(movements:FuelMovement[],predicate:(date:string)=>boolean):FuelPeriodTotals{return movements.filter(v=>v.status==='Active'&&predicate(localDateKey(v.confirmedAt))).reduce((total,v)=>{if(v.type==='delivery'){total.purchasedLitres+=v.litres;total.purchaseCostUsd+=v.finalTotalUsd??0;}else if(v.type==='fill'){total.consumedLitres+=v.litres;total.consumptionCostUsd+=v.consumptionCostUsd??0;if(v.consumptionCostUsd==null)total.unpricedFillLitres+=v.litres;}return total;},{purchasedLitres:0,purchaseCostUsd:0,consumedLitres:0,consumptionCostUsd:0,unpricedFillLitres:0});}
function breakdown(fills:FuelMovement[],key:'project'|'equipment'):FuelCostBreakdown[]{const result=new Map<string,FuelCostBreakdown>();for(const fill of fills){const id=key==='project'?fill.projectId:fill.equipmentId,name=key==='project'?fill.projectName:fill.equipmentName,groupKey=id??`unassigned:${name??key}`;const current=result.get(groupKey)??{id:id??'',name:name??(key==='project'?'No project linked':'Unknown equipment'),litres:0,costUsd:0,unpricedLitres:0,fillCount:0};current.litres+=fill.litres;current.costUsd+=fill.consumptionCostUsd??0;if(fill.consumptionCostUsd==null)current.unpricedLitres+=fill.litres;current.fillCount+=1;result.set(groupKey,current);}return [...result.values()].sort((a,b)=>b.litres-a.litres||a.name.localeCompare(b.name));}
export function buildFuelDashboard(movements:FuelMovement[],now=new Date()):FuelDashboard{const today=localDateKey(now),month=today.slice(0,7),activeMonthFills=movements.filter(v=>v.status==='Active'&&v.type==='fill'&&localDateKey(v.confirmedAt).startsWith(month));return{today:periodTotals(movements,date=>date===today),month:periodTotals(movements,date=>date.startsWith(month)),projects:breakdown(activeMonthFills,'project'),equipment:breakdown(activeMonthFills,'equipment')};}
