import {calculateWallVolume} from './walls';

/**
 * DEC-457. Deterministic technical wall diagram. The SVG is generated from the recorded geometry and
 * layer data every time it is displayed or exported; no bitmap is stored, nothing is fetched, and no
 * image is generated by any model. The same input always produces the same drawing.
 */

/** The one geometry shape shared by the wall, the base, and the volume formula. */
export type WallGeometry={lengthM:number;heightM:number;bottomThicknessM:number;topThicknessM:number};
export type WallLayerDraft={name:string;materialKey?:string|null;phaseOrder:number;bottomThicknessM:number;topThicknessM:number;note:string};
export type WallLayer=WallLayerDraft&{id:string;wallId:string;createdAt:string;updatedAt:string|null};

/** DEC-457. Layer thicknesses must agree with the wall within 5 mm, the tolerance a tape measure supports. */
export const LAYER_THICKNESS_TOLERANCE_M=0.005;

const round=(value:number)=>Number(value.toFixed(9));
const metres=(value:number)=>`${Number(value.toFixed(3))} m`;
const positive=(value:number)=>Number.isFinite(value)&&value>0&&Math.abs(value*1000-Math.round(value*1000))<1e-6;
const escapeXml=(value:unknown)=>String(value??'').replace(/[&<>"']/g,(character)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[character]??character));
const clip=(value:string,limit:number)=>value.length>limit?`${value.slice(0,limit-1)}…`:value;
const hasArabic=(value:string)=>/[؀-ۿ]/.test(value);

export function sortedLayers<T extends {phaseOrder:number}>(layers:T[]){return [...layers].sort((first,second)=>first.phaseOrder-second.phaseOrder);}

/**
 * DEC-457. Entered thicknesses are never adjusted to fit the wall; a disagreement is reported with its
 * exact difference and blocks saving instead.
 */
export function validateWallLayers(layers:WallLayerDraft[],wall:Pick<WallGeometry,'bottomThicknessM'|'topThicknessM'>):string[]{
  if(!layers.length)return [];
  const issues:string[]=[],seen=new Set<number>();
  for(const [index,layer] of sortedLayers(layers).entries()){
    const position=index+1;
    if(!layer.name.trim())issues.push('Every layer needs a material or layer name.');
    if(!Number.isInteger(layer.phaseOrder)||layer.phaseOrder<1)issues.push('Construction phase must be a whole number of 1 or more.');
    else if(seen.has(layer.phaseOrder))issues.push(`Two layers cannot share construction phase ${layer.phaseOrder}.`);
    else seen.add(layer.phaseOrder);
    if(!positive(layer.bottomThicknessM))issues.push(`Layer ${position} bottom thickness must be greater than zero with no more than three decimals.`);
    if(!positive(layer.topThicknessM))issues.push(`Layer ${position} top thickness must be greater than zero with no more than three decimals.`);
  }
  if(issues.length)return issues;
  const sum=(pick:(layer:WallLayerDraft)=>number)=>round(layers.reduce((total,layer)=>total+pick(layer),0));
  const compare=(label:string,total:number,wallValue:number)=>{
    const difference=round(Math.abs(total-wallValue));
    if(difference>LAYER_THICKNESS_TOLERANCE_M)issues.push(`Layer ${label} thicknesses total ${metres(total)} but the wall ${label} thickness is ${metres(wallValue)}, a difference of ${metres(difference)}.`);
  };
  compare('bottom',sum(layer=>layer.bottomThicknessM),wall.bottomThicknessM);
  compare('top',sum(layer=>layer.topThicknessM),wall.topThicknessM);
  return issues;
}

// Restrained construction-document colours: muted stone, concrete, steel, timber, and earth tones. No
// bright decorative hues, no gradients. Each is paired with a pattern so colour is never the only cue.
const PALETTE=['#8C8579','#6E7B8B','#A8895F','#5F7A6A','#9A6B5B','#7A7392','#6B8794','#8A7B4F'] as const;
const PATTERNS=['diagonal','cross','dots','horizontal','vertical','solid'] as const;
export type LayerPattern=typeof PATTERNS[number];
export type LayerAppearance={fill:string;pattern:LayerPattern;marker:number};

const fingerprint=(value:string)=>{let hash=2166136261;for(const character of value.trim().toLocaleLowerCase('en-US'))hash=Math.imul(hash^character.codePointAt(0)!,16777619)>>>0;return hash;};
/** Deterministic, repeatable appearance for a layer: the same material name always looks the same. */
export function layerAppearance(name:string,marker:number):LayerAppearance{
  const hash=fingerprint(name);
  return{fill:PALETTE[hash%PALETTE.length]!,pattern:PATTERNS[Math.floor(hash/PALETTE.length)%PATTERNS.length]!,marker};
}

export type DiagramLayer=Pick<WallLayerDraft,'name'|'phaseOrder'|'bottomThicknessM'|'topThicknessM'>&{note?:string|null};
export type DiagramBaseStatus='planned'|'constructed'|'curing'|'cured';
export type DiagramBase={geometry:WallGeometry;status:DiagramBaseStatus;curingDays?:number|null;label?:string|null}|null;
export type WallDiagramInput={wall:WallGeometry&{name:string};layers:DiagramLayer[];base?:DiagramBase;wallBuilt?:boolean};
export type DiagramLegendEntry={marker:number;phase:number;name:string;bottomThicknessM:number;topThicknessM:number;note:string|null;fill:string;pattern:LayerPattern};

export type DiagramElement=
  |{kind:'rect';x:number;y:number;width:number;height:number;fill:string;stroke:string|null;dash?:string}
  |{kind:'polygon';points:[number,number][];fill:string;stroke:string}
  |{kind:'line';x1:number;y1:number;x2:number;y2:number;stroke:string;dash?:string}
  |{kind:'circle';cx:number;cy:number;r:number;fill:string;stroke:string}
  |{kind:'text';value:string;x:number;y:number;size:number;weight:number;fill:string;anchor:'start'|'middle'|'end';rtl:boolean};
export type DiagramPatternDef={id:string;fill:string;pattern:LayerPattern};
export type WallDiagram={width:number;height:number;elements:DiagramElement[];patterns:DiagramPatternDef[];legend:DiagramLegendEntry[];exaggerated:boolean;svg:string};

const WIDTH=760,MIN_LAYER_PX=9,PADDING=18,ELEVATION_LEFT=PADDING+52;
const INK='#17212b',MUTED='#65717d',RESULT='#04545d',PAPER='#EFEAE0',BASE_FILL='#CFC6B6';

/**
 * Builds the composed figure: elevation, cross-section with layers in construction order, and a legend.
 * Proportional where it can be, with a stated minimum width so a thin layer stays identifiable; the
 * numbers beside the drawing are always the measured ones.
 */
export function buildWallDiagram(input:WallDiagramInput):WallDiagram{
  const {wall}=input,base=input.base??null;
  const layers=sortedLayers(input.layers??[]);
  const legend:DiagramLegendEntry[]=layers.map((layer,index)=>{
    const appearance=layerAppearance(layer.name,index+1);
    return{marker:index+1,phase:layer.phaseOrder,name:layer.name,bottomThicknessM:layer.bottomThicknessM,topThicknessM:layer.topThicknessM,note:layer.note?.trim()||null,fill:appearance.fill,pattern:appearance.pattern};
  });
  const patterns:DiagramPatternDef[]=legend.map(entry=>({id:`p${entry.marker}`,fill:entry.fill,pattern:entry.pattern}));
  const elements:DiagramElement[]=[];
  const rect=(x:number,y:number,width:number,height:number,fill:string,stroke:string|null=INK,dash?:string)=>elements.push({kind:'rect',x:round(x),y:round(y),width:round(Math.max(0,width)),height:round(Math.max(0,height)),fill,stroke,dash});
  const polygon=(points:[number,number][],fill:string,stroke=INK)=>elements.push({kind:'polygon',points:points.map(([x,y])=>[round(x),round(y)] as [number,number]),fill,stroke});
  const line=(x1:number,y1:number,x2:number,y2:number,stroke=INK,dash?:string)=>elements.push({kind:'line',x1:round(x1),y1:round(y1),x2:round(x2),y2:round(y2),stroke,dash});
  const circle=(cx:number,cy:number,r:number,fill:string,stroke=INK)=>elements.push({kind:'circle',cx:round(cx),cy:round(cy),r,fill,stroke});
  const write=(value:string,x:number,y:number,options:{size?:number;weight?:number;fill?:string;anchor?:'start'|'middle'|'end';rtl?:boolean}={})=>elements.push({kind:'text',value,x:round(x),y:round(y),size:options.size??10,weight:options.weight??400,fill:options.fill??INK,anchor:options.anchor??'start',rtl:options.rtl??false});
  /** Right-to-left text is drawn from its right edge so it stays inside its own column. */
  const label=(value:string,left:number,right:number,y:number,options:{size?:number;weight?:number;fill?:string}={})=>
    hasArabic(value)?write(value,right,y,{...options,anchor:'end',rtl:true}):write(value,left,y,options);

  const tapered=wall.bottomThicknessM!==wall.topThicknessM;
  const volume=calculateWallVolume(wall.lengthM,wall.heightM,wall.bottomThicknessM,wall.topThicknessM,0);
  const bandTop=58,bandHeight=150;
  const elevationWidth=330,sectionLeft=ELEVATION_LEFT+elevationWidth+30,sectionWidth=200;
  const elevationBoxWidth=elevationWidth-70,elevationBoxHeight=bandHeight-46;
  const elevationX=ELEVATION_LEFT,elevationY=bandTop+12;
  const baseHeight=base?30:0,sectionHeight=elevationBoxHeight-baseHeight;
  const maxThickness=Math.max(wall.bottomThicknessM,wall.topThicknessM,base?Math.max(base.geometry.bottomThicknessM,base.geometry.topThicknessM):0);
  const scale=(sectionWidth-40)/(maxThickness||1);
  const centre=sectionLeft+sectionWidth/2;

  let exaggerated=false;
  const widths=layers.map(layer=>{
    const bottom=layer.bottomThicknessM*scale,top=layer.topThicknessM*scale;
    if(bottom<MIN_LAYER_PX||top<MIN_LAYER_PX)exaggerated=true;
    return{bottom:Math.max(bottom,MIN_LAYER_PX),top:Math.max(top,MIN_LAYER_PX)};
  });
  const totalBottom=widths.reduce((sum,value)=>sum+value.bottom,0)||wall.bottomThicknessM*scale;
  const totalTop=widths.reduce((sum,value)=>sum+value.top,0)||wall.topThicknessM*scale;

  label(clip(wall.name,60),PADDING,WIDTH/2+60,24,{size:13,weight:700});
  write(`Gross volume ${volume.grossVolumeM3} m³`,WIDTH-PADDING,24,{size:10,weight:700,anchor:'end',fill:RESULT});
  write('Generated from the recorded dimensions. Not to scale.',PADDING,38,{size:8,fill:MUTED});

  // Elevation
  write('Elevation',elevationX,bandTop,{size:10,weight:700});
  rect(elevationX,elevationY,elevationBoxWidth,elevationBoxHeight-baseHeight,PAPER);
  if(base){
    const baseWidthPx=elevationBoxWidth*Math.min(1.12,(base.geometry.lengthM||wall.lengthM)/(wall.lengthM||1));
    const planned=base.status==='planned';
    rect(elevationX-(baseWidthPx-elevationBoxWidth)/2,elevationY+elevationBoxHeight-baseHeight,baseWidthPx,baseHeight,planned?'none':BASE_FILL,planned?MUTED:INK,planned?'4 3':undefined);
    write(`${base.label??'Base'}: ${base.status}${base.curingDays!=null?`, ${base.curingDays} curing days`:''}`,elevationX,elevationY+elevationBoxHeight+12,{size:8,fill:MUTED});
  }
  line(elevationX,elevationY+elevationBoxHeight+(base?22:10),elevationX+elevationBoxWidth,elevationY+elevationBoxHeight+(base?22:10));
  write(`${metres(wall.lengthM)} long`,elevationX+elevationBoxWidth/2,elevationY+elevationBoxHeight+(base?34:22),{size:9,anchor:'middle'});
  line(elevationX-12,elevationY,elevationX-12,elevationY+elevationBoxHeight-baseHeight);
  write(`${metres(wall.heightM)} high`,elevationX-16,elevationY+(elevationBoxHeight-baseHeight)/2,{size:9,anchor:'end'});
  if(tapered)write('Tapered section',elevationX+elevationBoxWidth,bandTop,{size:9,anchor:'end',fill:RESULT});

  // Cross-section
  write('Cross-section',sectionLeft,bandTop,{size:10,weight:700});
  const sectionTop=elevationY,sectionBottom=elevationY+sectionHeight;
  if(!layers.length){
    polygon([[centre-wall.bottomThicknessM*scale/2,sectionBottom],[centre+wall.bottomThicknessM*scale/2,sectionBottom],[centre+wall.topThicknessM*scale/2,sectionTop],[centre-wall.topThicknessM*scale/2,sectionTop]],PAPER);
    write('No layers recorded',centre,sectionTop+sectionHeight/2,{size:9,anchor:'middle',fill:MUTED});
  }else{
    let offsetBottom=centre-totalBottom/2,offsetTop=centre-totalTop/2;
    for(const [index,entry] of legend.entries()){
      const width=widths[index]!;
      polygon([[offsetBottom,sectionBottom],[offsetBottom+width.bottom,sectionBottom],[offsetTop+width.top,sectionTop],[offsetTop,sectionTop]],`url(#p${entry.marker})`);
      circle(offsetBottom+width.bottom/2,sectionBottom-12,7,'#FFFFFF');
      write(String(entry.marker),offsetBottom+width.bottom/2,sectionBottom-9,{size:8,weight:700,anchor:'middle'});
      offsetBottom+=width.bottom;offsetTop+=width.top;
    }
  }
  if(base){
    const baseWidth=Math.max(base.geometry.bottomThicknessM,base.geometry.topThicknessM)*scale,planned=base.status==='planned';
    rect(centre-baseWidth/2,sectionBottom,baseWidth,baseHeight-8,planned?'none':BASE_FILL,planned?MUTED:INK,planned?'4 3':undefined);
    write(`Base ${metres(base.geometry.bottomThicknessM)} / ${metres(base.geometry.topThicknessM)}`,centre,sectionBottom+baseHeight+2,{size:8,anchor:'middle',fill:MUTED});
  }
  line(centre-wall.bottomThicknessM*scale/2,sectionBottom+(base?baseHeight+12:10),centre+wall.bottomThicknessM*scale/2,sectionBottom+(base?baseHeight+12:10));
  write(`Bottom ${metres(wall.bottomThicknessM)}`,centre,sectionBottom+(base?baseHeight+22:20),{size:9,anchor:'middle'});
  write(`Top ${metres(wall.topThicknessM)}`,centre,sectionTop-6,{size:9,anchor:'middle'});

  // Legend and phase sequence
  let cursor=bandTop+bandHeight+(base?26:14);
  if(legend.length){
    write('Layers and construction phases',PADDING,cursor,{size:10,weight:700});
    cursor+=6;
    for(const entry of legend){
      cursor+=16;
      rect(PADDING,cursor-9,12,11,`url(#p${entry.marker})`);
      write(String(entry.marker),PADDING+5.5,cursor-1,{size:7,weight:700,anchor:'middle',fill:'#FFFFFF'});
      write(`Phase ${entry.phase}`,PADDING+20,cursor,{size:9,weight:700});
      label(clip(entry.name,46),PADDING+74,WIDTH-PADDING-150,cursor,{size:9});
      write(`bottom ${metres(entry.bottomThicknessM)} · top ${metres(entry.topThicknessM)}`,WIDTH-PADDING,cursor,{size:8,anchor:'end',fill:MUTED});
      if(entry.note){cursor+=11;label(clip(entry.note,72),PADDING+74,WIDTH-PADDING-150,cursor,{size:8,fill:MUTED});}
    }
    cursor+=14;
  }
  if(exaggerated){write('Thin layers shown wider than scale so they stay visible. The measurements above are the recorded values.',PADDING,cursor,{size:8,fill:'#8e2e1b'});cursor+=12;}
  const height=round(Math.max(bandTop+bandHeight+30,cursor+8));
  const diagram:Omit<WallDiagram,'svg'>={width:WIDTH,height,elements,patterns,legend,exaggerated};
  return{...diagram,svg:wallDiagramToSvg(diagram)};
}

const patternBody=(pattern:LayerPattern)=>pattern==='diagonal'?'M0,6 l6,-6'
  :pattern==='cross'?'M0,6 l6,-6 M0,0 l6,6'
  :pattern==='horizontal'?'M0,3 h6'
  :pattern==='vertical'?'M3,0 v6'
  :pattern==='dots'?'M3,3 m-1,0 a1,1 0 1,0 2,0 a1,1 0 1,0 -2,0'
  :'';
/** The pattern stroke geometry, shared by the SVG string and the on-screen native renderer. */
export function diagramPatternPath(pattern:LayerPattern){return patternBody(pattern);}

/** Serializes the diagram to a self-contained SVG string: no script, no external reference, no raster. */
export function wallDiagramToSvg(diagram:Omit<WallDiagram,'svg'>):string{
  const defs=diagram.patterns.map(entry=>{
    const path=patternBody(entry.pattern);
    return `<pattern id="${entry.id}" width="6" height="6" patternUnits="userSpaceOnUse"><rect width="6" height="6" fill="${entry.fill}"/>${path?`<path d="${path}" stroke="${INK}" stroke-width=".8" fill="${entry.pattern==='dots'?INK:'none'}"/>`:''}</pattern>`;
  }).join('');
  const body=diagram.elements.map(element=>{
    if(element.kind==='rect')return `<rect x="${element.x}" y="${element.y}" width="${element.width}" height="${element.height}" fill="${element.fill}"${element.stroke?` stroke="${element.stroke}" stroke-width="1"`:''}${element.dash?` stroke-dasharray="${element.dash}"`:''}/>`;
    if(element.kind==='polygon')return `<polygon points="${element.points.map(([x,y])=>`${x},${y}`).join(' ')}" fill="${element.fill}" stroke="${element.stroke}" stroke-width="1"/>`;
    if(element.kind==='line')return `<line x1="${element.x1}" y1="${element.y1}" x2="${element.x2}" y2="${element.y2}" stroke="${element.stroke}" stroke-width="1"${element.dash?` stroke-dasharray="${element.dash}"`:''}/>`;
    if(element.kind==='circle')return `<circle cx="${element.cx}" cy="${element.cy}" r="${element.r}" fill="${element.fill}" stroke="${element.stroke}" stroke-width="1"/>`;
    return `<text x="${element.x}" y="${element.y}" font-family="Arial, 'Noto Naskh Arabic', sans-serif" font-size="${element.size}" font-weight="${element.weight}" fill="${element.fill}" text-anchor="${element.anchor}"${element.rtl?' direction="rtl"':''}>${escapeXml(element.value)}</text>`;
  }).join('');
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${diagram.width} ${diagram.height}" width="100%" role="img"><defs>${defs}</defs><rect x="0" y="0" width="${diagram.width}" height="${diagram.height}" fill="#FFFFFF"/>${body}</svg>`;
}
