import * as FileSystem from'expo-file-system/legacy';
import * as Sharing from'expo-sharing';
import{businessReportLabels,type BusinessReportData,type BusinessReportKind}from'../domain/businessReports';
import{encodeBusinessWorkbookAsync,type WorkbookLocale,type WorkbookProgress}from'./businessWorkbook';

export type BusinessWorkbookExportOptions={signal?:AbortSignal;locale?:WorkbookLocale;onProgress?:(progress:WorkbookProgress)=>void};
const cancelled=()=>{const error=new Error('Workbook export cancelled.');error.name='AbortError';return error;};
const checkCancelled=(signal?:AbortSignal)=>{if(signal?.aborted)throw cancelled();};
export async function exportBusinessWorkbook(kind:BusinessReportKind,data:BusinessReportData,options:BusinessWorkbookExportOptions={}){if(!FileSystem.documentDirectory)throw new Error('Document storage is unavailable.');const directory=`${FileSystem.documentDirectory}exports/`;await FileSystem.makeDirectoryAsync(directory,{intermediates:true});const stamp=data.generatedAt.replace(/[:.]/g,'-').slice(0,19);const target=`${directory}DROMEX-${kind==='analysis'?'Analysis-Workbook':kind}-${stamp}.xlsx`,partial=`${target}.partial`;let finalized=false;try{checkCancelled(options.signal);const base64=await encodeBusinessWorkbookAsync(kind,data,options);checkCancelled(options.signal);options.onProgress?.({stage:'encoding',completed:1,total:1,percent:99,message:'Saving workbook safely'});await FileSystem.deleteAsync(partial,{idempotent:true});await FileSystem.writeAsStringAsync(partial,base64,{encoding:FileSystem.EncodingType.Base64});checkCancelled(options.signal);await FileSystem.moveAsync({from:partial,to:target});finalized=true;options.onProgress?.({stage:'encoding',completed:1,total:1,percent:100,message:'Workbook ready to share'});checkCancelled(options.signal);if(!(await Sharing.isAvailableAsync()))throw new Error(`Workbook saved at ${target}, but sharing is unavailable.`);await Sharing.shareAsync(target,{mimeType:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',UTI:'org.openxmlformats.spreadsheetml.sheet',dialogTitle:`Share ${businessReportLabels[kind]}`});return target;}catch(error){await FileSystem.deleteAsync(partial,{idempotent:true});if(options.signal?.aborted&&finalized)await FileSystem.deleteAsync(target,{idempotent:true});if(options.signal?.aborted)throw cancelled();throw error;}}
