import{strToU8,zipSync}from'fflate';
import{businessReportLabels,type BusinessReportData,type BusinessReportKind,type WorkbookCell,type WorkbookRow}from'../domain/businessReports';

export type SheetSpec={name:string;rows:WorkbookRow[]};
const money=(rows:WorkbookRow[],key:string)=>rows.reduce((sum,row)=>sum+Number(row[key]??0),0);
const summary=(data:BusinessReportData):WorkbookRow[]=>[
  {'Metric':'Generated at','Value':data.generatedAt},{'Metric':'Company','Value':data.companyName},
  {'Metric':'Confirmed loads','Value':data.loads.length},{'Metric':'Load sales USD','Value':money(data.loads,'Final Total USD')},
  {'Metric':'Customer receivable USD','Value':money(data.customers,'Remaining USD')},{'Metric':'Quarry purchases','Value':data.quarryPurchases.length},
  {'Metric':'Supplier payable USD','Value':money(data.suppliers,'Remaining USD')},{'Metric':'Current fuel litres','Value':data.fuelMovements.at(-1)?.['Balance After Litres']??0},
  {'Metric':'Projects','Value':data.projects.length},{'Metric':'Daily reports','Value':data.dailyReports.length},
];
const dictionary:WorkbookRow[]=[
  {'Sheet':'Loads and Sales','Purpose':'One row per confirmed outgoing load; amounts and quantities are numeric.'},
  {'Sheet':'Customer Summary','Purpose':'One row per customer with billed, paid, remaining, and overpaid totals.'},
  {'Sheet':'Payments','Purpose':'One row per payment event, including retained cancelled events.'},
  {'Sheet':'Opening Balances','Purpose':'Carried-forward receivable and payable records from paper history.'},
  {'Sheet':'Quarry Purchases','Purpose':'One row per incoming quarry purchase, including cancelled record status.'},
  {'Sheet':'Supplier Summary','Purpose':'One row per supplier across quarry and priced fuel delivery balances.'},
  {'Sheet':'Fuel Movements','Purpose':'Chronological single-tank gauge, delivery, and equipment-fill ledger.'},
  {'Sheet':'Equipment Totals','Purpose':'Active equipment-fill litres grouped by saved equipment.'},
  {'Sheet':'Project Summary','Purpose':'One row per project with identity, status, dates, and report count.'},
  {'Sheet':'Daily Reports','Purpose':'One row per project workday with full searchable operational text.'},
  {'Sheet':'Materials Summary','Purpose':'Daily-report material quantities grouped by project, item, unit, and movement.'},
];

export function sheetsForBusinessReport(kind:BusinessReportKind,data:BusinessReportData):SheetSpec[]{
  const payments=(types:string[])=>data.payments.filter(row=>types.includes(String(row['Target Type'])));
  const overview:SheetSpec={name:'Report Overview',rows:[{'Report information':'Report title','Details':businessReportLabels[kind]},{'Report information':'Company','Details':data.companyName},{'Report information':'Generated on','Details':data.generatedAt},{'Report information':'Export contents','Details':'Only records matching the scope below are included.'},...(data.activeFilters??[{'Filter':'Scope','Value':'All records'}]).map(row=>({'Report information':String(row.Filter),'Details':row.Value??null}))]};
  if(kind==='loads')return[overview,{name:'Summary',rows:summary(data).slice(0,5)},{name:'Loads and Sales',rows:data.loads},{name:'Payment Details',rows:payments(['load'])}];
  if(kind==='customers')return[overview,{name:'Customer Summary',rows:data.customers},{name:'Payment Details',rows:payments(['load','openingBalance']).filter(v=>v['Customer ID'])},{name:'Opening Balances',rows:data.openingBalances.filter(v=>v['Party Type']==='customer')}];
  if(kind==='quarry')return[overview,{name:'Supplier Summary',rows:data.suppliers},{name:'Purchase Details',rows:data.quarryPurchases},{name:'Payment Details',rows:payments(['quarryPurchase','openingBalance']).filter(v=>v['Supplier ID'])}];
  if(kind==='fuel'){const gauge=[...data.fuelMovements].reverse().find(v=>v.Type==='gauge'&&v.Status==='Active');return[overview,{name:'Balance Summary',rows:[{'Metric':'Current calculated litres','Value':data.fuelMovements.at(-1)?.['Balance After Litres']??0},{'Metric':'Latest physical gauge litres','Value':gauge?.['Gauge Litres']??null},{'Metric':'Latest physical gauge date','Value':gauge?.['Confirmed At']??null},{'Metric':'Total active delivered litres','Value':data.fuelMovements.filter(v=>v.Type==='delivery'&&v.Status==='Active').reduce((s,v)=>s+Number(v['Litres In']??0),0)},{'Metric':'Total active filled litres','Value':data.fuelMovements.filter(v=>v.Type==='fill'&&v.Status==='Active').reduce((s,v)=>s+Number(v['Litres Out']??0),0)},{'Metric':'Total active correction difference','Value':data.fuelMovements.filter(v=>v.Type==='gauge'&&v.Status==='Active').reduce((s,v)=>s+Number(v['Correction Difference']??0),0)}]},{name:'Movement Details',rows:data.fuelMovements},{name:'Equipment Totals',rows:data.equipmentTotals},{name:'Payment Details',rows:payments(['fuelDelivery'])}];}
  if(kind==='projects')return[overview,{name:'Project Summary',rows:data.projects},{name:'Project Loads',rows:data.loads},{name:'Quarry Purchases',rows:data.quarryPurchases},{name:'Fuel Movements',rows:data.fuelMovements},{name:'Payment Details',rows:data.payments},{name:'Daily Report Index',rows:data.dailyReports},{name:'Materials Summary',rows:data.materials}];
  return[overview,{name:'Executive Summary',rows:summary(data)},{name:'Loads and Sales',rows:data.loads},{name:'Customer Summary',rows:data.customers},{name:'Payments',rows:data.payments},{name:'Opening Balances',rows:data.openingBalances},{name:'Quarry Purchases',rows:data.quarryPurchases},{name:'Supplier Summary',rows:data.suppliers},{name:'Fuel Movements',rows:data.fuelMovements},{name:'Equipment Totals',rows:data.equipmentTotals},{name:'Project Summary',rows:data.projects},{name:'Daily Reports',rows:data.dailyReports},{name:'Materials Summary',rows:data.materials},{name:'Data Dictionary',rows:dictionary}];
}

const esc=(value:unknown)=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[char]??char));
const columnName=(index:number)=>{let name='';for(let value=index+1;value>0;value=Math.floor((value-1)/26))name=String.fromCharCode(65+((value-1)%26))+name;return name};
const cellXml=(value:WorkbookCell,row:number,column:number,header=false)=>{const ref=`${columnName(column)}${row}`;if(typeof value==='number'&&Number.isFinite(value))return`<c r="${ref}" s="${header?1:0}"><v>${value}</v></c>`;if(typeof value==='boolean')return`<c r="${ref}" t="b" s="${header?1:0}"><v>${value?1:0}</v></c>`;return`<c r="${ref}" t="inlineStr" s="${header?1:0}"><is><t xml:space="preserve">${esc(value)}</t></is></c>`};
function worksheetXml(spec:SheetSpec){const source=spec.rows.length?spec.rows:[{'Status':'No matching records'}],headers=[...new Set(source.flatMap(row=>Object.keys(row)))],rows=[headers.reduce<WorkbookRow>((row,key)=>(row[key]=key,row),{}),...source];const body=rows.map((values,index)=>`<row r="${index+1}">${headers.map((key,column)=>cellXml(values[key]??null,index+1,column,index===0)).join('')}</row>`).join('');const widths=headers.map((key,column)=>{let width=String(key).length+2;for(const row of source.slice(0,200))width=Math.max(width,String(row[key]??'').length+2);return`<col min="${column+1}" max="${column+1}" width="${Math.min(Math.max(width,12),36)}" customWidth="1"/>`}).join('');const last=`${columnName(Math.max(0,headers.length-1))}${rows.length}`;return`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetViews><sheetView workbookViewId="0"><pane ySplit="1" topLeftCell="A2" activePane="bottomLeft" state="frozen"/></sheetView></sheetViews><cols>${widths}</cols><sheetData>${body}</sheetData><autoFilter ref="A1:${last}"/></worksheet>`}
const contentTypes=(count:number)=>`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/>${Array.from({length:count},(_,i)=>`<Override PartName="/xl/worksheets/sheet${i+1}.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>`).join('')}</Types>`;
const styles=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><fonts count="2"><font><sz val="11"/><name val="Aptos"/></font><font><b/><color rgb="FFFFFFFF"/><sz val="11"/><name val="Aptos"/></font></fonts><fills count="3"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill><fill><patternFill patternType="solid"><fgColor rgb="FF173F67"/><bgColor indexed="64"/></patternFill></fill></fills><borders count="1"><border><left/><right/><top/><bottom/><diagonal/></border></borders><cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs><cellXfs count="2"><xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"/><xf numFmtId="0" fontId="1" fillId="2" borderId="0" xfId="0" applyFont="1" applyFill="1"/></cellXfs></styleSheet>`;
const rootRels=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>`;

export function buildBusinessWorkbook(kind:BusinessReportKind,data:BusinessReportData){const sheets=sheetsForBusinessReport(kind,data),files:Record<string,Uint8Array>={};files['[Content_Types].xml']=strToU8(contentTypes(sheets.length));files['_rels/.rels']=strToU8(rootRels);files['xl/styles.xml']=strToU8(styles);files['xl/workbook.xml']=strToU8(`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><workbookPr/><bookViews><workbookView/></bookViews><sheets>${sheets.map((sheet,index)=>`<sheet name="${esc(sheet.name.slice(0,31))}" sheetId="${index+1}" r:id="rId${index+1}"/>`).join('')}</sheets><calcPr calcId="191029"/></workbook>`);files['xl/_rels/workbook.xml.rels']=strToU8(`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">${sheets.map((_,index)=>`<Relationship Id="rId${index+1}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet${index+1}.xml"/>`).join('')}<Relationship Id="rId${sheets.length+1}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>`);sheets.forEach((sheet,index)=>files[`xl/worksheets/sheet${index+1}.xml`]=strToU8(worksheetXml(sheet)));return zipSync(files,{level:6});}

function base64(bytes:Uint8Array){const chars='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/';let result='';for(let index=0;index<bytes.length;index+=3){const a=bytes[index]??0,b=bytes[index+1]??0,c=bytes[index+2]??0,value=(a<<16)|(b<<8)|c;result+=chars.charAt((value>>18)&63)+chars.charAt((value>>12)&63)+(index+1<bytes.length?chars.charAt((value>>6)&63):'=')+(index+2<bytes.length?chars.charAt(value&63):'=')}return result;}
export function encodeBusinessWorkbook(kind:BusinessReportKind,data:BusinessReportData){return base64(buildBusinessWorkbook(kind,data));}
