import * as FileSystem from 'expo-file-system/legacy'; import * as Print from 'expo-print'; import * as Sharing from 'expo-sharing';
import type { ConfirmedLoad } from '../domain/loads'; import type { DailyProjectReport,LinkedProjectLoad,LinkedWasteDump,ProjectCompletionLoad,ProjectCompletionWasteDump,ProjectReportSetup,ReportProject } from '../domain/projectReports'; import { imageUriToDataUrl } from './media'; import { buildLoadDocumentHtml,type LoadDocumentKind,type PaperWidth } from './documentTemplates'; import {buildProjectReportHtmlWithWaste} from './projectReportWasteTemplate'; import {buildProjectCompletionHtml} from './projectCompletionTemplate';
import type {QuickTextDocument} from '../domain/quickText'; import {buildQuickTextHtml} from './documentTemplates';
export type {LoadDocumentKind,PaperWidth} from './documentTemplates';
type PdfPageSize={width:number;height:number};
export function loadDocumentPageSize(kind:LoadDocumentKind,paper:PaperWidth):PdfPageSize{return {width:paper==='58'?176:244,height:kind==='receipt'?(paper==='58'?500:450):(paper==='58'?640:560)};}
async function saveAndShare(html:string,filename:string,title:string,pageSize?:PdfPageSize){const result=await Print.printToFileAsync({html,...pageSize});if(!FileSystem.documentDirectory)throw new Error('Document storage is unavailable.');const directory=`${FileSystem.documentDirectory}exports/`;await FileSystem.makeDirectoryAsync(directory,{intermediates:true});const target=`${directory}${filename}`;await FileSystem.deleteAsync(target,{idempotent:true});await FileSystem.moveAsync({from:result.uri,to:target});if(!(await Sharing.isAvailableAsync()))throw new Error(`PDF saved at ${target}, but sharing is unavailable.`);await Sharing.shareAsync(target,{mimeType:'application/pdf',UTI:'com.adobe.pdf',dialogTitle:title});return target;}
export async function exportAndShareLoadDocument(record:ConfirmedLoad,kind:LoadDocumentKind,paper:PaperWidth){const logo=await imageUriToDataUrl(record.companyLogoUri);return saveAndShare(buildLoadDocumentHtml(record,kind,paper,logo),`${kind==='receipt'?'Receipt':'Delivery-Authorization'}-${record.transactionNumber}-${paper}mm.pdf`,kind==='receipt'?'Share Receipt':'Share Delivery Authorization',loadDocumentPageSize(kind,paper));}
export async function exportAndShareProjectReport(report:DailyProjectReport,project:ReportProject,loads:LinkedProjectLoad[],waste:LinkedWasteDump[],company:ProjectReportSetup['company']){const [logo,...photos]=await Promise.all([imageUriToDataUrl(company.logoUri),...report.photos.map(imageUriToDataUrl)]);return saveAndShare(buildProjectReportHtmlWithWaste(report,project,loads,waste,company,logo,photos),`Project-Report-${project.name.replace(/[^a-z0-9]+/gi,'-')}-${report.workDate}.pdf`,'Share Project Report');}
export async function exportAndShareProjectCompletion(project:ReportProject,reports:DailyProjectReport[],loads:ProjectCompletionLoad[],waste:ProjectCompletionWasteDump[],company:ProjectReportSetup['company']){const logo=await imageUriToDataUrl(company.logoUri);const photoRefs=reports.flatMap(report=>report.photos.map(uri=>({workDate:report.workDate,uri})));const converted=await Promise.all(photoRefs.map(async photo=>({...photo,src:await imageUriToDataUrl(photo.uri)})));const photos=converted.filter((photo):photo is typeof photo & {src:string}=>!!photo.src).map(({workDate,src})=>({workDate,src}));return saveAndShare(buildProjectCompletionHtml(project,reports,loads,waste,company,logo,photos),`Completed-Project-${project.name.replace(/[^a-z0-9]+/gi,'-')}.pdf`,'Share Completed Project Report');}
export async function exportAndShareQuickText(record:QuickTextDocument){const logo=await imageUriToDataUrl(record.companyLogoUri);const company={name:record.companyName,address:record.companyAddress,phone:record.companyPhone,email:record.companyEmail,taxVatNumber:record.companyTaxVatNumber,receiptFooter:record.companyReceiptFooter};const page={width:record.paperWidth==='58'?176:244,height:record.paperWidth==='58'?500:450};return saveAndShare(buildQuickTextHtml(record,company,logo,{number:record.documentNumber,createdAt:record.createdAt,customerName:record.customerName,projectName:record.projectName}),`Quick-Text-${record.documentNumber}-${record.paperWidth}mm.pdf`,'Share Quick Text',page);}
export async function printQuickText(record:QuickTextDocument){const logo=await imageUriToDataUrl(record.companyLogoUri);const company={name:record.companyName,address:record.companyAddress,phone:record.companyPhone,email:record.companyEmail,taxVatNumber:record.companyTaxVatNumber,receiptFooter:record.companyReceiptFooter};await Print.printAsync({html:buildQuickTextHtml(record,company,logo,{number:record.documentNumber,createdAt:record.createdAt,customerName:record.customerName,projectName:record.projectName})});}
