import * as FileSystem from 'expo-file-system/legacy';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import type {PavementCalculation} from '../domain/pavement';
import {buildWorkbookFromSheets,encodeWorkbookBytes} from './businessWorkbook';

const esc=(value:unknown)=>String(value??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
const safe=(value:string)=>value.replace(/[^a-z0-9]+/gi,'-').replace(/^-|-$/g,'')||'Project';
const total=(records:PavementCalculation[],key:'areaM2'|'theoreticalKg'|'allowanceKg'|'plannedKg')=>records.reduce((sum,row)=>sum+row[key],0);

export async function exportPavementPdf(records:PavementCalculation[],projectName:string){if(!records.length)throw new Error('Save at least one pavement calculation before exporting.');const rows=records.map(row=>`<tr><td>${esc(row.name)}</td><td>${row.areaM2.toFixed(2)}</td><td>${row.spreadRateKgM2.toFixed(1)}</td><td>${row.densityTM3.toFixed(2)}</td><td>${row.thicknessMm.toFixed(1)}</td><td>${row.looseThicknessMm===null?'—':row.looseThicknessMm.toFixed(1)}</td><td>${row.looseThicknessFactor===null?'—':row.looseThicknessFactor.toFixed(2)}</td><td>${(row.theoreticalKg/1000).toFixed(3)}</td><td>${row.allowancePercent.toFixed(1)}%</td><td>${(row.plannedKg/1000).toFixed(3)}</td></tr>`).join('');const html=`<!doctype html><html><head><meta charset="utf-8"><style>@page{margin:12mm}body{font-family:Arial;color:#17212B}h1{color:#173F67}h2{color:#C84B31}.meta{color:#65717D}table{width:100%;border-collapse:collapse;font-size:8px}th{background:#173F67;color:white}th,td{padding:6px;border:1px solid #DDD7CC;text-align:right}th:first-child,td:first-child{text-align:left}.totals{margin-top:16px;padding:12px;background:#FFF8ED;border-left:5px solid #C84B31;font-weight:bold}</style></head><body><h1>DROMEX</h1><h2>Asphalt Pavement Quantity Report</h2><p class="meta">${esc(projectName)} · ${new Date().toLocaleString()}</p><table><thead><tr><th>Layer / section</th><th>Area m²</th><th>kg/m²</th><th>Density t/m³</th><th>Finished mm</th><th>Loose mm</th><th>Factor</th><th>Theoretical t</th><th>Allowance</th><th>Planned t</th></tr></thead><tbody>${rows}</tbody></table><div class="totals">${records.length} calculations · ${total(records,'areaM2').toFixed(2)} m² entered area · ${(total(records,'theoreticalKg')/1000).toFixed(3)} t theoretical · ${(total(records,'plannedKg')/1000).toFixed(3)} t planned</div><p class="meta">Loose thickness is shown only when an entered project/paver factor is available. Quantities are estimates from entered geometry, spread rates, density, factor, and allowances. Approved project drawings, mix design, trial strip, and engineer requirements control construction.</p></body></html>`;const result=await Print.printToFileAsync({html});if(!(await Sharing.isAvailableAsync()))throw new Error(`PDF saved at ${result.uri}, but sharing is unavailable.`);await Sharing.shareAsync(result.uri,{mimeType:'application/pdf',UTI:'com.adobe.pdf',dialogTitle:'Share Pavement Quantity PDF'});return result.uri;}

export async function exportPavementExcel(records:PavementCalculation[],projectName:string){if(!records.length)throw new Error('Save at least one pavement calculation before exporting.');if(!FileSystem.documentDirectory)throw new Error('Document storage is unavailable.');const summary=[{'Project':projectName,'Calculations':records.length,'Entered area total m²':total(records,'areaM2'),'Theoretical total t':total(records,'theoreticalKg')/1000,'Allowance total t':total(records,'allowanceKg')/1000,'Planned total t':total(records,'plannedKg')/1000}];const calculations=records.map(row=>({'Project':row.projectName,'Layer / section':row.name,'Length m':row.lengthM,'Width m':row.widthM,'Area m²':row.areaM2,'Spread kg/m²':row.spreadRateKgM2,'Density t/m³':row.densityTM3,'Finished compacted thickness mm':row.thicknessMm,'Loose thickness factor':row.looseThicknessFactor,'Before-compaction loose thickness mm':row.looseThicknessMm,'Theoretical kg':row.theoreticalKg,'Theoretical t':row.theoreticalKg/1000,'Allowance %':row.allowancePercent,'Allowance kg':row.allowanceKg,'Planned kg':row.plannedKg,'Planned t':row.plannedKg/1000,'Notes':row.notes,'Updated':row.updatedAt}));const bytes=buildWorkbookFromSheets([{name:'Project Summary',rows:summary},{name:'Pavement Calculations',rows:calculations}]);const directory=`${FileSystem.documentDirectory}exports/`;await FileSystem.makeDirectoryAsync(directory,{intermediates:true});const uri=`${directory}DROMEX-Pavement-${safe(projectName)}-${Date.now()}.xlsx`;await FileSystem.writeAsStringAsync(uri,encodeWorkbookBytes(bytes),{encoding:FileSystem.EncodingType.Base64});if(!(await Sharing.isAvailableAsync()))throw new Error(`Excel workbook saved at ${uri}, but sharing is unavailable.`);await Sharing.shareAsync(uri,{mimeType:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',UTI:'org.openxmlformats.spreadsheetml.sheet',dialogTitle:'Share Pavement Quantity Excel'});return uri;}
