import {netWorkMinutes,type DailyProjectReport,type LinkedFuelFill,type LinkedProjectLoad,type LinkedQuarryLoad,type LinkedWasteDump,type ProjectReportSetup,type ReportProject} from '../domain/projectReports';

const e=(value:unknown)=>String(value??'').replace(/[&<>"']/g,(c)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]??c));
const display=(value:string|null|undefined)=>value?.trim()?e(value):'&mdash;';
const list=(values:string[])=>values.length?values.map(e).join('; '):'&mdash;';
const fmt=(value:number)=>Number.isInteger(value)?String(value):value.toFixed(3).replace(/0+$/,'').replace(/\.$/,'');

export function buildProjectReportHtmlWithWaste(report:DailyProjectReport,project:ReportProject,loads:LinkedProjectLoad[],quarry:LinkedQuarryLoad[],waste:LinkedWasteDump[],fuel:LinkedFuelFill[],company:ProjectReportSetup['company'],logo:string|null,photos:(string|null)[],includePrices?:boolean):string;
export function buildProjectReportHtmlWithWaste(report:DailyProjectReport,project:ReportProject,loads:LinkedProjectLoad[],waste:LinkedWasteDump[],company:ProjectReportSetup['company'],logo:string|null,photos:(string|null)[]):string;
export function buildProjectReportHtmlWithWaste(report:DailyProjectReport,project:ReportProject,loads:LinkedProjectLoad[],quarryOrWaste:LinkedQuarryLoad[]|LinkedWasteDump[],wasteOrCompany:LinkedWasteDump[]|ProjectReportSetup['company'],fuelOrLogo:LinkedFuelFill[]|string|null,companyOrPhotos:ProjectReportSetup['company']|(string|null)[],logo?:string|null,photosArg?:(string|null)[],includePricesArg=false){
  const current=Array.isArray(wasteOrCompany);const quarry=current?quarryOrWaste as LinkedQuarryLoad[]:[];const waste=current?wasteOrCompany as LinkedWasteDump[]:quarryOrWaste as LinkedWasteDump[];const fuel=current?fuelOrLogo as LinkedFuelFill[]:[];const company=(current?companyOrPhotos:wasteOrCompany) as ProjectReportSetup['company'];const resolvedLogo=current?logo:fuelOrLogo as string|null;const photos=(current?photosArg:companyOrPhotos) as (string|null)[];
  const includePrices=current&&includePricesArg;
  const minutes=netWorkMinutes(report);
  const updatedDate=new Date(report.updatedAt);const updatedLabel=Number.isNaN(updatedDate.getTime())?'Not available':updatedDate.toLocaleString();
  const timeValue=minutes==null?'Not recorded':`${Math.floor(minutes/60)}h ${minutes%60}m`;
  const timeNote=report.workStartTime&&report.workEndTime?`${e(report.workStartTime)} to ${e(report.workEndTime)}${report.breakMinutes?` &middot; ${e(report.breakMinutes)} min break`:''}`:'No working time entered';
  const wasteGroups=[...waste.reduce((map,dump)=>{const key=`${dump.dumpLocation}\u0000${dump.materialType}`;const prior=map.get(key);map.set(key,{location:dump.dumpLocation,material:dump.materialType,count:(prior?.count??0)+1});return map;},new Map<string,{location:string;material:string;count:number}>()).values()];
  const materialRows=report.materials.map(material=>`<tr><td>${e(material.movement==='used'?'Used':'Transported')}</td><td>${e(material.itemName)}</td><td class="number">${fmt(material.quantity)}</td><td>${e(material.unitSymbol)}</td></tr>`).join('')||'<tr><td colspan="4" class="empty">No materials recorded</td></tr>';
  const loadRows=loads.map(load=>`<tr><td>${e(load.transactionNumber)}</td><td>${e(load.itemName)}</td><td>${fmt(load.quantity)} ${e(load.unitSymbol)}</td><td>${e(load.driverName)}</td><td>${e(load.truckPlate)}</td>${includePrices?`<td class="number">${load.finalTotalUsd==null?'Unpriced':`$${load.finalTotalUsd.toFixed(2)}`}</td>`:''}</tr>`).join('')||`<tr><td colspan="${includePrices?6:5}" class="empty">No project-linked loads for this date</td></tr>`;
  const quarryRows=quarry.map(load=>`<tr><td>${e(load.purchaseNumber)}</td><td>${e(load.supplierName)}</td><td>${e(load.itemName)}</td><td>${fmt(load.quantity)} ${e(load.unitSymbol)}</td><td>${e(load.deliveryLabel)}</td><td>${display(load.truckPlate)}</td><td>${display(load.supplierTicketNumber)}</td>${includePrices?`<td class="number">${load.finalTotalUsd==null?'Unpriced':`$${load.finalTotalUsd.toFixed(2)}`}</td>`:''}</tr>`).join('')||`<tr><td colspan="${includePrices?8:7}" class="empty">No project-linked supplier loads for this date</td></tr>`;
  const fuelRows=fuel.map(fill=>`<tr><td>${new Date(fill.confirmedAt).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</td><td>${e(fill.equipmentName)}</td><td class="number">${fmt(fill.litres)} L</td>${includePrices?`<td class="number">${fill.pricePerLitreUsd==null?'Unpriced':`$${fill.pricePerLitreUsd.toFixed(2)}/L`}</td><td class="number">${fill.consumptionCostUsd==null?'&mdash;':`$${fill.consumptionCostUsd.toFixed(2)}`}</td>`:''}<td>${display(fill.odometerReading)}</td></tr>`).join('')||`<tr><td colspan="${includePrices?6:4}" class="empty">No project-linked fuel fills for this date</td></tr>`;
  const fuelLitres=fuel.reduce((sum,fill)=>sum+fill.litres,0),fuelCost=fuel.reduce((sum,fill)=>sum+(fill.consumptionCostUsd??0),0),unpricedFuel=fuel.filter(fill=>fill.consumptionCostUsd==null).reduce((sum,fill)=>sum+fill.litres,0);
  const wasteRows=wasteGroups.map(group=>`<tr><td>${e(group.material)}</td><td>${e(group.location)}</td><td class="number">${group.count}</td></tr>`).join('')||'<tr><td colspan="3" class="empty">No completed waste dumps for this date</td></tr>';
  const safetyRows=[...report.workers.map(name=>({name,type:'Worker',key:'worker'})),...report.drivers.map(name=>({name,type:'Truck Driver',key:'driver'}))].map(person=>{const safety=(report.workerSafety??[]).find(value=>value.workerName===person.name&&(value.participantType??'worker')===person.key);const status=safety?.status==='compliant'?'Compliant':safety?.status==='missing'?'Missing PPE':'Not checked';const statusColor=safety?.status==='compliant'?'#287A55':safety?.status==='missing'?'#9A6512':'#65717D';const details=safety?.status==='missing'?(safety.missingItems.join(', ')||'Missing item not specified'):'—';return`<tr><td>${e(person.name)}</td><td>${e(person.type)}</td><td><span style="color:${statusColor};font-weight:700">${e(status)}</span></td><td>${e(details)}</td><td>${display(safety?.notes)}</td></tr>`;}).join('')||'<tr><td colspan="5" class="empty">No workers or truck drivers recorded</td></tr>';
  const photoHtml=photos.filter((photo):photo is string=>!!photo).map((src,index)=>`<figure><img src="${src}"/><figcaption>Photo ${index+1} &middot; ${e(report.workDate)}</figcaption></figure>`).join('')||'<div class="empty-photo">No photos attached to this daily report</div>';
  const modeBadge=`<span class="mode-badge${includePrices?' mode-badge-prices':''}">${includePrices?'WITH PRICES':'NO PRICES'}</span>`;
  return `<!doctype html><html><head><meta charset="utf-8"><style>
    @page{size:A4;margin:13mm 13mm 15mm}*{box-sizing:border-box}body{margin:0;font-family:Arial,sans-serif;color:#17212b;font-size:9pt;line-height:1.4}
    header{display:flex;justify-content:space-between;align-items:flex-start;border-bottom:3px solid #c84b31;padding-bottom:4mm;margin-bottom:5mm}
    .brand img{max-width:36mm;max-height:18mm}.brand-name{font-size:16pt;font-weight:900;color:#17212b}.company-line{font-size:7.5pt;color:#65717d;margin-top:1mm}
    .report-title{text-align:right}.report-title h1{font-size:14pt;line-height:1.05;margin:0;color:#173f67;letter-spacing:1.2pt;font-weight:900}.report-title p{font-size:7.5pt;margin:1.5mm 0 1mm;color:#65717d}
    .mode-badge{display:inline-block;border:1px solid #173f67;color:#173f67;font-size:7.5pt;font-weight:700;padding:1mm 2.8mm;border-radius:3mm;letter-spacing:.4pt}.mode-badge-prices{border-color:#c84b31;color:#8e2e1b}
    .project-line{display:grid;grid-template-columns:1fr 1fr;gap:3mm 8mm;margin-bottom:5mm;padding-bottom:4mm;border-bottom:1px solid #e3d6c2}
    .label{display:block;color:#65717d;font-size:7.5pt;font-weight:700;letter-spacing:.5pt;margin-bottom:.8mm;text-transform:uppercase}.value{font-size:10.5pt;font-weight:700;color:#17212b}
    .cards{display:grid;grid-template-columns:repeat(4,1fr);gap:2.5mm;margin:4mm 0}
    .card{min-height:24mm;padding:3mm;background:#fff8ed;border:1px solid #e3d6c2;border-left:3px solid #173f67}
    .card strong{display:block;font-size:16pt;font-weight:900;line-height:1;color:#17212b}.card b{display:block;font-size:7.5pt;font-weight:700;letter-spacing:.3pt;margin-top:2mm;color:#173f67}.card small{display:block;color:#65717d;font-size:7pt;margin-top:2mm}
    h2{font-size:12.5pt;font-weight:700;color:#17212b;margin:5mm 0 2mm;padding-bottom:1mm;border-bottom:2px solid #c84b31}
    .panel{padding:3.5mm 4mm;background:#fff8ed;border:1px solid #e3d6c2;border-left:3px solid #173f67;break-inside:avoid}
    .panel-attention{background:#fce8e6;border-color:#e3b7b0;border-left-color:#b3261e}
    .panel h3{margin:0 0 2mm;font-size:10pt;font-weight:700;color:#17212b}.panel p{margin:0;white-space:pre-wrap;font-size:9pt}
    .two{display:grid;grid-template-columns:1fr 1fr;gap:2.5mm}.section{break-inside:avoid}
    table{width:100%;border-collapse:collapse;font-size:8pt}thead{display:table-header-group}
    th{background:#e7eef5;color:#173f67;text-align:left;font-size:7.5pt;font-weight:700;letter-spacing:.2pt}
    th,td{border:1px solid #d9d5ce;padding:2.2mm 2mm;vertical-align:top}
    .table-accent-company th:first-child,.table-accent-supplier th:first-child{border-left-width:3px}
    .table-accent-company th{border-top:2px solid #c84b31}.table-accent-supplier th{border-top:2px solid #173f67}
    .number{text-align:right}.empty{text-align:center;color:#65717d;padding:5mm}
    .page-two{page-break-before:always}.notes-grid{display:grid;grid-template-columns:1fr 1fr;gap:2.5mm}
    .photos{display:grid;grid-template-columns:1fr 1fr;gap:4mm}.photos figure{margin:0;break-inside:avoid}.photos img{width:100%;height:73mm;object-fit:contain;background:#f5f2ec;border-radius:2mm;border:1px solid #e3d6c2}.photos figcaption{font-size:7.5pt;color:#65717d;margin-top:1mm}
    .empty-photo{grid-column:1/-1;background:#f5f2ec;color:#65717d;padding:16mm;text-align:center;border:1px dashed #d9d5ce}
    .footer-note{margin-top:5mm;border-top:1px solid #d9d5ce;padding-top:2mm;color:#65717d;font-size:7pt}
    .source-label{display:flex;align-items:center;gap:2mm;margin:3mm 0 1.5mm}.source-label h3{margin:0;font-size:10pt;font-weight:700;color:#17212b}.source-chip{font-size:7pt;font-weight:700;letter-spacing:.3pt;padding:.6mm 2mm;border-radius:2.5mm;color:#fff}.source-chip-company{background:#c84b31}.source-chip-supplier{background:#173f67}
  </style></head><body>
    <header><div class="brand">${resolvedLogo?`<img src="${resolvedLogo}"/>`:`<div class="brand-name">${e(company.name)}</div>`}<div class="company-line">${[company.address,company.phone,company.email].filter(Boolean).map(e).join(' &middot; ')}</div></div><div class="report-title"><h1>DAILY PROJECT REPORT</h1><p>${e(report.workDate)}</p>${modeBadge}</div></header>
    <div class="project-line"><div><span class="label">Project</span><span class="value">${e(project.name)}</span></div><div><span class="label">Contractor</span><span class="value">${e(company.name)}</span></div><div><span class="label">Location</span>${e(project.location)}</div><div><span class="label">Work date</span>${e(report.workDate)}</div></div>
    <div class="cards"><div class="card"><strong>${e(timeValue)}</strong><b>NET WORKING TIME</b><small>${timeNote}</small></div><div class="card"><strong>${loads.length+quarry.length}</strong><b>LOADS DELIVERED</b><small>${loads.length} company &middot; ${quarry.length} supplier</small></div><div class="card"><strong>${fmt(fuelLitres)} L</strong><b>FUEL USED</b><small>${includePrices?`$${fuelCost.toFixed(2)}${unpricedFuel?` &middot; ${fmt(unpricedFuel)} L unpriced`:''}`:'Operational quantities only'}</small></div><div class="card"><strong>${photos.filter(Boolean).length}</strong><b>PHOTOS</b><small>Saved with this report</small></div></div>
    <section class="section"><h2>Work performed today</h2><div class="panel"><h3>Daily work description</h3><p>${display(report.workDescription)}</p></div></section>
    <section class="section"><h2>Time and site conditions</h2><div class="two"><div class="panel"><h3>Working time</h3><p>Start ${display(report.workStartTime)} &middot; End ${display(report.workEndTime)} &middot; Break ${report.breakMinutes?`${e(report.breakMinutes)} minutes`:'&mdash;'}<br/><b>Net ${e(timeValue)}</b></p></div><div class="panel"><h3>Weather and site</h3><p>${display(report.weatherSiteConditions)}</p></div></div></section>
    <section class="section"><h2>People and equipment</h2><table><thead><tr><th>Section</th><th>Count</th><th>Present today</th></tr></thead><tbody><tr><td>Workers</td><td class="number">${report.workers.length}</td><td>${list(report.workers)}</td></tr><tr><td>Drivers</td><td class="number">${report.drivers.length}</td><td>${list(report.drivers)}</td></tr><tr><td>Trucks</td><td class="number">${report.truckPlates.length}</td><td>${list(report.truckPlates)}</td></tr><tr><td>Machines</td><td class="number">${report.machines.length}</td><td>${list(report.machines)}</td></tr></tbody></table></section>
    <section class="section"><h2>Worker safety / PPE</h2><table><thead><tr><th>Person</th><th>Role</th><th>Status</th><th>Missing PPE</th><th>Notes</th></tr></thead><tbody>${safetyRows}</tbody></table></section>
    <section class="section"><h2>Materials used or transported</h2><table class="materials"><thead><tr><th>Movement</th><th>Material</th><th>Quantity</th><th>Unit</th></tr></thead><tbody>${materialRows}</tbody></table></section>
    <div class="page-two">
      <header><div class="brand">${resolvedLogo?`<img src="${resolvedLogo}"/>`:`<div class="brand-name">${e(company.name)}</div>`}</div><div class="report-title"><h1>DAILY PROJECT REPORT</h1><p>${e(project.name)} &middot; ${e(report.workDate)}</p>${modeBadge}</div></header>
      <section><h2>Loads delivered that day</h2><div class="source-label"><h3>Company Loads</h3><span class="source-chip source-chip-company">DROMEX / COMPANY</span></div><table class="table-accent-company"><thead><tr><th>Transaction</th><th>Item</th><th>Quantity</th><th>Driver</th><th>Truck</th>${includePrices?'<th>Total</th>':''}</tr></thead><tbody>${loadRows}</tbody></table><div class="source-label"><h3>Supplier Loads</h3><span class="source-chip source-chip-supplier">SUPPLIER</span></div><table class="table-accent-supplier"><thead><tr><th>Reference</th><th>Supplier</th><th>Item</th><th>Quantity</th><th>Delivery</th><th>Truck</th><th>Ticket</th>${includePrices?'<th>Total</th>':''}</tr></thead><tbody>${quarryRows}</tbody></table></section>
      <section><h2>Fuel used that day</h2><table><thead><tr><th>Time</th><th>Equipment</th><th>Litres</th>${includePrices?'<th>Price</th><th>Cost</th>':''}<th>Odometer</th></tr></thead><tbody>${fuelRows}</tbody></table></section>
      <section><h2>Waste dumps completed that day</h2><div class="two"><div class="card"><strong>${waste.length}</strong><b>TOTAL DUMPS</b><small>Total completed dumps: ${waste.length}</small></div><table class="waste"><thead><tr><th>Material</th><th>Dump location</th><th>Dumps</th></tr></thead><tbody>${wasteRows}</tbody></table></div></section>
      <section><h2>Site notes and follow-up</h2><div class="notes-grid"><div class="panel"><h3>General notes</h3><p>${display(report.notes)}</p></div><div class="panel panel-attention"><h3>Problems, delays, or incidents</h3><p>${display(report.problemsDelaysIncidents)}</p></div><div class="panel"><h3>Next work planned</h3><p>${display(report.nextWorkPlanned)}</p></div><div class="panel"><h3>Daily report status</h3><p>Saved project-day record<br/>Updated ${e(updatedLabel)}</p></div></div></section>
      <section><h2>Photo evidence</h2><div class="photos">${photoHtml}</div></section>
      <div class="footer-note">Linked company loads, supplier loads, fuel fills, and waste dumps are read-only here. Corrections are made in their original operational records and automatically appear in later exports.</div>
    </div>
  </body></html>`;
}
