import {netWorkMinutes,type DailyProjectReport,type LinkedProjectLoad,type LinkedWasteDump,type ProjectReportSetup,type ReportProject} from '../domain/projectReports';

const e=(value:unknown)=>String(value??'').replace(/[&<>"']/g,(c)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]??c));
const display=(value:string|null|undefined)=>value?.trim()?e(value):'&mdash;';
const list=(values:string[])=>values.length?values.map(e).join('; '):'&mdash;';
const fmt=(value:number)=>Number.isInteger(value)?String(value):value.toFixed(3).replace(/0+$/,'').replace(/\.$/,'');

export function buildProjectReportHtmlWithWaste(report:DailyProjectReport,project:ReportProject,loads:LinkedProjectLoad[],waste:LinkedWasteDump[],company:ProjectReportSetup['company'],logo:string|null,photos:(string|null)[]){
  const minutes=netWorkMinutes(report);
  const updatedDate=new Date(report.updatedAt);const updatedLabel=Number.isNaN(updatedDate.getTime())?'Not available':updatedDate.toLocaleString();
  const timeValue=minutes==null?'Not recorded':`${Math.floor(minutes/60)}h ${minutes%60}m`;
  const timeNote=report.workStartTime&&report.workEndTime?`${e(report.workStartTime)} to ${e(report.workEndTime)}${report.breakMinutes?` &middot; ${e(report.breakMinutes)} min break`:''}`:'No working time entered';
  const wasteGroups=[...waste.reduce((map,dump)=>{const key=`${dump.dumpLocation}\u0000${dump.materialType}`;const prior=map.get(key);map.set(key,{location:dump.dumpLocation,material:dump.materialType,count:(prior?.count??0)+1});return map;},new Map<string,{location:string;material:string;count:number}>()).values()];
  const materialRows=report.materials.map(material=>`<tr><td>${e(material.movement==='used'?'Used':'Transported')}</td><td>${e(material.itemName)}</td><td class="number">${fmt(material.quantity)}</td><td>${e(material.unitSymbol)}</td></tr>`).join('')||'<tr><td colspan="4" class="empty">No materials recorded</td></tr>';
  const loadRows=loads.map(load=>`<tr><td>${e(load.transactionNumber)}</td><td>${e(load.itemName)}</td><td>${fmt(load.quantity)} ${e(load.unitSymbol)}</td><td>${e(load.driverName)}</td><td>${e(load.truckPlate)}</td></tr>`).join('')||'<tr><td colspan="5" class="empty">No project-linked loads for this date</td></tr>';
  const wasteRows=wasteGroups.map(group=>`<tr><td>${e(group.material)}</td><td>${e(group.location)}</td><td class="number">${group.count}</td></tr>`).join('')||'<tr><td colspan="3" class="empty">No completed waste dumps for this date</td></tr>';
  const photoHtml=photos.filter((photo):photo is string=>!!photo).map((src,index)=>`<figure><img src="${src}"/><figcaption>Photo ${index+1} &middot; ${e(report.workDate)}</figcaption></figure>`).join('')||'<div class="empty-photo">No photos attached to this daily report</div>';
  return `<!doctype html><html><head><meta charset="utf-8"><style>
    @page{size:A4;margin:13mm 13mm 15mm}*{box-sizing:border-box}body{margin:0;font-family:Arial,sans-serif;color:#17212b;font-size:9pt;line-height:1.38}header{display:flex;justify-content:space-between;align-items:flex-start;border-bottom:3px solid #c84b31;padding-bottom:4mm;margin-bottom:5mm}.brand img{max-width:36mm;max-height:18mm}.brand-name{font-size:16pt;font-weight:900;color:#17212b}.company-line{font-size:7.5pt;color:#65717d;margin-top:1mm}.report-title{text-align:right}.report-title h1{font-size:13pt;line-height:1.05;margin:0;color:#8e2e1b;letter-spacing:.5pt}.report-title p{font-size:7.5pt;margin:1.5mm 0 0;color:#65717d}.project-line{display:grid;grid-template-columns:1fr 1fr;gap:3mm 8mm;margin-bottom:5mm}.label{display:block;color:#65717d;font-size:7.5pt;font-weight:700;margin-bottom:.8mm}.value{font-size:10pt;font-weight:800}.cards{display:grid;grid-template-columns:repeat(4,1fr);gap:2mm;margin:4mm 0}.card{min-height:24mm;padding:3mm;border:1px solid;border-left-width:3px}.card strong{display:block;font-size:17pt;line-height:1;color:#17212b}.card b{display:block;font-size:7.5pt;margin-top:2mm}.card small{display:block;color:#65717d;font-size:7pt;margin-top:2mm}.green{background:#e5f3ec;border-color:#26735b}.blue{background:#e7f1f8;border-color:#2e638a}.orange{background:#fff3d8;border-color:#a66a13}.purple{background:#f0e9f5;border-color:#73518c}h2{font-size:13pt;color:#17212b;margin:5mm 0 2mm}.panel{padding:3.5mm 4mm;border:1px solid;border-left-width:3px;break-inside:avoid}.panel h3{margin:0 0 2mm;font-size:10.5pt}.panel p{margin:0;white-space:pre-wrap}.two{display:grid;grid-template-columns:1fr 1fr;gap:2.5mm}.section{break-inside:avoid}table{width:100%;border-collapse:collapse;font-size:8pt}thead{display:table-header-group}th{background:#e7f1f8;color:#17212b;text-align:left;font-size:7.5pt}th,td{border:1px solid #d9d5ce;padding:2mm;vertical-align:top}.materials th{background:#e5f3ec}.waste th{background:#fff3d8}.number{text-align:right}.empty{text-align:center;color:#65717d;padding:5mm}.page-two{page-break-before:always}.notes-grid{display:grid;grid-template-columns:1fr 1fr;gap:2.5mm}.photos{display:grid;grid-template-columns:1fr 1fr;gap:4mm}.photos figure{margin:0;break-inside:avoid}.photos img{width:100%;height:73mm;object-fit:contain;background:#f5f2ec;border-radius:2mm}.photos figcaption{font-size:7.5pt;color:#65717d;margin-top:1mm}.empty-photo{grid-column:1/-1;background:#f5f2ec;color:#65717d;padding:16mm;text-align:center}.footer-note{margin-top:5mm;border-top:1px solid #d9d5ce;padding-top:2mm;color:#65717d;font-size:7pt}
  </style></head><body>
    <header><div class="brand">${logo?`<img src="${logo}"/>`:`<div class="brand-name">${e(company.name)}</div>`}<div class="company-line">${[company.address,company.phone,company.email].filter(Boolean).map(e).join(' &middot; ')}</div></div><div class="report-title"><h1>DPR</h1><p>${e(report.workDate)} &middot; SAVED</p></div></header>
    <div class="project-line"><div><span class="label">PROJECT</span><span class="value">${e(project.name)}</span></div><div><span class="label">CUSTOMER</span><span class="value">${e(project.customerName)}</span></div><div><span class="label">LOCATION</span>${e(project.location)}</div><div><span class="label">WORK DATE</span>${e(report.workDate)}</div></div>
    <div class="cards"><div class="card green"><strong>${e(timeValue)}</strong><b>NET WORKING TIME</b><small>${timeNote}</small></div><div class="card blue"><strong>${loads.length}</strong><b>LOADS DELIVERED</b><small>Automatically linked records</small></div><div class="card orange"><strong>${waste.length}</strong><b>WASTE DUMPS</b><small>Total completed dumps: ${waste.length}</small></div><div class="card purple"><strong>${photos.filter(Boolean).length}</strong><b>PHOTOS</b><small>Saved with this report</small></div></div>
    <section class="section"><h2>Work performed today</h2><div class="panel blue"><h3>Daily work description</h3><p>${display(report.workDescription)}</p></div></section>
    <section class="section"><h2>Time and site conditions</h2><div class="two"><div class="panel green"><h3>Working time</h3><p>Start ${display(report.workStartTime)} &middot; End ${display(report.workEndTime)} &middot; Break ${report.breakMinutes?`${e(report.breakMinutes)} minutes`:'&mdash;'}<br/><b>Net ${e(timeValue)}</b></p></div><div class="panel orange"><h3>Weather and site</h3><p>${display(report.weatherSiteConditions)}</p></div></div></section>
    <section class="section"><h2>People and equipment</h2><table><thead><tr><th>Section</th><th>Count</th><th>Present today</th></tr></thead><tbody><tr><td>Workers</td><td class="number">${report.workers.length}</td><td>${list(report.workers)}</td></tr><tr><td>Drivers</td><td class="number">${report.drivers.length}</td><td>${list(report.drivers)}</td></tr><tr><td>Trucks</td><td class="number">${report.truckPlates.length}</td><td>${list(report.truckPlates)}</td></tr><tr><td>Machines</td><td class="number">${report.machines.length}</td><td>${list(report.machines)}</td></tr></tbody></table></section>
    <section class="section"><h2>Materials used or transported</h2><table class="materials"><thead><tr><th>Movement</th><th>Material</th><th>Quantity</th><th>Unit</th></tr></thead><tbody>${materialRows}</tbody></table></section>
    <div class="page-two">
      <header><div class="brand">${logo?`<img src="${logo}"/>`:`<div class="brand-name">${e(company.name)}</div>`}</div><div class="report-title"><h1>DPR</h1><p>${e(project.name)} &middot; ${e(report.workDate)}</p></div></header>
      <section><h2>Loads delivered that day</h2><table><thead><tr><th>Transaction</th><th>Item</th><th>Quantity</th><th>Driver</th><th>Truck</th></tr></thead><tbody>${loadRows}</tbody></table></section>
      <section><h2>Waste dumps completed that day</h2><div class="two"><div class="card orange"><strong>${waste.length}</strong><b>TOTAL DUMPS</b><small>Total completed dumps: ${waste.length}</small></div><table class="waste"><thead><tr><th>Material</th><th>Dump location</th><th>Dumps</th></tr></thead><tbody>${wasteRows}</tbody></table></div></section>
      <section><h2>Site notes and follow-up</h2><div class="notes-grid"><div class="panel blue"><h3>General notes</h3><p>${display(report.notes)}</p></div><div class="panel" style="background:#fce8e6;border-color:#c84b31"><h3>Problems, delays, or incidents</h3><p>${display(report.problemsDelaysIncidents)}</p></div><div class="panel green"><h3>Next work planned</h3><p>${display(report.nextWorkPlanned)}</p></div><div class="panel purple"><h3>Daily report status</h3><p>Saved project-day record<br/>Updated ${e(updatedLabel)}</p></div></div></section>
      <section><h2>Photo evidence</h2><div class="photos">${photoHtml}</div></section>
      <div class="footer-note">Linked loads and waste dumps are read-only here. Corrections are made in their original operational records and automatically appear in later exports.</div>
    </div>
  </body></html>`;
}
