import{describe,expect,it}from'vitest';
import{buildBusinessWorkbook,buildBusinessWorkbookAsync,sheetsForBusinessReport}from'../src/services/businessWorkbook';
import{strFromU8,unzipSync}from'fflate';
import{emptyBusinessReportFilters,filterBusinessReportData,type BusinessReportData}from'../src/domain/businessReports';

const data:BusinessReportData={generatedAt:'2026-08-13T12:00:00.000Z',companyName:'DROMEX',loads:[{'Record ID':'l1','Final Total USD':111,'Project ID':'p1'}],customers:[],payments:[],openingBalances:[],quarryPurchases:[],suppliers:[],fuelMovements:[{'Movement ID':'f1','Type':'gauge','Status':'Active','Gauge Litres':5000,'Confirmed At':'2026-08-13T08:00:00Z','Balance After Litres':5000,'Correction Difference':200}],equipmentTotals:[],projects:[],dailyReports:[],materials:[]};

describe('business workbooks',()=>{
  it('builds all analysis sheets with clear overviews, native charts, and filterable frozen headers',()=>{const files=unzipSync(buildBusinessWorkbook('analysis',data)),workbook=strFromU8(files['xl/workbook.xml']!),overview=strFromU8(files['xl/worksheets/sheet1.xml']!),sheet=strFromU8(files['xl/worksheets/sheet2.xml']!);expect((workbook.match(/<sheet /g)??[]).length).toBe(16);expect(workbook).toContain('name="Report Overview"');expect(workbook).toContain('name="Financial Charts"');expect(workbook).toContain('name="Operations Charts"');expect(workbook).toContain('name="Data Dictionary"');expect(overview).toContain('Report title');expect(overview).toContain('Complete Analysis Workbook');expect(sheet).toContain('<autoFilter ref=');expect(sheet).toContain('state="frozen"');expect(files['xl/charts/chart1.xml']).toBeDefined();expect(files['xl/charts/chart2.xml']).toBeDefined();expect(files['xl/drawings/drawing1.xml']).toBeDefined();});
  it('includes current and latest gauge facts in fuel summary',()=>{const sheets=sheetsForBusinessReport('fuel',data);expect(sheets.map(v=>v.name)).toEqual(['Report Overview','Balance Summary','Charts','Movement Details','Project Cost Totals','Machine Cost Totals','Payment Details']);expect(sheets[1]?.rows).toContainEqual({'Metric':'Latest physical gauge litres','Value':5000});});
  it('filters workbook records and records a readable selected scope',()=>{const source:BusinessReportData={...data,projects:[{'Project ID':'p2','Project':'Harbour Extension'}],loads:[{'Record ID':'l1','Confirmed At':'2026-08-10T08:00:00Z','Project ID':'p1','Customer ID':'c1','Item':'Sand','Payment Status':'Paid'},{'Record ID':'l2','Confirmed At':'2026-08-12T08:00:00Z','Project ID':'p2','Customer ID':'c2','Item':'Stone','Payment Status':'Unpaid'}]};const filtered=filterBusinessReportData(source,{...emptyBusinessReportFilters,fromDate:'2026-08-11',projectId:'p2',paymentStatus:'Unpaid'});expect(filtered.loads.map(row=>row['Record ID'])).toEqual(['l2']);expect(sheetsForBusinessReport('loads',filtered)[0]?.name).toBe('Report Overview');expect(filtered.activeFilters).toContainEqual({'Filter':'Project','Value':'Harbour Extension'});expect(filtered.activeFilters).toContainEqual({'Filter':'Date range','Value':'2026-08-11 to Today'});});
  it('keeps every payment linked to a matching load regardless of payment date',()=>{const source:BusinessReportData={...data,loads:[{'Record ID':'l1','Confirmed At':'2026-08-10T08:00:00Z','Project ID':'p1','Customer ID':'c1','Item':'Sand','Payment Status':'Partially Paid'},{'Record ID':'l2','Confirmed At':'2026-07-01T08:00:00Z','Project ID':'p1','Customer ID':'c1','Item':'Sand','Payment Status':'Paid'}],payments:[{'Payment ID':'pay-late','Target Record ID':'l1','Target Type':'load','Payment Date':'2026-09-01','Status':'Active','Amount USD':40},{'Payment ID':'pay-cancelled','Target Record ID':'l1','Target Type':'load','Payment Date':'2026-09-02','Status':'Cancelled','Amount USD':10},{'Payment ID':'pay-unrelated','Target Record ID':'l2','Target Type':'load','Payment Date':'2026-08-10','Status':'Active','Amount USD':90}]};const filtered=filterBusinessReportData(source,{...emptyBusinessReportFilters,fromDate:'2026-08-01',toDate:'2026-08-31'});expect(filtered.loads.map(row=>row['Record ID'])).toEqual(['l1']);expect(filtered.payments.map(row=>row['Payment ID'])).toEqual(['pay-late','pay-cancelled']);const sheets=sheetsForBusinessReport('loads',filtered);expect(sheets.map(sheet=>sheet.name)).toContain('Payment Details');expect(sheets.find(sheet=>sheet.name==='Payment Details')?.rows).toHaveLength(2);});
  it('includes project operational details in the project workbook',()=>{const sheets=sheetsForBusinessReport('projects',data);expect(sheets.map(sheet=>sheet.name)).toEqual(['Report Overview','Charts','Project Summary','Project Loads','Supplier Loads','Fuel Movements','Payment Details','Daily Report Index','Materials Summary']);});
  it('creates Arabic RTL sheets while preserving entered business text and Western digits',()=>{const arabicData={...data,companyName:'DROMEX شركة',loads:[{'Record ID':'load-123','Item':'رمل Sand','Final Total USD':1250}]};const files=unzipSync(buildBusinessWorkbook('loads',arabicData,'ar')),workbook=strFromU8(files['xl/workbook.xml']!),overview=strFromU8(files['xl/worksheets/sheet1.xml']!),details=strFromU8(files['xl/worksheets/sheet4.xml']!);expect(workbook).toContain('نظرة عامة على التقرير');expect(overview).toContain('rightToLeft="1"');expect(overview).toContain('عنوان التقرير');expect(overview).toContain('الأحمال والمبيعات');expect(details).toContain('رمل Sand');expect(details).toContain('load-123');expect(details).toContain('<v>1250</v>');});
  it('adds at least one native chart to every business workbook',()=>{for(const kind of ['loads','customers','quarry','fuel','projects','analysis'] as const){const files=unzipSync(buildBusinessWorkbook(kind,data));expect(Object.keys(files).some(path=>path.startsWith('xl/charts/chart'))).toBe(true);expect(Object.keys(files).some(path=>path.startsWith('xl/drawings/drawing'))).toBe(true);}});
  it('reports monotonic generation progress and produces a valid asynchronous workbook',async()=>{const updates:number[]=[];const bytes=await buildBusinessWorkbookAsync('analysis',data,{onProgress:value=>updates.push(value.percent)});const files=unzipSync(bytes);expect(files['xl/workbook.xml']).toBeDefined();expect(updates.length).toBeGreaterThan(5);expect(updates.every((value,index)=>index===0||value>=updates[index-1]!)).toBe(true);expect(updates.at(-1)).toBe(82);});
  it('stops safely when cancellation is requested between workbook stages',async()=>{const controller=new AbortController();const promise=buildBusinessWorkbookAsync('analysis',data,{signal:controller.signal,onProgress:value=>{if(value.stage==='building')controller.abort();}});await expect(promise).rejects.toMatchObject({name:'AbortError',message:'Workbook export cancelled.'});});
  it('reconciles thousands of filtered parent records and every linked payment within a practical time',async()=>{const loadCount=4000;const loads=Array.from({length:loadCount},(_,index)=>({'Record ID':`load-${index}`,'Confirmed At':index%2===0?'2026-08-10T08:00:00Z':'2026-07-10T08:00:00Z','Project ID':index%2===0?'p1':'p2','Customer ID':index%2===0?'c1':'c2','Item':'Stone','Payment Status':'Partially Paid','Final Total USD':100}));const payments=loads.flatMap((load,index)=>[{'Payment ID':`payment-${index}-a`,'Target Record ID':load['Record ID'],'Target Type':'load','Payment Date':'2026-09-01','Status':'Active','Amount USD':25},{'Payment ID':`payment-${index}-b`,'Target Record ID':load['Record ID'],'Target Type':'load','Payment Date':'2026-09-02','Status':'Cancelled','Amount USD':10}]);const source:BusinessReportData={...data,loads,payments,projects:[{'Project ID':'p1','Project':'Selected Project','Customer ID':'c1'},{'Project ID':'p2','Project':'Excluded Project','Customer ID':'c2'}]};const started=performance.now();const filtered=filterBusinessReportData(source,{...emptyBusinessReportFilters,fromDate:'2026-08-01',projectId:'p1'});expect(filtered.loads).toHaveLength(loadCount/2);expect(filtered.payments).toHaveLength(loadCount);expect(new Set(filtered.payments.map(row=>row['Payment ID'])).size).toBe(loadCount);expect(filtered.loads.reduce((sum,row)=>sum+Number(row['Final Total USD']),0)).toBe(200000);const bytes=await buildBusinessWorkbookAsync('loads',filtered);expect(unzipSync(bytes)['xl/worksheets/sheet4.xml']).toBeDefined();expect(performance.now()-started).toBeLessThan(10000);});
});
