import{describe,expect,it}from'vitest';
import{buildBusinessWorkbook,sheetsForBusinessReport}from'../src/services/businessWorkbook';
import{strFromU8,unzipSync}from'fflate';
import{emptyBusinessReportFilters,filterBusinessReportData,type BusinessReportData}from'../src/domain/businessReports';

const data:BusinessReportData={generatedAt:'2026-08-13T12:00:00.000Z',companyName:'DROMEX',loads:[{'Record ID':'l1','Final Total USD':111,'Project ID':'p1'}],customers:[],payments:[],openingBalances:[],quarryPurchases:[],suppliers:[],fuelMovements:[{'Movement ID':'f1','Type':'gauge','Status':'Active','Gauge Litres':5000,'Confirmed At':'2026-08-13T08:00:00Z','Balance After Litres':5000,'Correction Difference':200}],equipmentTotals:[],projects:[],dailyReports:[],materials:[]};

describe('business workbooks',()=>{
  it('builds all analysis sheets with a clear overview and filterable frozen headers',()=>{const files=unzipSync(buildBusinessWorkbook('analysis',data)),workbook=strFromU8(files['xl/workbook.xml']!),overview=strFromU8(files['xl/worksheets/sheet1.xml']!),sheet=strFromU8(files['xl/worksheets/sheet2.xml']!);expect((workbook.match(/<sheet /g)??[]).length).toBe(14);expect(workbook).toContain('name="Report Overview"');expect(workbook).toContain('name="Data Dictionary"');expect(overview).toContain('Report title');expect(overview).toContain('Complete Analysis Workbook');expect(sheet).toContain('<autoFilter ref=');expect(sheet).toContain('state="frozen"');});
  it('includes current and latest gauge facts in fuel summary',()=>{const sheets=sheetsForBusinessReport('fuel',data);expect(sheets.map(v=>v.name)).toEqual(['Report Overview','Balance Summary','Movement Details','Equipment Totals','Payment Details']);expect(sheets[1]?.rows).toContainEqual({'Metric':'Latest physical gauge litres','Value':5000});});
  it('filters workbook records and records a readable selected scope',()=>{const source:BusinessReportData={...data,projects:[{'Project ID':'p2','Project':'Harbour Extension'}],loads:[{'Record ID':'l1','Confirmed At':'2026-08-10T08:00:00Z','Project ID':'p1','Customer ID':'c1','Item':'Sand','Payment Status':'Paid'},{'Record ID':'l2','Confirmed At':'2026-08-12T08:00:00Z','Project ID':'p2','Customer ID':'c2','Item':'Stone','Payment Status':'Unpaid'}]};const filtered=filterBusinessReportData(source,{...emptyBusinessReportFilters,fromDate:'2026-08-11',projectId:'p2',paymentStatus:'Unpaid'});expect(filtered.loads.map(row=>row['Record ID'])).toEqual(['l2']);expect(sheetsForBusinessReport('loads',filtered)[0]?.name).toBe('Report Overview');expect(filtered.activeFilters).toContainEqual({'Filter':'Project','Value':'Harbour Extension'});expect(filtered.activeFilters).toContainEqual({'Filter':'Date range','Value':'2026-08-11 to Today'});});
  it('keeps every payment linked to a matching load regardless of payment date',()=>{const source:BusinessReportData={...data,loads:[{'Record ID':'l1','Confirmed At':'2026-08-10T08:00:00Z','Project ID':'p1','Customer ID':'c1','Item':'Sand','Payment Status':'Partially Paid'},{'Record ID':'l2','Confirmed At':'2026-07-01T08:00:00Z','Project ID':'p1','Customer ID':'c1','Item':'Sand','Payment Status':'Paid'}],payments:[{'Payment ID':'pay-late','Target Record ID':'l1','Target Type':'load','Payment Date':'2026-09-01','Status':'Active','Amount USD':40},{'Payment ID':'pay-cancelled','Target Record ID':'l1','Target Type':'load','Payment Date':'2026-09-02','Status':'Cancelled','Amount USD':10},{'Payment ID':'pay-unrelated','Target Record ID':'l2','Target Type':'load','Payment Date':'2026-08-10','Status':'Active','Amount USD':90}]};const filtered=filterBusinessReportData(source,{...emptyBusinessReportFilters,fromDate:'2026-08-01',toDate:'2026-08-31'});expect(filtered.loads.map(row=>row['Record ID'])).toEqual(['l1']);expect(filtered.payments.map(row=>row['Payment ID'])).toEqual(['pay-late','pay-cancelled']);const sheets=sheetsForBusinessReport('loads',filtered);expect(sheets.map(sheet=>sheet.name)).toContain('Payment Details');expect(sheets.find(sheet=>sheet.name==='Payment Details')?.rows).toHaveLength(2);});
  it('includes project operational details in the project workbook',()=>{const sheets=sheetsForBusinessReport('projects',data);expect(sheets.map(sheet=>sheet.name)).toEqual(['Report Overview','Project Summary','Project Loads','Quarry Purchases','Fuel Movements','Payment Details','Daily Report Index','Materials Summary']);});
});
