import {describe,expect,it} from 'vitest';import {applyFuelLedger,buildFuelDashboard,calculateFuelDelivery,calculateFuelFillCost,filterFuelMovements,groupProjectFuelByEquipment,validateGaugeLitres,validatePositiveLitres,type FuelMovement} from '../src/domain/fuel';
const movement=(overrides:Partial<Omit<FuelMovement,'balanceAfterLitres'>>):Omit<FuelMovement,'balanceAfterLitres'>=>({id:'x',type:'delivery',confirmedAt:'2026-01-01T00:00:00Z',litres:0,previousBalanceLitres:null,differenceLitres:null,supplierId:null,supplierName:null,equipmentId:null,equipmentName:null,projectId:null,projectName:null,ticketNumber:null,odometerReading:null,reason:null,notes:null,fuelPriceHistoryId:null,pricePerLitreUsd:null,priceOverrideReason:null,consumptionCostUsd:null,subtotalUsd:null,vatRatePercent:null,vatAmountUsd:null,finalTotalUsd:null,paymentStatus:'Unpriced',status:'Active',cancellationReason:null,cancelledAt:null,...overrides});
describe('fuel ledger',()=>{it('uses gauge as baseline and applies active movements',()=>{const result=applyFuelLedger([movement({id:'g',type:'gauge',litres:1000}),movement({id:'d',confirmedAt:'2026-01-02T00:00:00Z',litres:250}),movement({id:'f',type:'fill',confirmedAt:'2026-01-03T00:00:00Z',litres:400})]);expect(result.at(-1)?.balanceAfterLitres).toBe(850);});it('excludes cancelled movements',()=>{const result=applyFuelLedger([movement({type:'gauge',litres:500}),movement({type:'fill',litres:100,confirmedAt:'2026-01-02T00:00:00Z',status:'Cancelled'})]);expect(result.at(-1)?.balanceAfterLitres).toBe(500);});it('allows a negative calculated balance',()=>{const result=applyFuelLedger([movement({type:'gauge',litres:50}),movement({type:'fill',litres:75,confirmedAt:'2026-01-02T00:00:00Z'})]);expect(result.at(-1)?.balanceAfterLitres).toBe(-25);});it('calculates delivery VAT and validates quantities',()=>{expect(calculateFuelDelivery(100, '1.25', 11)).toEqual({pricePerLitreUsd:1.25,subtotalUsd:125,vatAmountUsd:13.75,finalTotalUsd:138.75});expect(()=>validatePositiveLitres('0')).toThrow();expect(validateGaugeLitres('0')).toBe(0);});it('rejects scientific notation and malformed litre values',()=>{expect(()=>validatePositiveLitres('1e3')).toThrow();expect(()=>validatePositiveLitres('.5')).toThrow();expect(()=>validateGaugeLitres('Infinity')).toThrow();});});

describe('fuel boundary behavior',()=>{
  it.each(['',' ','-1','0','0.000','1e3','.5','Infinity','NaN'])('rejects invalid positive litre input %j',(value)=>expect(()=>validatePositiveLitres(value)).toThrow());
  it.each(['-1','1e3','.5','Infinity','NaN'])('rejects invalid gauge input %j',(value)=>expect(()=>validateGaugeLitres(value)).toThrow());
  it('records the prior calculated balance and gauge difference',()=>{const result=applyFuelLedger([movement({id:'d',litres:100}),movement({id:'g',type:'gauge',confirmedAt:'2026-01-02T00:00:00Z',litres:80})]);expect(result.at(-1)).toMatchObject({previousBalanceLitres:100,differenceLitres:-20,balanceAfterLitres:80});});
  it('sorts out-of-order movements chronologically before calculating',()=>{const result=applyFuelLedger([movement({id:'fill',type:'fill',confirmedAt:'2026-01-03T00:00:00Z',litres:10}),movement({id:'gauge',type:'gauge',confirmedAt:'2026-01-01T00:00:00Z',litres:50}),movement({id:'delivery',confirmedAt:'2026-01-02T00:00:00Z',litres:20})]);expect(result.map(value=>value.id)).toEqual(['gauge','delivery','fill']);expect(result.at(-1)?.balanceAfterLitres).toBe(60);});
});

describe('project equipment fuel usage',()=>{
  it('filters one project, excludes cancelled fills, and groups newest fills by equipment',()=>{const movements=applyFuelLedger([movement({id:'a1',type:'fill',projectId:'project-a',equipmentId:'loader',equipmentName:'Loader 01',litres:80,confirmedAt:'2026-08-20T08:00:00Z'}),movement({id:'b1',type:'fill',projectId:'project-b',equipmentId:'loader',equipmentName:'Loader 01',litres:500,confirmedAt:'2026-08-20T09:00:00Z'}),movement({id:'a2',type:'fill',projectId:'project-a',equipmentId:'loader',equipmentName:'Loader 01',litres:45,confirmedAt:'2026-08-21T08:00:00Z'}),movement({id:'a3',type:'fill',projectId:'project-a',equipmentId:'roller',equipmentName:'Roller 02',litres:30,confirmedAt:'2026-08-21T09:00:00Z'}),movement({id:'cancelled',type:'fill',projectId:'project-a',equipmentId:'roller',equipmentName:'Roller 02',litres:999,status:'Cancelled',confirmedAt:'2026-08-22T09:00:00Z'})]);const result=groupProjectFuelByEquipment(movements,'project-a');expect(result.map(value=>[value.equipmentName,value.totalLitres,value.fillCount])).toEqual([['Loader 01',125,2],['Roller 02',30,1]]);expect(result[0]?.fills.map(value=>value.id)).toEqual(['a2','a1']);});
});

describe('general fuel history filters',()=>{
  const records=applyFuelLedger([movement({id:'delivery',type:'delivery',litres:500,confirmedAt:'2026-08-18T08:00:00Z'}),movement({id:'loader-a',type:'fill',projectId:'project-a',equipmentId:'loader',equipmentName:'Loader',litres:60,confirmedAt:'2026-08-20T08:00:00Z'}),movement({id:'roller-a',type:'fill',projectId:'project-a',equipmentId:'roller',equipmentName:'Roller',litres:30,status:'Cancelled',confirmedAt:'2026-08-21T08:00:00Z'}),movement({id:'loader-b',type:'fill',projectId:'project-b',equipmentId:'loader',equipmentName:'Loader',litres:40,confirmedAt:'2026-08-22T08:00:00Z'})]);
  it('combines project, equipment, type, status, and inclusive dates',()=>expect(filterFuelMovements(records,{projectId:'project-a',equipmentId:'loader',type:'fill',status:'Active',fromDate:'2026-08-20',toDate:'2026-08-20'}).map(value=>value.id)).toEqual(['loader-a']));
  it('can show cancelled records independently',()=>expect(filterFuelMovements(records,{status:'Cancelled'}).map(value=>value.id)).toEqual(['roller-a']));
});

describe('fuel costing and dashboard',()=>{
  it('snapshots a fill price into a rounded transaction cost',()=>expect(calculateFuelFillCost(40,'0.90')).toEqual({pricePerLitreUsd:.9,consumptionCostUsd:36}));
  it('separates purchase spend, consumption cost, and unpriced litres',()=>{const dashboard=buildFuelDashboard(applyFuelLedger([movement({id:'purchase',type:'delivery',confirmedAt:'2026-08-29T08:00:00',litres:1000,finalTotalUsd:950}),movement({id:'priced',type:'fill',confirmedAt:'2026-08-29T09:00:00',litres:40,projectId:'p',projectName:'Road',equipmentId:'e',equipmentName:'Excavator',pricePerLitreUsd:.9,consumptionCostUsd:36}),movement({id:'unpriced',type:'fill',confirmedAt:'2026-08-29T10:00:00',litres:10,projectId:'p',projectName:'Road',equipmentId:'e',equipmentName:'Excavator'})]),new Date(2026,7,29,12));expect(dashboard.today).toMatchObject({purchasedLitres:1000,purchaseCostUsd:950,consumedLitres:50,consumptionCostUsd:36,unpricedFillLitres:10});expect(dashboard.projects[0]).toMatchObject({name:'Road',litres:50,costUsd:36,unpricedLitres:10});});
});
