import {describe,expect,it} from 'vitest';import {applyFuelLedger,calculateFuelDelivery,validateGaugeLitres,validatePositiveLitres,type FuelMovement} from '../src/domain/fuel';
const movement=(overrides:Partial<Omit<FuelMovement,'balanceAfterLitres'>>):Omit<FuelMovement,'balanceAfterLitres'>=>({id:'x',type:'delivery',confirmedAt:'2026-01-01T00:00:00Z',litres:0,previousBalanceLitres:null,differenceLitres:null,supplierId:null,supplierName:null,equipmentId:null,equipmentName:null,projectId:null,projectName:null,ticketNumber:null,odometerReading:null,reason:null,notes:null,pricePerLitreUsd:null,subtotalUsd:null,vatRatePercent:null,vatAmountUsd:null,finalTotalUsd:null,paymentStatus:'Unpriced',status:'Active',cancellationReason:null,cancelledAt:null,...overrides});
describe('fuel ledger',()=>{it('uses gauge as baseline and applies active movements',()=>{const result=applyFuelLedger([movement({id:'g',type:'gauge',litres:1000}),movement({id:'d',confirmedAt:'2026-01-02T00:00:00Z',litres:250}),movement({id:'f',type:'fill',confirmedAt:'2026-01-03T00:00:00Z',litres:400})]);expect(result.at(-1)?.balanceAfterLitres).toBe(850);});it('excludes cancelled movements',()=>{const result=applyFuelLedger([movement({type:'gauge',litres:500}),movement({type:'fill',litres:100,confirmedAt:'2026-01-02T00:00:00Z',status:'Cancelled'})]);expect(result.at(-1)?.balanceAfterLitres).toBe(500);});it('allows a negative calculated balance',()=>{const result=applyFuelLedger([movement({type:'gauge',litres:50}),movement({type:'fill',litres:75,confirmedAt:'2026-01-02T00:00:00Z'})]);expect(result.at(-1)?.balanceAfterLitres).toBe(-25);});it('calculates delivery VAT and validates quantities',()=>{expect(calculateFuelDelivery(100, '1.25', 11)).toEqual({pricePerLitreUsd:1.25,subtotalUsd:125,vatAmountUsd:13.75,finalTotalUsd:138.75});expect(()=>validatePositiveLitres('0')).toThrow();expect(validateGaugeLitres('0')).toBe(0);});it('rejects scientific notation and malformed litre values',()=>{expect(()=>validatePositiveLitres('1e3')).toThrow();expect(()=>validatePositiveLitres('.5')).toThrow();expect(()=>validateGaugeLitres('Infinity')).toThrow();});});

describe('fuel boundary behavior',()=>{
  it.each(['',' ','-1','0','0.000','1e3','.5','Infinity','NaN'])('rejects invalid positive litre input %j',(value)=>expect(()=>validatePositiveLitres(value)).toThrow());
  it.each(['-1','1e3','.5','Infinity','NaN'])('rejects invalid gauge input %j',(value)=>expect(()=>validateGaugeLitres(value)).toThrow());
  it('records the prior calculated balance and gauge difference',()=>{const result=applyFuelLedger([movement({id:'d',litres:100}),movement({id:'g',type:'gauge',confirmedAt:'2026-01-02T00:00:00Z',litres:80})]);expect(result.at(-1)).toMatchObject({previousBalanceLitres:100,differenceLitres:-20,balanceAfterLitres:80});});
  it('sorts out-of-order movements chronologically before calculating',()=>{const result=applyFuelLedger([movement({id:'fill',type:'fill',confirmedAt:'2026-01-03T00:00:00Z',litres:10}),movement({id:'gauge',type:'gauge',confirmedAt:'2026-01-01T00:00:00Z',litres:50}),movement({id:'delivery',confirmedAt:'2026-01-02T00:00:00Z',litres:20})]);expect(result.map(value=>value.id)).toEqual(['gauge','delivery','fill']);expect(result.at(-1)?.balanceAfterLitres).toBe(60);});
});
