import {DatabaseSync} from 'node:sqlite';
import {afterEach,describe,expect,it} from 'vitest';
import {migrateDatabase} from '../src/data/database/migrations';
import {SqlitePavementRepository} from '../src/data/repositories/SqlitePavementRepository';
import {appliedEmulsionLitres,averageThickness,calculatePavement,circleArea,coatLitres,compactedVolume,coverageArea,crossfallDifferenceMm,gradeElevationDifferenceM,looseThickness,looseVolume,massFromVolume,pavementSpreadRates,progressPercent,quantityVarianceTonnes,slopedSurfaceWidth,triangleArea,truckLoads,variableWidthArea} from '../src/domain/pavement';

class TestDatabase{readonly raw=new DatabaseSync(':memory:');execAsync(sql:string){this.raw.exec(sql);return Promise.resolve();}getFirstAsync<T>(sql:string,...params:unknown[]){return Promise.resolve((this.raw.prepare(sql).get(...params as never[])??null)as T|null);}getAllAsync<T>(sql:string,...params:unknown[]){return Promise.resolve(this.raw.prepare(sql).all(...params as never[])as T[]);}runAsync(sql:string,...params:unknown[]){const result=this.raw.prepare(sql).run(...params as never[]);return Promise.resolve({changes:Number(result.changes),lastInsertRowId:Number(result.lastInsertRowid)});}async withTransactionAsync(action:()=>Promise<void>){this.raw.exec('BEGIN');try{await action();this.raw.exec('COMMIT');}catch(cause){this.raw.exec('ROLLBACK');throw cause;}}close(){this.raw.close();}}

describe('asphalt pavement calculator',()=>{const databases:TestDatabase[]=[];afterEach(()=>databases.splice(0).forEach(value=>value.close()));
  it('converts 90 kg/m² to 37.5 mm finished and 45 mm loose with a project factor of 1.20',()=>{const result=calculatePavement(3500,90,2.4,5);expect(result.thicknessMm).toBe(37.5);expect(looseThickness(result.thicknessMm,1.2)).toBe(45);expect(result.theoreticalKg).toBe(315000);expect(result.plannedKg).toBe(330750);expect(pavementSpreadRates).toContain(90);});
  it('calculates variable geometry and common shapes',()=>{expect(variableWidthArea(100,6,8)).toBe(700);expect(triangleArea(10,4)).toBe(20);expect(circleArea(2)).toBeCloseTo(12.566,3);});
  it('calculates layer volumes, masses, loose volume, and reverse coverage',()=>{const volume=compactedVolume(3500,200);expect(volume).toBe(700);expect(massFromVolume(volume,2.1)).toBe(1470);expect(looseVolume(volume,1.2)).toBe(840);expect(coverageArea(420,120)).toBe(3500);expect(averageThickness(420,3500,2.4)).toBe(50);});
  it('calculates coats, milling, slopes, truck loads, progress, and variance',()=>{expect(coatLitres(3500,.3)).toBe(1050);expect(appliedEmulsionLitres(1050,.6)).toBe(1750);expect(compactedVolume(3500,50)).toBe(175);expect(crossfallDifferenceMm(3.5,2.5)).toBeCloseTo(87.5,6);expect(gradeElevationDifferenceM(500,1)).toBe(5);expect(slopedSurfaceWidth(7,2.5)).toBeCloseTo(7.002,3);expect(truckLoads(441,20)).toBe(23);expect(progressPercent(220.5,441)).toBe(50);expect(quantityVarianceTonnes(450,441)).toBe(9);});
  it('saves compacted and before-compaction thickness beneath its active project',async()=>{const db=new TestDatabase();databases.push(db);await migrateDatabase(db as never);db.raw.prepare(`INSERT INTO customers (id,customer_type,name,is_own_company,is_active,created_at,updated_at) VALUES ('c','company','Road Co',0,1,'2026-08-22','2026-08-22')`).run();db.raw.prepare(`INSERT INTO projects (id,customer_id,name,location,status,created_at,updated_at,is_archived) VALUES ('p','c','Coastal Road','Beirut','active','2026-08-22','2026-08-22',0)`).run();const repository=new SqlitePavementRepository(db as never);const saved=await repository.saveCalculation({projectId:'p',name:'Wearing course',lengthM:500,widthM:7,areaM2:3500,spreadRateKgM2:120,densityTM3:2.4,looseThicknessFactor:1.2,allowancePercent:5,notes:''});expect(saved).toMatchObject({projectName:'Coastal Road',areaM2:3500,spreadRateKgM2:120,thicknessMm:50,looseThicknessFactor:1.2,looseThicknessMm:60,theoreticalKg:420000,plannedKg:441000});expect(await repository.listCalculations('p')).toHaveLength(1);expect(Number((db.raw.prepare(`SELECT COUNT(*) count FROM sync_outbox WHERE entity_type='pavementCalculation'`).get()as{count:number}).count)).toBe(1);});
});
