import {DatabaseSync} from 'node:sqlite';
import {afterEach,describe,expect,it} from 'vitest';
import {migrateDatabase} from '../src/data/database/migrations';
import {SqliteWallRepository} from '../src/data/repositories/SqliteWallRepository';
import {calculateRebar,calculateWallVolume,rebarUnitWeightKgM} from '../src/domain/walls';

class TestDatabase{readonly raw=new DatabaseSync(':memory:');execAsync(sql:string){this.raw.exec(sql);return Promise.resolve();}getFirstAsync<T>(sql:string,...params:unknown[]){return Promise.resolve((this.raw.prepare(sql).get(...params as never[])??null)as T|null);}getAllAsync<T>(sql:string,...params:unknown[]){return Promise.resolve(this.raw.prepare(sql).all(...params as never[])as T[]);}runAsync(sql:string,...params:unknown[]){const result=this.raw.prepare(sql).run(...params as never[]);return Promise.resolve({changes:Number(result.changes),lastInsertRowId:Number(result.lastInsertRowid)});}async withTransactionAsync(action:()=>Promise<void>){this.raw.exec('BEGIN');try{await action();this.raw.exec('COMMIT');}catch(cause){this.raw.exec('ROLLBACK');throw cause;}}close(){this.raw.close();}}

describe('wall construction and consumption',()=>{const databases:TestDatabase[]=[];afterEach(()=>databases.splice(0).forEach(value=>value.close()));
  it('calculates a tapered wall volume and allowance',()=>{const result=calculateWallVolume(20,4,.8,.4,2,5);expect(result.grossVolumeM3).toBeCloseTo(48,8);expect(result.netVolumeM3).toBeCloseTo(46,8);expect(result.plannedVolumeM3).toBeCloseTo(48.3,8);});
  it('calculates rebar length and steel weight from diameter',()=>{const result=calculateRebar(16,40,12);expect(result.totalLengthM).toBe(480);expect(rebarUnitWeightKgM(16)).toBeCloseTo(1.578,3);expect(result.totalKg).toBeCloseTo(757.65,1);});
  it('saves one project wall and distinct concrete, site-mix, rebar, and stone use',async()=>{const db=new TestDatabase();databases.push(db);await migrateDatabase(db as never);db.raw.prepare(`INSERT INTO customers (id,customer_type,name,is_own_company,is_active,created_at,updated_at) VALUES ('c','company','Road Co',0,1,'2026-08-22','2026-08-22')`).run();db.raw.prepare(`INSERT INTO projects (id,customer_id,name,location,status,created_at,updated_at,is_archived) VALUES ('p','c','Mountain Road','Beirut','active','2026-08-22','2026-08-22',0)`).run();const repository=new SqliteWallRepository(db as never);const wall=await repository.saveWall({projectId:'p',name:'Retaining wall A',system:'reinforced_concrete',purpose:'retaining',lengthM:20,heightM:4,bottomThicknessM:.8,topThicknessM:.4,deductionM3:2,allowancePercent:5,notes:''});expect(wall).toMatchObject({projectName:'Mountain Road',netVolumeM3:46,plannedVolumeM3:48.3});const base={wallId:wall.id,usedOn:'2026-08-22',concretePurpose:null,finishedVolumeM3:null,cementBags:null,cementBagKg:null,sandQuantity:null,sandUnit:null,gravelQuantity:null,gravelUnit:null,waterLitres:null,admixtureQuantity:null,admixtureUnit:null,stoneQuantity:null,stoneUnit:null,rebarDiameterMm:null,rebarCount:null,rebarLengthEachM:null,rebarGrade:'',notes:''} as const;await repository.addConsumption({...base,type:'ready_mix',concretePurpose:'structural',finishedVolumeM3:12});await repository.addConsumption({...base,type:'site_mix',concretePurpose:'filling',finishedVolumeM3:3,cementBags:30,cementBagKg:50,sandQuantity:2,sandUnit:'m3',gravelQuantity:3,gravelUnit:'m3',waterLitres:600});const steel=await repository.addConsumption({...base,type:'rebar',rebarDiameterMm:16,rebarCount:40,rebarLengthEachM:12});await repository.addConsumption({...base,type:'stone',stoneQuantity:9,stoneUnit:'m3'});expect(steel.totalRebarKg).toBeCloseTo(757.65,1);const detail=await repository.getWall(wall.id);expect(detail.entries).toHaveLength(4);expect(detail.entries.map(value=>value.type).sort()).toEqual(['ready_mix','rebar','site_mix','stone']);expect(Number((db.raw.prepare(`SELECT COUNT(*) count FROM sync_outbox WHERE entity_type IN ('wall','wallConsumption')`).get()as{count:number}).count)).toBe(5);});
});
