import type {ReactNode} from 'react';
import {ActivityIndicator,ScrollView,StyleSheet,Text,TextInput,TouchableOpacity,View,type KeyboardTypeOptions,type TextInputProps} from 'react-native';
import {colors,radius,spacing,typography} from '../theme';

export function AppPage({children,keyboard=false}:{children:ReactNode;keyboard?:boolean}){return <ScrollView contentContainerStyle={styles.page} keyboardShouldPersistTaps={keyboard?'handled':'never'}>{children}</ScrollView>;}
export function PageHeader({eyebrow,title,onBack}:{eyebrow:string;title:string;onBack:()=>void}){return <View style={styles.header}><TouchableOpacity style={styles.back} onPress={onBack} accessibilityRole="button"><Text style={styles.backText}>Back</Text></TouchableOpacity><View style={styles.flex}><Text style={styles.eyebrow}>{eyebrow}</Text><Text style={styles.title}>{title}</Text></View></View>;}
export function AppCard({title,hint,children,tone='white'}:{title?:string;hint?:string;children:ReactNode;tone?:'white'|'cream'|'navy'|'orange'}){const dark=tone==='navy'||tone==='orange';return <View style={[styles.card,tone==='cream'&&styles.cream,tone==='navy'&&styles.navy,tone==='orange'&&styles.orange]}>{title?<Text style={[styles.cardTitle,dark&&styles.light]}>{title}</Text>:null}{hint?<Text style={[styles.helper,dark&&styles.lightHelper]}>{hint}</Text>:null}{children}</View>;}
export function AppButton({label,onPress,tone='primary',disabled=false,busy=false,hint}:{label:string;onPress:()=>void;tone?:'primary'|'navy'|'secondary'|'danger';disabled?:boolean;busy?:boolean;hint?:string}){const solid=tone==='primary'||tone==='navy';return <TouchableOpacity disabled={disabled||busy} onPress={onPress} accessibilityRole="button" style={[styles.button,tone==='primary'&&styles.primary,tone==='navy'&&styles.navyButton,tone==='secondary'&&styles.secondary,tone==='danger'&&styles.dangerButton,(disabled||busy)&&styles.disabled]}>{busy?<ActivityIndicator color={solid?'#FFF':colors.brand}/>:<><Text style={[styles.buttonText,solid&&styles.buttonTextLight,tone==='danger'&&styles.dangerText]}>{label}</Text>{hint?<Text style={[styles.buttonHint,solid&&styles.buttonHintLight]}>{hint}</Text>:null}</>}</TouchableOpacity>;}
export function AppField({label,multiline,keyboardType,...props}:{label:string;multiline?:boolean;keyboardType?:KeyboardTypeOptions}&TextInputProps){return <View style={styles.field}><Text style={styles.label}>{label}</Text><TextInput {...props} multiline={multiline} keyboardType={keyboardType} placeholderTextColor="#89939B" style={[styles.input,multiline&&styles.multiline]}/></View>;}
export function MetricCard({label,value,accent=false}:{label:string;value:string;accent?:boolean}){return <View style={[styles.metric,accent&&styles.metricAccent]}><Text style={[styles.metricValue,accent&&styles.light]}>{value}</Text><Text style={[styles.metricLabel,accent&&styles.lightHelper]}>{label}</Text></View>;}
export function Feedback({kind,children}:{kind:'error'|'success'|'warning';children:ReactNode}){return <Text style={[styles.feedback,kind==='error'?styles.error:kind==='success'?styles.success:styles.warning]}>{children}</Text>;}
export function EmptyState({title,body}:{title:string;body:string}){return <View style={styles.empty}><Text style={styles.cardTitle}>{title}</Text><Text style={styles.helper}>{body}</Text></View>;}

const styles=StyleSheet.create({page:{padding:spacing.xl,paddingBottom:42,gap:spacing.lg},header:{flexDirection:'row',alignItems:'center',gap:14},back:{backgroundColor:colors.surface,padding:10,borderRadius:radius.sm,minHeight:42,justifyContent:'center'},backText:{color:colors.ink,fontWeight:'800'},flex:{flex:1,minWidth:0},eyebrow:{color:colors.brand,...typography.eyebrow},title:{color:colors.ink,...typography.pageTitle},card:{backgroundColor:colors.surface,borderRadius:radius.lg,padding:17,gap:spacing.md},cream:{backgroundColor:colors.cream,borderWidth:1,borderColor:'#E8DED0'},navy:{backgroundColor:colors.navy},orange:{backgroundColor:colors.brand},cardTitle:{color:colors.ink,...typography.cardTitle},helper:{color:colors.muted,...typography.helper},light:{color:colors.cream},lightHelper:{color:'#E8E2D7'},button:{minHeight:48,borderRadius:radius.md,paddingHorizontal:16,paddingVertical:13,alignItems:'center',justifyContent:'center',gap:3},primary:{backgroundColor:colors.brand},navyButton:{backgroundColor:colors.navy},secondary:{borderWidth:1,borderColor:colors.navy,backgroundColor:colors.surface},dangerButton:{borderWidth:1,borderColor:colors.danger,backgroundColor:colors.surface},disabled:{opacity:.4},buttonText:{color:colors.navy,fontWeight:'900',fontSize:15},buttonTextLight:{color:'#FFF'},dangerText:{color:colors.danger},buttonHint:{color:colors.muted,fontSize:11,textAlign:'center'},buttonHintLight:{color:'#F4E8E1'},field:{gap:6},label:{color:colors.ink,fontSize:13,fontWeight:'800'},input:{minHeight:46,borderWidth:1,borderColor:colors.line,borderRadius:11,paddingHorizontal:13,paddingVertical:11,color:colors.ink,backgroundColor:'#FCFBF8',fontSize:15},multiline:{minHeight:78,textAlignVertical:'top'},metric:{flex:1,minWidth:130,backgroundColor:colors.surface,borderRadius:radius.md,padding:15,gap:3},metricAccent:{backgroundColor:colors.navy},metricValue:{color:colors.ink,fontSize:26,fontWeight:'900'},metricLabel:{color:colors.muted,fontSize:11,fontWeight:'800'},feedback:{padding:12,borderRadius:radius.sm,fontWeight:'700',lineHeight:18},error:{color:colors.danger,backgroundColor:'#FCE8E6'},success:{color:colors.success,backgroundColor:'#E5F3EC'},warning:{color:colors.warning,backgroundColor:'#FFF3D8'},empty:{borderWidth:1,borderColor:colors.line,borderStyle:'dashed',borderRadius:radius.lg,padding:16,gap:5}});
