import {Modal,Pressable,ScrollView,StyleSheet,Text,TouchableOpacity,View} from 'react-native';
import type {Project} from '../../domain/loads';
import {colors} from '../theme';

export type CreateAction='receipt'|'dailyReport'|'waste'|'quarry'|'fuelDelivery'|'equipmentFill'|'quickText'|'schedule'|'issue'|'photo';
const actions:{id:CreateAction;number:string;title:string;hint:string;tone:'orange'|'navy'|'cream'}[]=[
  {id:'receipt',number:'01',title:'Make Receipt',hint:'Create an outgoing load and its documents.',tone:'orange'},
  {id:'dailyReport',number:'02',title:'Daily Report',hint:'Record today’s work, people, materials, and photos.',tone:'navy'},
  {id:'schedule',number:'03',title:'Scheduled Work',hint:'Add planned work under a project.',tone:'cream'},
  {id:'waste',number:'04',title:'Waste Dump',hint:'Use driver counters or record a one-off dump.',tone:'navy'},
  {id:'quarry',number:'05',title:'Quarry Purchase',hint:'Record incoming material and supplier cost.',tone:'cream'},
  {id:'fuelDelivery',number:'06',title:'Fuel Delivery',hint:'Record fuel arriving into the tank.',tone:'navy'},
  {id:'equipmentFill',number:'07',title:'Equipment Fill',hint:'Record fuel issued to equipment and a project.',tone:'cream'},
  {id:'quickText',number:'08',title:'Quick Text',hint:'Create a printable company document.',tone:'navy'},
  {id:'issue',number:'09',title:'Project Issue',hint:'Capture a blocker, problem, or follow-up.',tone:'cream'},
  {id:'photo',number:'10',title:'Site Photo',hint:'Add a photo directly to the active project.',tone:'navy'},
];

export function CreateActionSheet({visible,activeProject,onClose,onSelect,onChooseProject}:{visible:boolean;activeProject:Project|null;onClose:()=>void;onSelect:(action:CreateAction)=>void;onChooseProject:()=>void}){
  return <Modal visible={visible} transparent animationType="fade" onRequestClose={onClose}><View style={styles.overlay}><Pressable style={StyleSheet.absoluteFill} onPress={onClose}/><View style={styles.sheet}><View style={styles.handle}/><View style={styles.header}><View style={styles.flex}><Text style={styles.eyebrow}>CREATE</Text><Text style={styles.title}>What are you recording?</Text><Text style={styles.hint}>Choose one clear field action. DROMEX keeps the same project context where applicable.</Text></View><TouchableOpacity style={styles.close} onPress={onClose}><Text style={styles.closeText}>×</Text></TouchableOpacity></View><TouchableOpacity style={[styles.context,!activeProject&&styles.contextEmpty]} onPress={onChooseProject}><View style={styles.flex}><Text style={styles.contextLabel}>{activeProject?'ACTIVE PROJECT':'PROJECT CONTEXT'}</Text><Text style={styles.contextName}>{activeProject?.name??'Choose a project'}</Text><Text style={styles.contextHint}>{activeProject?`${activeProject.customerName} · ${activeProject.location}`:'Optional now; required actions will ask before saving.'}</Text></View><Text style={styles.change}>{activeProject?'Change':'Choose'} ›</Text></TouchableOpacity><ScrollView contentContainerStyle={styles.actions} showsVerticalScrollIndicator={false}>{actions.map(action=><TouchableOpacity key={action.id} activeOpacity={.7} style={[styles.action,action.tone==='orange'?styles.actionOrange:action.tone==='navy'?styles.actionNavy:styles.actionCream]} onPress={()=>onSelect(action.id)}><Text style={[styles.number,action.tone==='navy'&&styles.light]}>{action.number}</Text><View style={styles.flex}><Text style={[styles.actionTitle,action.tone==='navy'&&styles.light]}>{action.title}</Text><Text style={[styles.actionHint,action.tone==='navy'&&styles.lightHint]}>{action.hint}</Text></View><Text style={[styles.arrow,action.tone==='navy'&&styles.light]}>›</Text></TouchableOpacity>)}</ScrollView></View></View></Modal>;
}

const styles=StyleSheet.create({overlay:{flex:1,backgroundColor:'rgba(8,27,45,.55)',justifyContent:'flex-end'},sheet:{maxHeight:'91%',backgroundColor:colors.background,borderTopLeftRadius:26,borderTopRightRadius:26,padding:18,paddingBottom:28,gap:13},handle:{width:48,height:5,borderRadius:3,backgroundColor:'#C6BFB4',alignSelf:'center'},header:{flexDirection:'row',alignItems:'flex-start',gap:12},flex:{flex:1,minWidth:0},eyebrow:{color:colors.brand,fontSize:10,fontWeight:'900',letterSpacing:1.4},title:{color:colors.ink,fontSize:24,fontWeight:'900',marginTop:2},hint:{color:colors.muted,fontSize:11,lineHeight:16,marginTop:4},close:{width:42,height:42,borderRadius:13,backgroundColor:colors.surface,alignItems:'center',justifyContent:'center'},closeText:{color:colors.navy,fontSize:28,fontWeight:'700'},context:{backgroundColor:colors.navy,borderRadius:15,padding:14,flexDirection:'row',alignItems:'center',gap:10},contextEmpty:{backgroundColor:colors.brand},contextLabel:{color:'#F2A184',fontSize:8,fontWeight:'900',letterSpacing:1},contextName:{color:'#FFF8ED',fontSize:16,fontWeight:'900',marginTop:2},contextHint:{color:'#D5E4EF',fontSize:10,marginTop:2},change:{color:'#FFF',fontSize:11,fontWeight:'900'},actions:{gap:8,paddingBottom:4},action:{minHeight:68,borderRadius:14,padding:13,flexDirection:'row',alignItems:'center',gap:10},actionOrange:{backgroundColor:colors.brand},actionNavy:{backgroundColor:colors.navy},actionCream:{backgroundColor:colors.cream,borderWidth:1,borderColor:'#E4D7C7'},number:{width:27,color:colors.navy,fontSize:9,fontWeight:'900'},actionTitle:{color:colors.ink,fontSize:15,fontWeight:'900'},actionHint:{color:colors.muted,fontSize:10,lineHeight:14,marginTop:2},arrow:{color:colors.brand,fontSize:25,fontWeight:'900'},light:{color:'#FFF8ED'},lightHint:{color:'#D5E4EF'}});
