import {useEffect,useMemo,useState} from 'react';
import {Modal,SafeAreaView,StyleSheet,Text,TouchableOpacity,View} from 'react-native';
import {colors} from '../theme';

const iso=(date:Date)=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;
const parse=(value:string)=>{const match=/^(\d{4})-(\d{2})-(\d{2})$/.exec(value);if(!match)return null;const date=new Date(Number(match[1]),Number(match[2])-1,Number(match[3]));return iso(date)===value?date:null;};
export const todayIso=()=>iso(new Date());
export const displayDate=(value:string)=>{const date=parse(value);return date?date.toLocaleDateString(undefined,{day:'numeric',month:'short',year:'numeric'}):'';};

export function DatePickerField({label,value,onChange,placeholder='Select date',allowClear=false,minDate,maxDate}:{label:string;value:string;onChange:(value:string)=>void;placeholder?:string;allowClear?:boolean;minDate?:string;maxDate?:string}){
  const[open,setOpen]=useState(false);const[month,setMonth]=useState(()=>{const selected=parse(value)??new Date();return new Date(selected.getFullYear(),selected.getMonth(),1);});
  useEffect(()=>{if(open){const selected=parse(value)??new Date();setMonth(new Date(selected.getFullYear(),selected.getMonth(),1));}},[open,value]);
  const cells=useMemo(()=>{const first=month.getDay(),count=new Date(month.getFullYear(),month.getMonth()+1,0).getDate();return [...Array(first).fill(null),...Array.from({length:count},(_,index)=>index+1)];},[month]);
  const monthLabel=month.toLocaleDateString(undefined,{month:'long',year:'numeric'});const selected=parse(value);const today=todayIso();
  function choose(day:number){const next=iso(new Date(month.getFullYear(),month.getMonth(),day));if((minDate&&next<minDate)||(maxDate&&next>maxDate))return;onChange(next);setOpen(false);}
  return <View style={styles.field}><Text style={styles.label}>{label}</Text><TouchableOpacity style={styles.control} onPress={()=>setOpen(true)} accessibilityRole="button"><Text style={[styles.value,!value&&styles.placeholder]}>{value?displayDate(value):placeholder}</Text><Text style={styles.calendar}>▦</Text></TouchableOpacity><Modal visible={open} animationType="slide" presentationStyle="pageSheet" onRequestClose={()=>setOpen(false)}><SafeAreaView style={styles.modal}><View style={styles.modalHeader}><View><Text style={styles.eyebrow}>CHOOSE A DATE</Text><Text style={styles.title}>{label.replace(' *','')}</Text></View><TouchableOpacity style={styles.close} onPress={()=>setOpen(false)}><Text style={styles.closeText}>Close</Text></TouchableOpacity></View><View style={styles.calendarCard}><View style={styles.monthRow}><TouchableOpacity style={styles.monthButton} onPress={()=>setMonth(new Date(month.getFullYear(),month.getMonth()-1,1))}><Text style={styles.monthButtonText}>‹</Text></TouchableOpacity><Text style={styles.monthLabel}>{monthLabel}</Text><TouchableOpacity style={styles.monthButton} onPress={()=>setMonth(new Date(month.getFullYear(),month.getMonth()+1,1))}><Text style={styles.monthButtonText}>›</Text></TouchableOpacity></View><View style={styles.week}>{['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(day=><Text key={day} style={styles.weekDay}>{day}</Text>)}</View><View style={styles.days}>{cells.map((day,index)=>{if(day==null)return <View key={`blank-${index}`} style={styles.day}/>;const key=iso(new Date(month.getFullYear(),month.getMonth(),day));const disabled=!!((minDate&&key<minDate)||(maxDate&&key>maxDate));const active=selected&&key===value;return <TouchableOpacity key={key} style={[styles.day,active&&styles.dayActive]} disabled={disabled} onPress={()=>choose(day)}><Text style={[styles.dayText,key===today&&styles.today,active&&styles.dayTextActive,disabled&&styles.disabled]}>{day}</Text></TouchableOpacity>;})}</View><View style={styles.quickRow}><TouchableOpacity style={styles.quick} disabled={!!((minDate&&today<minDate)||(maxDate&&today>maxDate))} onPress={()=>{onChange(today);setOpen(false);}}><Text style={styles.quickText}>Today</Text></TouchableOpacity>{allowClear?<TouchableOpacity style={styles.quick} onPress={()=>{onChange('');setOpen(false);}}><Text style={styles.quickText}>Clear date</Text></TouchableOpacity>:null}</View></View></SafeAreaView></Modal></View>;
}

const styles=StyleSheet.create({field:{gap:6},label:{color:colors.ink,fontSize:13,fontWeight:'800'},control:{minHeight:49,borderWidth:1,borderColor:colors.line,borderRadius:11,paddingHorizontal:13,paddingVertical:11,backgroundColor:'#FCFBF8',flexDirection:'row',alignItems:'center',justifyContent:'space-between'},value:{color:colors.ink,fontSize:15,fontWeight:'700'},placeholder:{color:colors.muted,fontWeight:'500'},calendar:{color:colors.brandDark,fontSize:22,fontWeight:'900'},modal:{flex:1,backgroundColor:colors.background},modalHeader:{padding:20,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},eyebrow:{color:colors.brand,fontSize:10,fontWeight:'900',letterSpacing:1.2},title:{color:colors.ink,fontSize:26,fontWeight:'900'},close:{padding:10,backgroundColor:colors.surface,borderRadius:10},closeText:{color:colors.ink,fontWeight:'800'},calendarCard:{margin:20,marginTop:0,backgroundColor:colors.surface,borderRadius:18,padding:15,gap:13},monthRow:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},monthButton:{width:42,height:42,borderRadius:12,backgroundColor:'#EEEAE2',alignItems:'center',justifyContent:'center'},monthButtonText:{fontSize:30,color:colors.brandDark,lineHeight:32},monthLabel:{color:colors.ink,fontSize:18,fontWeight:'900'},week:{flexDirection:'row'},weekDay:{width:'14.285%',textAlign:'center',color:colors.muted,fontSize:10,fontWeight:'800'},days:{flexDirection:'row',flexWrap:'wrap'},day:{width:'14.285%',height:46,alignItems:'center',justifyContent:'center',borderRadius:23},dayActive:{backgroundColor:colors.brand},dayText:{color:colors.ink,fontSize:15,fontWeight:'700'},dayTextActive:{color:'#FFF'},today:{textDecorationLine:'underline',color:colors.brandDark,fontWeight:'900'},disabled:{color:'#C7C2B8'},quickRow:{flexDirection:'row',gap:9},quick:{flex:1,borderWidth:1,borderColor:colors.brand,borderRadius:11,padding:12,alignItems:'center'},quickText:{color:colors.brandDark,fontWeight:'900'}});
