import {Children,useEffect,useState,type ReactNode} from 'react';
import {Animated,Pressable,StyleSheet,Text,TouchableOpacity,View} from 'react-native';
import {colors} from '../theme';

export type MenuTone='navy'|'orange'|'cream';

export function ExpandableMenuSection({title,hint,tone='navy',open,onToggle,children}:{title:string;hint:string;tone?:MenuTone;open:boolean;onToggle:()=>void;children:ReactNode}){
  const items=Children.toArray(children);const[render,setRender]=useState(open);const progress=useState(()=>new Animated.Value(open?1:0))[0];
  useEffect(()=>{if(open)setRender(true);const animation=Animated.timing(progress,{toValue:open?1:0,duration:open?230:170,useNativeDriver:false});animation.start(({finished})=>{if(finished&&!open)setRender(false);});return()=>animation.stop();},[open,progress]);
  const dark=tone!=='cream';return <View style={styles.section}><Pressable onPress={onToggle} accessibilityRole="button" accessibilityState={{expanded:open}}><View style={[styles.header,tone==='navy'?styles.navy:tone==='orange'?styles.orange:styles.cream]}><View style={styles.copy}><Text style={[styles.title,dark&&styles.light]}>{title}</Text><Text style={[styles.hint,dark&&styles.lightHint]}>{hint}</Text></View><Animated.Text style={[styles.plus,dark&&styles.light,{transform:[{rotate:progress.interpolate({inputRange:[0,1],outputRange:['0deg','45deg']})}]}]}>+</Animated.Text><Animated.View style={[styles.accent,{width:progress.interpolate({inputRange:[0,1],outputRange:['0%','100%']})}]}/></View></Pressable>{render?<View style={styles.body}>{items.map((item,index)=><Animated.View key={index} style={{opacity:progress,transform:[{translateY:progress.interpolate({inputRange:[0,1],outputRange:[-6,0]})}]}}>{item}</Animated.View>)}</View>:null}</View>;
}

export function MenuAction({number,title,body,onPress,tone='white',badge}:{number:string;title:string;body:string;onPress:()=>void;tone?:'white'|'cream'|'orange';badge?:string}){
  return <TouchableOpacity activeOpacity={.7} style={[styles.action,tone==='cream'&&styles.actionCream,tone==='orange'&&styles.actionOrange]} onPress={onPress} accessibilityRole="button"><Text style={styles.number}>{number}</Text><View style={styles.actionCopy}>{badge?<Text style={styles.badge}>{badge}</Text>:null}<Text style={styles.actionTitle}>{title}</Text><Text style={styles.actionBody}>{body}</Text></View><Text style={styles.arrow}>›</Text></TouchableOpacity>;
}

const styles=StyleSheet.create({section:{gap:8},header:{minHeight:67,borderRadius:15,paddingHorizontal:15,paddingVertical:12,flexDirection:'row',alignItems:'center',gap:12,overflow:'hidden'},navy:{backgroundColor:colors.navy},orange:{backgroundColor:colors.brand},cream:{backgroundColor:colors.cream,borderWidth:1,borderColor:'#E4D7C7'},copy:{flex:1,minWidth:0,gap:3},title:{color:colors.ink,fontSize:19,fontWeight:'900'},hint:{color:colors.muted,fontSize:11,lineHeight:16},light:{color:'#FFF8ED'},lightHint:{color:'#F2E2D5'},plus:{width:26,textAlign:'center',color:colors.navy,fontSize:27,fontWeight:'700'},accent:{position:'absolute',height:3,left:0,bottom:0,backgroundColor:colors.brand},body:{gap:8,paddingLeft:10},action:{minHeight:80,backgroundColor:colors.surface,borderRadius:14,borderLeftWidth:4,borderLeftColor:colors.navy,padding:14,flexDirection:'row',alignItems:'center',gap:11},actionCream:{backgroundColor:'#FFF8ED',borderLeftColor:colors.brand},actionOrange:{backgroundColor:'#FFF1E9',borderLeftColor:colors.brand,borderWidth:1,borderColor:'#F0C5B4'},number:{width:28,color:colors.brand,fontSize:10,fontWeight:'900'},actionCopy:{flex:1,minWidth:0,gap:3},badge:{color:colors.brandDark,fontSize:8,fontWeight:'900',letterSpacing:.7},actionTitle:{color:colors.ink,fontSize:16,fontWeight:'900'},actionBody:{color:colors.muted,fontSize:11,lineHeight:16},arrow:{color:colors.brand,fontSize:27,fontWeight:'900'}});
