import {useMemo,useState} from 'react';
import {Modal,SafeAreaView,ScrollView,StyleSheet,Text,TextInput,TouchableOpacity,View} from 'react-native';
import {colors} from '../theme';
import type {SelectOption} from './SearchableSelect';

export type SelectOptionGroup={id:string;label:string;options:SelectOption[]};

export function GroupedSearchableSelect({label,groups,selectedId,onSelect,placeholder='Select'}:{label:string;groups:SelectOptionGroup[];selectedId:string;onSelect:(id:string)=>void;placeholder?:string}){
  const[open,setOpen]=useState(false);const[search,setSearch]=useState('');const[openGroups,setOpenGroups]=useState<Set<string>>(()=>new Set());
  const selected=useMemo(()=>groups.flatMap(group=>group.options.map(option=>({...option,groupLabel:group.label}))).find(option=>option.id===selectedId),[groups,selectedId]);
  const visible=useMemo(()=>{const query=search.trim().toLocaleLowerCase('en-US');if(!query)return groups;return groups.map(group=>{const groupMatches=group.label.toLocaleLowerCase('en-US').includes(query);const options=groupMatches?group.options:group.options.filter(option=>`${option.label} ${option.detail??''}`.toLocaleLowerCase('en-US').includes(query));return{...group,options};}).filter(group=>group.options.length>0);},[groups,search]);
  function show(){setSearch('');setOpenGroups(new Set());setOpen(true);}
  function choose(id:string){onSelect(id);setOpen(false);setSearch('');setOpenGroups(new Set());}
  function toggle(id:string){setOpenGroups(current=>{const next=new Set(current);if(next.has(id))next.delete(id);else next.add(id);return next;});}
  const searching=Boolean(search.trim());
  return <View style={styles.field}><Text style={styles.label}>{label}</Text><TouchableOpacity style={styles.control} onPress={show} accessibilityRole="button"><View style={styles.controlCopy}><Text style={[styles.value,!selected&&styles.placeholder]} numberOfLines={1}>{selected?.label??placeholder}</Text>{selected?<Text style={styles.detail} numberOfLines={1}>{selected.groupLabel}{selected.detail?` · ${selected.detail}`:''}</Text>:null}</View><Text style={styles.chevron}>⌄</Text></TouchableOpacity><Modal visible={open} animationType="slide" presentationStyle="pageSheet" onRequestClose={()=>setOpen(false)}><SafeAreaView style={styles.modal}><View style={styles.header}><View style={styles.headerCopy}><Text style={styles.eyebrow}>CHOOSE CATEGORY, THEN ITEM</Text><Text style={styles.title}>{label.replace(' *','')}</Text></View><TouchableOpacity onPress={()=>setOpen(false)} style={styles.close}><Text style={styles.closeText}>Close</Text></TouchableOpacity></View><TextInput style={styles.search} value={search} onChangeText={setSearch} placeholder="Search category or item…" placeholderTextColor="#89939B" autoFocus/><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={styles.list}>{visible.map(group=>{const expanded=searching||openGroups.has(group.id);return <View key={group.id} style={styles.group}><TouchableOpacity activeOpacity={.72} style={styles.groupHeader} onPress={()=>toggle(group.id)} disabled={searching}><View style={styles.groupCopy}><Text style={styles.groupEyebrow}>CATEGORY</Text><Text style={styles.groupTitle}>{group.label}</Text></View><View style={styles.groupRight}><Text style={styles.count}>{group.options.length}</Text><Text style={styles.mark}>{expanded?'×':'+'}</Text></View></TouchableOpacity>{expanded?<View style={styles.options}>{group.options.map(option=><TouchableOpacity key={option.id} style={[styles.option,option.id===selectedId&&styles.optionSelected]} onPress={()=>choose(option.id)}><View style={styles.optionCopy}><Text style={styles.optionTitle}>{option.label}</Text>{option.detail?<Text style={styles.optionDetail}>{option.detail}</Text>:null}</View>{option.id===selectedId?<Text style={styles.check}>✓</Text>:null}</TouchableOpacity>)}</View>:null}</View>})}{visible.length===0?<Text style={styles.empty}>No matching categories or load-enabled items.</Text>:null}</ScrollView></SafeAreaView></Modal></View>;
}

const styles=StyleSheet.create({field:{gap:6},label:{color:colors.ink,fontSize:13,fontWeight:'800'},control:{minHeight:49,borderWidth:1,borderColor:colors.line,borderRadius:11,paddingHorizontal:13,paddingVertical:9,backgroundColor:'#FCFBF8',flexDirection:'row',alignItems:'center',gap:8},controlCopy:{flex:1},value:{color:colors.ink,fontSize:15,fontWeight:'700'},placeholder:{color:colors.muted,fontWeight:'500'},detail:{color:colors.muted,fontSize:11,marginTop:2},chevron:{color:colors.brandDark,fontSize:22,fontWeight:'900'},modal:{flex:1,backgroundColor:colors.background},header:{padding:20,flexDirection:'row',justifyContent:'space-between',alignItems:'center',gap:12},headerCopy:{flex:1},eyebrow:{color:colors.brand,fontSize:10,letterSpacing:1.2,fontWeight:'900'},title:{color:colors.ink,fontSize:25,fontWeight:'900'},close:{padding:10,backgroundColor:colors.surface,borderRadius:10},closeText:{color:colors.ink,fontWeight:'800'},search:{marginHorizontal:20,borderWidth:1,borderColor:colors.line,borderRadius:12,padding:13,backgroundColor:colors.surface,color:colors.ink},list:{padding:20,gap:10},group:{borderWidth:1,borderColor:'#A9C2D2',borderRadius:15,overflow:'hidden',backgroundColor:'#EAF2F6'},groupHeader:{minHeight:68,backgroundColor:colors.navy,borderLeftWidth:5,borderLeftColor:colors.brand,paddingHorizontal:14,paddingVertical:11,flexDirection:'row',alignItems:'center',gap:10},groupCopy:{flex:1},groupEyebrow:{color:'#F2A184',fontSize:8,fontWeight:'900',letterSpacing:1},groupTitle:{color:'#FFF',fontSize:17,fontWeight:'900',marginTop:2},groupRight:{flexDirection:'row',alignItems:'center',gap:9},count:{minWidth:29,textAlign:'center',color:colors.navy,backgroundColor:'#F3B09A',paddingHorizontal:7,paddingVertical:4,borderRadius:14,fontWeight:'900'},mark:{color:'#FFF',fontSize:24,width:22,textAlign:'center'},options:{padding:9,gap:8},option:{backgroundColor:colors.surface,borderRadius:11,padding:13,flexDirection:'row',alignItems:'center',gap:10,borderWidth:1,borderColor:'#D7E2E8'},optionSelected:{borderColor:colors.brand,backgroundColor:'#FBE9E4'},optionCopy:{flex:1},optionTitle:{color:colors.ink,fontSize:15,fontWeight:'800'},optionDetail:{color:colors.muted,fontSize:11,marginTop:3},check:{color:colors.brandDark,fontSize:18,fontWeight:'900'},empty:{color:colors.muted,textAlign:'center',padding:30}});
