import {Children,useState,type ReactNode} from 'react';
import {StyleSheet,Text,View} from 'react-native';
import {appliedEmulsionLitres,averageThickness,circleArea,coatLitres,compactedVolume,coverageArea,crossfallDifferenceMm,gradeElevationDifferenceM,looseThickness,looseVolume,massFromVolume,progressPercent,quantityVarianceTonnes,slopedSurfaceWidth,triangleArea,truckLoads,variableWidthArea} from '../../domain/pavement';
import {AppButton,AppCard,AppField,MetricCard} from './AppPrimitives';
import {ExpandableMenuSection} from './ExpandableMenu';
import {colors} from '../theme';

type Layer={name:string;kind:'granular'|'asphalt';thickness:string;density:string;spread:string;looseFactor:string};
const n=(value:string)=>{const parsed=Number(value.replace(',','.'));return Number.isFinite(parsed)?parsed:0;};
const f=(value:number,digits=2)=>Number.isFinite(value)?value.toLocaleString(undefined,{minimumFractionDigits:digits,maximumFractionDigits:digits}):'—';
const initialLayers:Layer[]=[{name:'Subbase',kind:'granular',thickness:'',density:'2.10',spread:'',looseFactor:'1.20'},{name:'Base course',kind:'granular',thickness:'',density:'2.20',spread:'',looseFactor:'1.18'},{name:'Asphalt base',kind:'asphalt',thickness:'',density:'2.40',spread:'',looseFactor:''},{name:'Binder course',kind:'asphalt',thickness:'',density:'2.40',spread:'',looseFactor:''},{name:'Wearing course',kind:'asphalt',thickness:'',density:'2.40',spread:'',looseFactor:''}];

export function PavementAdvancedSections({areaM2,plannedTonnes,onUseArea}:{areaM2:number;plannedTonnes:number;onUseArea:(area:number)=>void}){
  const[open,setOpen]=useState<Set<string>>(()=>new Set());const toggle=(key:string)=>setOpen(current=>{const next=new Set(current);if(next.has(key))next.delete(key);else next.add(key);return next;});
  const[geometry,setGeometry]=useState({length:'',widthStart:'',widthEnd:'',deduction:'0',triangleBase:'0',triangleHeight:'0',circleRadius:'0'});
  const[layers,setLayers]=useState(initialLayers);const[reverse,setReverse]=useState({tonnes:'',density:'2.40',thickness:'',payload:'20'});const[coats,setCoats]=useState({primeRate:'',tackRate:'',residue:'60'});const[milling,setMilling]=useState({depth:'',density:'2.30'});const[survey,setSurvey]=useState({width:'',crossfall:'',length:'',grade:''});const[actual,setActual]=useState({tonnes:'',payload:'20'});
  const geometryArea=Math.max(0,variableWidthArea(n(geometry.length),n(geometry.widthStart),n(geometry.widthEnd))+triangleArea(n(geometry.triangleBase),n(geometry.triangleHeight))+circleArea(n(geometry.circleRadius))-n(geometry.deduction));
  const updateLayer=(index:number,key:keyof Layer,value:string)=>setLayers(current=>current.map((layer,i)=>i===index?{...layer,[key]:value}:layer));
  const reverseCoverage=n(reverse.tonnes)>0&&n(reverse.thickness)>0&&n(reverse.density)>0?coverageArea(n(reverse.tonnes),n(reverse.thickness)*n(reverse.density)):0;
  const reverseThickness=n(reverse.tonnes)>0&&areaM2>0&&n(reverse.density)>0?averageThickness(n(reverse.tonnes),areaM2,n(reverse.density)):0;
  const prime=coatLitres(areaM2,n(coats.primeRate)),tack=coatLitres(areaM2,n(coats.tackRate)),residue=n(coats.residue)/100;
  const millingVolume=compactedVolume(areaM2,n(milling.depth)),millingTonnes=massFromVolume(millingVolume,n(milling.density));
  const actualTonnes=n(actual.tonnes),progress=plannedTonnes>0?progressPercent(actualTonnes,plannedTonnes):0,variance=plannedTonnes>0?quantityVarianceTonnes(actualTonnes,plannedTonnes):0;
  return <>
    <ExpandableMenuSection title="Geometry and Variable Width" hint="Tapered road sections, triangles, circles, and area deductions." open={open.has('geometry')} onToggle={()=>toggle('geometry')}><AppCard hint="Variable section area = length × average of start/end widths."><Pair><AppField label="Section length (m)" value={geometry.length} onChangeText={length=>setGeometry({...geometry,length})} keyboardType="decimal-pad"/><AppField label="Start width (m)" value={geometry.widthStart} onChangeText={widthStart=>setGeometry({...geometry,widthStart})} keyboardType="decimal-pad"/></Pair><Pair><AppField label="End width (m)" value={geometry.widthEnd} onChangeText={widthEnd=>setGeometry({...geometry,widthEnd})} keyboardType="decimal-pad"/><AppField label="Deductions (m²)" value={geometry.deduction} onChangeText={deduction=>setGeometry({...geometry,deduction})} keyboardType="decimal-pad"/></Pair><Pair><AppField label="Triangle base (m)" value={geometry.triangleBase} onChangeText={triangleBase=>setGeometry({...geometry,triangleBase})} keyboardType="decimal-pad"/><AppField label="Triangle height (m)" value={geometry.triangleHeight} onChangeText={triangleHeight=>setGeometry({...geometry,triangleHeight})} keyboardType="decimal-pad"/></Pair><AppField label="Circle radius (m)" value={geometry.circleRadius} onChangeText={circleRadius=>setGeometry({...geometry,circleRadius})} keyboardType="decimal-pad"/><Result label="Net calculated area" value={`${f(geometryArea)} m²`}/><AppButton label="Use This Net Area" disabled={geometryArea<=0} onPress={()=>onUseArea(geometryArea)}/></AppCard></ExpandableMenuSection>
    <ExpandableMenuSection title="Complete Layer Stack" hint="Subbase, base, asphalt base, binder, and wearing quantities." tone="orange" open={open.has('layers')} onToggle={()=>toggle('layers')}>{layers.map((layer,index)=>{const volume=compactedVolume(areaM2,n(layer.thickness)),tonnes=layer.kind==='asphalt'&&n(layer.spread)>0?(areaM2*n(layer.spread))/1000:massFromVolume(volume,n(layer.density));const loose=layer.kind==='granular'?looseVolume(volume,n(layer.looseFactor)):0,looseLayerMm=layer.kind==='asphalt'&&n(layer.looseFactor)>1?looseThickness(n(layer.thickness),n(layer.looseFactor)):0;return <AppCard key={layer.name} title={layer.name} hint={layer.kind==='asphalt'?'Asphalt mass uses kg/m². Loose thickness requires the project/paver factor.':'Granular material shows compacted and estimated loose volume.'}><Pair><AppField label="Compacted thickness (mm)" value={layer.thickness} onChangeText={value=>updateLayer(index,'thickness',value)} keyboardType="decimal-pad"/><AppField label="Density (t/m³)" value={layer.density} onChangeText={value=>updateLayer(index,'density',value)} keyboardType="decimal-pad"/></Pair>{layer.kind==='asphalt'?<Pair><AppField label="Spread rate (kg/m²)" value={layer.spread} onChangeText={value=>updateLayer(index,'spread',value)} keyboardType="decimal-pad"/><AppField label="Loose-thickness factor" value={layer.looseFactor} onChangeText={value=>updateLayer(index,'looseFactor',value)} keyboardType="decimal-pad" placeholder="Project value"/></Pair>:<AppField label="Loose-volume factor" value={layer.looseFactor} onChangeText={value=>updateLayer(index,'looseFactor',value)} keyboardType="decimal-pad"/>}<View style={styles.metricRow}><MetricCard label="Compacted volume" value={`${f(volume)} m³`} result/><MetricCard label={layer.kind==='asphalt'?'Required asphalt':'Mass cross-check'} value={`${f(tonnes,3)} t`} result/>{layer.kind==='granular'?<MetricCard label="Estimated loose volume" value={`${f(loose)} m³`} result/>:<MetricCard label="Before compaction · loose" value={looseLayerMm>0?`${f(looseLayerMm,1)} mm`:'Enter factor'} result/>}</View></AppCard>;})}</ExpandableMenuSection>
    <ExpandableMenuSection title="Reverse Coverage and Truck Loads" hint="Find coverage, average thickness, and the required whole trucks." tone="cream" open={open.has('reverse')} onToggle={()=>toggle('reverse')}><AppCard><Pair><AppField label="Available / delivered tonnes" value={reverse.tonnes} onChangeText={tonnes=>setReverse({...reverse,tonnes})} keyboardType="decimal-pad"/><AppField label="Density (t/m³)" value={reverse.density} onChangeText={density=>setReverse({...reverse,density})} keyboardType="decimal-pad"/></Pair><Pair><AppField label="Target thickness (mm)" value={reverse.thickness} onChangeText={thickness=>setReverse({...reverse,thickness})} keyboardType="decimal-pad"/><AppField label="Truck payload (t)" value={reverse.payload} onChangeText={payload=>setReverse({...reverse,payload})} keyboardType="decimal-pad"/></Pair><View style={styles.metricRow}><MetricCard label="Equivalent kg/m²" value={`${f(n(reverse.thickness)*n(reverse.density),1)} kg/m²`} result/><MetricCard label="Coverage at target" value={`${f(reverseCoverage)} m²`} result/><MetricCard label="Average thickness on current area" value={`${f(reverseThickness,1)} mm`} result/><MetricCard label="Whole trucks" value={n(reverse.payload)>0?String(truckLoads(n(reverse.tonnes),n(reverse.payload))):'—'} result/></View></AppCard></ExpandableMenuSection>
    <ExpandableMenuSection title="Prime and Tack Coats" hint="Calculate litres from L/m² without mixing applied and residual rates." open={open.has('coats')} onToggle={()=>toggle('coats')}><AppCard><Pair><AppField label="Prime coat applied rate (L/m²)" value={coats.primeRate} onChangeText={primeRate=>setCoats({...coats,primeRate})} keyboardType="decimal-pad"/><AppField label="Tack residual rate (L/m²)" value={coats.tackRate} onChangeText={tackRate=>setCoats({...coats,tackRate})} keyboardType="decimal-pad"/></Pair><AppField label="Emulsion residue (%)" value={coats.residue} onChangeText={residueValue=>setCoats({...coats,residue:residueValue})} keyboardType="decimal-pad"/><View style={styles.metricRow}><MetricCard label="Prime applied emulsion" value={`${f(prime)} L`} result/><MetricCard label="Tack residual" value={`${f(tack)} L`} result/><MetricCard label="Applied tack emulsion" value={residue>0&&residue<=1?`${f(appliedEmulsionLitres(tack,residue))} L`:'—'} result/></View><Text style={styles.note}>Use only the rates specified for this project. DROMEX does not select engineering application rates.</Text></AppCard></ExpandableMenuSection>
    <ExpandableMenuSection title="Milling" hint="Removal area, compacted volume, and estimated reclaimed tonnes." tone="orange" open={open.has('milling')} onToggle={()=>toggle('milling')}><AppCard><Pair><AppField label="Milling depth (mm)" value={milling.depth} onChangeText={depth=>setMilling({...milling,depth})} keyboardType="decimal-pad"/><AppField label="Removed-material density (t/m³)" value={milling.density} onChangeText={densityValue=>setMilling({...milling,density:densityValue})} keyboardType="decimal-pad"/></Pair><View style={styles.metricRow}><MetricCard label="Milling area" value={`${f(areaM2)} m²`} result/><MetricCard label="Removal volume" value={`${f(millingVolume)} m³`} result/><MetricCard label="Estimated reclaimed mass" value={`${f(millingTonnes,3)} t`} result/></View></AppCard></ExpandableMenuSection>
    <ExpandableMenuSection title="Crossfall, Slope, and Levels" hint="Edge-height difference, longitudinal rise/fall, and actual sloped width." tone="cream" open={open.has('survey')} onToggle={()=>toggle('survey')}><AppCard><Pair><AppField label="Horizontal width (m)" value={survey.width} onChangeText={widthValue=>setSurvey({...survey,width:widthValue})} keyboardType="decimal-pad"/><AppField label="Crossfall (%)" value={survey.crossfall} onChangeText={crossfall=>setSurvey({...survey,crossfall})} keyboardType="decimal-pad"/></Pair><Pair><AppField label="Road length (m)" value={survey.length} onChangeText={lengthValue=>setSurvey({...survey,length:lengthValue})} keyboardType="decimal-pad"/><AppField label="Longitudinal grade (%)" value={survey.grade} onChangeText={grade=>setSurvey({...survey,grade})} keyboardType="decimal-pad"/></Pair><View style={styles.metricRow}><MetricCard label="Crossfall edge difference" value={`${f(crossfallDifferenceMm(n(survey.width),n(survey.crossfall)),1)} mm`} result/><MetricCard label="Longitudinal rise / fall" value={`${f(gradeElevationDifferenceM(n(survey.length),n(survey.grade)),3)} m`} result/><MetricCard label="Actual sloped width" value={`${f(slopedSurfaceWidth(n(survey.width),n(survey.crossfall)),3)} m`} result/></View></AppCard></ExpandableMenuSection>
    <ExpandableMenuSection title="Actual Delivery and Variance" hint="Compare received asphalt with the planned amount and count trucks." open={open.has('actual')} onToggle={()=>toggle('actual')}><AppCard><Pair><AppField label="Actual delivered (t)" value={actual.tonnes} onChangeText={tonnes=>setActual({...actual,tonnes})} keyboardType="decimal-pad"/><AppField label="Truck payload (t)" value={actual.payload} onChangeText={payload=>setActual({...actual,payload})} keyboardType="decimal-pad"/></Pair><View style={styles.metricRow}><MetricCard label="Planned" value={`${f(plannedTonnes,3)} t`} result/><MetricCard label="Progress" value={plannedTonnes>0?`${f(progress,1)}%`:'—'} result/><MetricCard label="Variance" value={plannedTonnes>0?`${variance>=0?'+':''}${f(variance,3)} t`:'—'} result/><MetricCard label="Actual trucks" value={n(actual.payload)>0?String(truckLoads(actualTonnes,n(actual.payload))):'—'} result/></View></AppCard></ExpandableMenuSection>
  </>;
}
function Pair({children}:{children:ReactNode}){return <View style={styles.pair}>{Children.map(children,child=><View style={styles.pairItem}>{child}</View>)}</View>;}function Result({label,value}:{label:string;value:string}){return <View style={styles.result}><Text style={styles.resultLabel}>{label}</Text><Text style={styles.resultValue}>{value}</Text></View>;}
const styles=StyleSheet.create({pair:{flexDirection:'row',gap:10},pairItem:{flex:1,minWidth:0},metricRow:{flexDirection:'row',flexWrap:'wrap',gap:8},result:{backgroundColor:colors.result,borderWidth:2,borderColor:colors.resultDark,borderRadius:12,padding:14,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},resultLabel:{color:colors.resultSoft,fontSize:11,fontWeight:'900'},resultValue:{color:'#FFF',fontSize:20,fontWeight:'900'},note:{color:colors.warning,fontSize:11,lineHeight:17,fontWeight:'700'}});
