import { useMemo, useState } from 'react';
import { FlatList, Modal, SafeAreaView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';

import { colors } from '../theme';

export type SelectOption = { id: string; label: string; detail?: string };

export function SearchableSelect({ label, options, selectedId, onSelect, placeholder = 'Select', allowClear = false }: {
  label: string; options: SelectOption[]; selectedId: string; onSelect: (id: string) => void;
  placeholder?: string; allowClear?: boolean;
}) {
  const [open, setOpen] = useState(false); const [search, setSearch] = useState('');
  const selected = options.find((option) => option.id === selectedId);
  const visible = useMemo(() => { const query = search.trim().toLocaleLowerCase('en-US'); if (!query) return options; return options.filter((option) => `${option.label} ${option.detail ?? ''}`.toLocaleLowerCase('en-US').includes(query)); }, [options, search]);
  function choose(id: string) { onSelect(id); setOpen(false); setSearch(''); }
  return <View style={styles.field}><Text style={styles.label}>{label}</Text><TouchableOpacity style={styles.control} onPress={() => setOpen(true)} accessibilityRole="button"><View style={styles.controlCopy}><Text style={[styles.value, !selected && styles.placeholder]} numberOfLines={1}>{selected?.label ?? placeholder}</Text>{selected?.detail ? <Text style={styles.detail} numberOfLines={1}>{selected.detail}</Text> : null}</View><Text style={styles.chevron}>⌄</Text></TouchableOpacity><Modal visible={open} animationType="slide" presentationStyle="pageSheet" onRequestClose={() => setOpen(false)}><SafeAreaView style={styles.modal}><View style={styles.header}><View><Text style={styles.eyebrow}>CHOOSE FROM SAVED RECORDS</Text><Text style={styles.title}>{label.replace(' *', '')}</Text></View><TouchableOpacity onPress={() => setOpen(false)} style={styles.close}><Text style={styles.closeText}>Close</Text></TouchableOpacity></View><TextInput style={styles.search} value={search} onChangeText={setSearch} placeholder="Search…" placeholderTextColor="#89939B" autoFocus /><FlatList data={visible} keyExtractor={(item) => item.id} keyboardShouldPersistTaps="handled" contentContainerStyle={styles.list} ListHeaderComponent={allowClear ? <TouchableOpacity style={styles.option} onPress={() => choose('')}><Text style={styles.optionTitle}>None</Text></TouchableOpacity> : null} ListEmptyComponent={<Text style={styles.empty}>No matching records.</Text>} renderItem={({ item }) => <TouchableOpacity style={[styles.option, item.id === selectedId && styles.optionSelected]} onPress={() => choose(item.id)}><View style={styles.optionCopy}><Text style={styles.optionTitle}>{item.label}</Text>{item.detail ? <Text style={styles.optionDetail}>{item.detail}</Text> : null}</View>{item.id === selectedId ? <Text style={styles.check}>✓</Text> : null}</TouchableOpacity>} /></SafeAreaView></Modal></View>;
}

const styles = StyleSheet.create({ field: { gap: 6 }, label: { color: colors.ink, fontSize: 13, fontWeight: '800' }, control: { minHeight: 49, borderWidth: 1, borderColor: colors.line, borderRadius: 11, paddingHorizontal: 13, paddingVertical: 9, backgroundColor: '#FCFBF8', flexDirection: 'row', alignItems: 'center', gap: 8 }, controlCopy: { flex: 1 }, value: { color: colors.ink, fontSize: 15, fontWeight: '700' }, placeholder: { color: colors.muted, fontWeight: '500' }, detail: { color: colors.muted, fontSize: 11, marginTop: 2 }, chevron: { color: colors.brandDark, fontSize: 22, fontWeight: '900' }, modal: { flex: 1, backgroundColor: colors.background }, header: { padding: 20, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, eyebrow: { color: colors.brand, fontSize: 10, letterSpacing: 1.2, fontWeight: '900' }, title: { color: colors.ink, fontSize: 26, fontWeight: '900' }, close: { padding: 10, backgroundColor: colors.surface, borderRadius: 10 }, closeText: { color: colors.ink, fontWeight: '800' }, search: { marginHorizontal: 20, borderWidth: 1, borderColor: colors.line, borderRadius: 12, padding: 13, backgroundColor: colors.surface, color: colors.ink }, list: { padding: 20, gap: 9 }, option: { backgroundColor: colors.surface, borderRadius: 12, padding: 14, flexDirection: 'row', alignItems: 'center', gap: 10 }, optionSelected: { borderWidth: 1, borderColor: colors.brand, backgroundColor: '#FBE9E4' }, optionCopy: { flex: 1 }, optionTitle: { color: colors.ink, fontSize: 15, fontWeight: '800' }, optionDetail: { color: colors.muted, fontSize: 12, marginTop: 3 }, check: { color: colors.brandDark, fontSize: 18, fontWeight: '900' }, empty: { color: colors.muted, textAlign: 'center', padding: 30 } });
