import { createHash } from 'node:crypto';
import { readFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';

import { Client } from 'pg';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';

import { createEphemeralDatabase, type EphemeralDatabase } from '../helpers/db.ts';

/**
 * Better Auth's two-factor schema, generated by the pinned `auth@1.7.4` CLI
 * against a disposable database that already held migration 0001, and
 * committed unedited. The expectations below describe that actual output.
 *
 * **Neither `verified` nor `failedVerificationCount` has a database default.**
 * Better Auth's plugin schema declares `defaultValue: true` and
 * `defaultValue: 0` for them, but the pinned generator did not emit either as
 * a PostgreSQL default. The migration stays exactly as generated (DEC-431):
 * the runtime values come from Better Auth's adapter, which applies the
 * plugin-schema defaults on every insert it performs. That adapter is the only
 * writer of this table; `auth-two-factor-rows.test.ts` proves every supported
 * flow leaves both columns non-null.
 */
const MIGRATION = (file: string) =>
  fileURLToPath(new URL(`../../migrations/better-auth/${file}`, import.meta.url));

/** SHA-256 of the CLI's output, recorded when it was generated (LF line endings). */
const GENERATED_SHA256 = 'dfa8a47c0ae919b5e8b0aa5bf093c18bb213a82b6bfcba14849709c860dcd3ae';

interface Column {
  column_name: string;
  data_type: string;
  is_nullable: 'YES' | 'NO';
  column_default: string | null;
}

describe('Better Auth two-factor schema on PostgreSQL 18.6', () => {
  let database: EphemeralDatabase;
  let client: Client;
  let twoFactorSql: string;

  async function columns(table: string): Promise<Column[]> {
    const { rows } = await client.query<Column>(
      `SELECT column_name, data_type, is_nullable, column_default
         FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = $1
        ORDER BY column_name`,
      [table],
    );
    return rows;
  }

  beforeAll(async () => {
    twoFactorSql = await readFile(MIGRATION('0002_two_factor.sql'), 'utf8');
    database = await createEphemeralDatabase();
    client = new Client({ connectionString: database.uri });
    await client.connect();
    await client.query(await readFile(MIGRATION('0001_better_auth_init.sql'), 'utf8'));
    await client.query(twoFactorSql);
  });

  afterAll(async () => {
    await client?.end().catch(() => undefined);
    await database?.drop().catch(() => undefined);
  });

  it('is byte-for-byte the output of the pinned CLI, apart from checkout line endings', () => {
    const digest = createHash('sha256').update(twoFactorSql.replaceAll('\r\n', '\n')).digest('hex');

    expect(digest).toBe(GENERATED_SHA256);
  });

  it('adds exactly one table, "twoFactor"', async () => {
    const { rows } = await client.query<{ table_name: string }>(
      `SELECT table_name FROM information_schema.tables
        WHERE table_schema = 'public' AND table_type = 'BASE TABLE' ORDER BY table_name`,
    );

    expect(rows.map((row) => row.table_name)).toEqual([
      'account',
      'rateLimit',
      'session',
      'twoFactor',
      'user',
      'verification',
    ]);
  });

  it('adds only a nullable "twoFactorEnabled" boolean, defaulting false, to "user"', async () => {
    const added = (await columns('user')).find((column) => column.column_name === 'twoFactorEnabled');

    expect(added).toEqual({
      column_name: 'twoFactorEnabled',
      data_type: 'boolean',
      is_nullable: 'YES',
      column_default: 'false',
    });
    expect((await columns('user')).map((column) => column.column_name)).toEqual([
      'createdAt',
      'email',
      'emailVerified',
      'id',
      'image',
      'name',
      'twoFactorEnabled',
      'updatedAt',
    ]);
  });

  it('leaves "session" unchanged', async () => {
    expect((await columns('session')).map((column) => column.column_name)).toEqual([
      'createdAt',
      'expiresAt',
      'id',
      'ipAddress',
      'token',
      'updatedAt',
      'userAgent',
      'userId',
    ]);
  });

  it('creates "twoFactor" with the generated column inventory, types, and nullability, and no column defaults', async () => {
    expect(await columns('twoFactor')).toEqual([
      { column_name: 'backupCodes', data_type: 'text', is_nullable: 'NO', column_default: null },
      { column_name: 'failedVerificationCount', data_type: 'integer', is_nullable: 'YES', column_default: null },
      { column_name: 'id', data_type: 'text', is_nullable: 'NO', column_default: null },
      { column_name: 'lockedUntil', data_type: 'timestamp with time zone', is_nullable: 'YES', column_default: null },
      { column_name: 'secret', data_type: 'text', is_nullable: 'NO', column_default: null },
      { column_name: 'userId', data_type: 'text', is_nullable: 'NO', column_default: null },
      { column_name: 'verified', data_type: 'boolean', is_nullable: 'YES', column_default: null },
    ]);
  });

  it('stores NULL, not a default, when a row omits "verified" and "failedVerificationCount"', async () => {
    // Inside a rolled-back transaction, so the remaining schema checks see an
    // empty table. This is why only Better Auth's adapter may write the table.
    await client.query('BEGIN');
    try {
      await client.query(
        `INSERT INTO "user" (id, name, email, "emailVerified") VALUES ('schema-user', 'Synthetic', 'schema@synthetic.invalid', false)`,
      );
      await client.query(
        `INSERT INTO "twoFactor" (id, secret, "backupCodes", "userId") VALUES ('schema-factor', 'synthetic', 'synthetic', 'schema-user')`,
      );
      const { rows } = await client.query(
        `SELECT verified, "failedVerificationCount", "lockedUntil" FROM "twoFactor" WHERE id = 'schema-factor'`,
      );

      expect(rows).toEqual([{ verified: null, failedVerificationCount: null, lockedUntil: null }]);
    } finally {
      await client.query('ROLLBACK');
    }
  });

  it('links "twoFactor"."userId" to "user"."id", cascading on delete', async () => {
    const { rows } = await client.query<{ column_name: string; foreign_table: string; delete_rule: string }>(
      `SELECT kcu.column_name, ccu.table_name AS foreign_table, rc.delete_rule
         FROM information_schema.table_constraints tc
         JOIN information_schema.key_column_usage kcu ON kcu.constraint_name = tc.constraint_name
         JOIN information_schema.constraint_column_usage ccu ON ccu.constraint_name = tc.constraint_name
         JOIN information_schema.referential_constraints rc ON rc.constraint_name = tc.constraint_name
        WHERE tc.table_schema = 'public' AND tc.table_name = 'twoFactor' AND tc.constraint_type = 'FOREIGN KEY'`,
    );

    expect(rows).toEqual([{ column_name: 'userId', foreign_table: 'user', delete_rule: 'CASCADE' }]);
  });

  it('indexes "secret" and "userId" without making "userId" unique', async () => {
    const { rows } = await client.query<{ indexname: string; indexdef: string }>(
      `SELECT indexname, indexdef FROM pg_indexes
        WHERE schemaname = 'public' AND tablename = 'twoFactor' ORDER BY indexname`,
    );

    expect(rows.map((row) => row.indexname)).toEqual([
      'twoFactor_pkey',
      'twoFactor_secret_idx',
      'twoFactor_userId_idx',
    ]);
    for (const row of rows) {
      if (row.indexname !== 'twoFactor_pkey') expect(row.indexdef).not.toMatch(/UNIQUE/i);
    }
  });

  it('contains no destructive, privileged, or unrelated statement', () => {
    const sql = twoFactorSql.toLowerCase();

    for (const dangerous of [
      'drop ',
      'truncate',
      'delete from',
      'update ',
      'insert into',
      'grant ',
      'revoke ',
      'create role',
      'alter role',
      'create extension',
      'owner to',
      '"session"',
      '"account"',
      '"verification"',
      '"ratelimit"',
    ]) {
      expect(sql, dangerous).not.toContain(dangerous);
    }
  });

  it('contains no secret, connection string, or environment value', () => {
    const sql = twoFactorSql.toLowerCase();

    for (const leak of ['postgresql://', 'postgres://', 'better_auth_secret', 'dromex_schema_gen', 'dromex_dev', '5433', '127.0.0.1', 'localhost', '$ba$']) {
      expect(sql).not.toContain(leak);
    }
  });
});
