import { readFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';

import { Client } from 'pg';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';

import { createEphemeralDatabase, type EphemeralDatabase } from '../helpers/db.ts';

/**
 * The Better Auth schema, generated by the pinned `auth@1.7.4` CLI and
 * committed under its own migration directory. It is kept entirely separate
 * from the Android SQLite migrations and from future DROMEX business and
 * permission migrations (DEC-431).
 */
const MIGRATION_PATH = fileURLToPath(
  new URL('../../migrations/better-auth/0001_better_auth_init.sql', import.meta.url),
);

/** Better Auth's four core tables, plus its database-backed rate limiter. */
const EXPECTED_TABLES = ['user', 'session', 'account', 'verification', 'rateLimit'];

/**
 * Tables that must never appear in a Better Auth migration. If any of these
 * were created here, the authentication schema would have reached into
 * DROMEX business data or Android territory.
 */
const FORBIDDEN_TABLE_FRAGMENTS = [
  'project',
  'load',
  'fuel',
  'payment',
  'supplier',
  'customer',
  'waste',
  'wall',
  'pavement',
  'principal',
  'permission',
  'consulting',
];

describe('Better Auth schema on PostgreSQL 18.6', () => {
  let database: EphemeralDatabase;
  let client: Client;
  let migrationSql: string;

  beforeAll(async () => {
    migrationSql = await readFile(MIGRATION_PATH, 'utf8');

    database = await createEphemeralDatabase();
    client = new Client({ connectionString: database.uri });
    await client.connect();

    // Applied only to a disposable, per-test-file database. Never to the
    // persistent development database, which the global setup guard refuses.
    await client.query(migrationSql);
  });

  afterAll(async () => {
    await client?.end().catch(() => undefined);
    await database?.drop().catch(() => undefined);
  });

  it('confirms the server really is PostgreSQL 18.6', async () => {
    // `SHOW server_version` returns a column named after the setting itself.
    const { rows } = await client.query<{ server_version: string }>(
      'SHOW server_version',
    );

    expect(rows[0]?.server_version).toMatch(/^18\.6\b/);
  });

  it('creates every expected Better Auth table', async () => {
    const { rows } = await client.query<{ table_name: string }>(
      `SELECT table_name FROM information_schema.tables
       WHERE table_schema = 'public' AND table_type = 'BASE TABLE'`,
    );
    const tables = rows.map((row) => row.table_name);

    for (const expected of EXPECTED_TABLES) {
      expect(tables).toContain(expected);
    }
  });

  it('creates no DROMEX business or Android table', async () => {
    const { rows } = await client.query<{ table_name: string }>(
      `SELECT table_name FROM information_schema.tables
       WHERE table_schema = 'public' AND table_type = 'BASE TABLE'`,
    );

    for (const table of rows.map((row) => row.table_name.toLowerCase())) {
      for (const forbidden of FORBIDDEN_TABLE_FRAGMENTS) {
        expect(table).not.toContain(forbidden);
      }
    }
  });

  it('gives every table a primary key', async () => {
    const { rows } = await client.query<{ table_name: string }>(
      `SELECT t.table_name
         FROM information_schema.tables t
        WHERE t.table_schema = 'public'
          AND t.table_type = 'BASE TABLE'
          AND NOT EXISTS (
            SELECT 1 FROM information_schema.table_constraints c
             WHERE c.table_schema = 'public'
               AND c.table_name = t.table_name
               AND c.constraint_type = 'PRIMARY KEY'
          )`,
    );

    expect(rows.map((row) => row.table_name)).toEqual([]);
  });

  it('enforces a unique user email', async () => {
    const { rows } = await client.query<{ count: string }>(
      `SELECT count(*)::text AS count
         FROM information_schema.table_constraints c
         JOIN information_schema.constraint_column_usage u
           ON u.constraint_name = c.constraint_name
          AND u.table_schema = c.table_schema
        WHERE c.table_schema = 'public'
          AND c.table_name = 'user'
          AND c.constraint_type = 'UNIQUE'
          AND u.column_name = 'email'`,
    );

    expect(Number(rows[0]?.count ?? 0)).toBeGreaterThan(0);
  });

  it('enforces a unique session token', async () => {
    const { rows } = await client.query<{ count: string }>(
      `SELECT count(*)::text AS count
         FROM information_schema.table_constraints c
         JOIN information_schema.constraint_column_usage u
           ON u.constraint_name = c.constraint_name
          AND u.table_schema = c.table_schema
        WHERE c.table_schema = 'public'
          AND c.table_name = 'session'
          AND c.constraint_type = 'UNIQUE'
          AND u.column_name = 'token'`,
    );

    expect(Number(rows[0]?.count ?? 0)).toBeGreaterThan(0);
  });

  it('links session and account to user by foreign key', async () => {
    const { rows } = await client.query<{ table_name: string; foreign_table: string }>(
      `SELECT c.table_name, u.table_name AS foreign_table
         FROM information_schema.table_constraints c
         JOIN information_schema.constraint_column_usage u
           ON u.constraint_name = c.constraint_name
          AND u.table_schema = c.table_schema
        WHERE c.table_schema = 'public'
          AND c.constraint_type = 'FOREIGN KEY'`,
    );

    const links = rows.map((row) => `${row.table_name}->${row.foreign_table}`);
    expect(links).toContain('session->user');
    expect(links).toContain('account->user');
  });

  it('provides the database-backed rate limit table with a key and count', async () => {
    const { rows } = await client.query<{ column_name: string }>(
      `SELECT column_name FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = 'rateLimit'`,
    );
    const columns = rows.map((row) => row.column_name.toLowerCase());

    expect(columns).toContain('key');
    expect(columns).toContain('count');
  });

  it('inserts no row: the migration creates structure only', async () => {
    for (const table of EXPECTED_TABLES) {
      const { rows } = await client.query<{ count: string }>(
        `SELECT count(*)::text AS count FROM "${table}"`,
      );

      expect(Number(rows[0]?.count ?? -1)).toBe(0);
    }
  });

  it('contains no credential value, connection string, or environment value', async () => {
    // Note what is deliberately NOT asserted: the SQL legitimately declares
    // columns named "password", "accessToken", and "refreshToken" on the
    // account table. Those are column names in a schema, not secrets. The
    // real risk is an embedded *value* — a connection string, a generated
    // secret, or a development host — so that is what is checked.
    const sql = migrationSql.toLowerCase();

    for (const leak of [
      'postgresql://',
      'postgres://',
      'better_auth_secret',
      'dromex_schema_gen_database_url',
      'ckpt3b_synthetic',
      'dromex_dev',
      '5433',
      '127.0.0.1',
      'localhost',
    ]) {
      expect(sql).not.toContain(leak);
    }

    // No literal assignment of a credential-shaped value.
    expect(sql).not.toMatch(/password\s*=\s*'/);
    expect(sql).not.toMatch(/secret\s*=\s*'/);
  });

  it('performs no destructive or privileged operation', async () => {
    const sql = migrationSql.toLowerCase();

    for (const dangerous of [
      'drop table',
      'drop database',
      'drop schema',
      'truncate',
      'delete from',
      'create database',
      'create role',
      'alter role',
      'grant ',
      'revoke ',
      'create extension',
      'alter system',
      'owner to',
    ]) {
      expect(sql).not.toContain(dangerous);
    }
  });

  it('fails loudly when the raw SQL file is replayed', async () => {
    // The generated SQL is plain CREATE TABLE with no IF NOT EXISTS, so
    // replaying the *file* must fail rather than silently succeed or
    // partially mutate. Asserted, not assumed.
    //
    // Note what this does NOT imply. Better Auth's own `migrate` command is
    // safe to re-run: it introspects the live schema, computes the
    // difference, and reports "No migrations needed" when there is none.
    // Verified empirically against a disposable database — and there is no
    // ledger table anywhere, because the live schema *is* the record of what
    // has been applied. Anything that replays this file directly, rather
    // than going through the CLI, is what needs its own tracking.
    await expect(client.query(migrationSql)).rejects.toThrow(/already exists/i);
  });
});
