import {useCallback,useEffect,useState} from 'react';
import {StyleSheet,Text,TouchableOpacity,View} from 'react-native';
import Storage from 'expo-sqlite/kv-store';
import type {WorkspaceRepository} from '../../data/repositories/WorkspaceRepository';
import type {AttentionSnapshot,GlobalSearchRoute} from '../../domain/workspace';
import {AppPage,EmptyState,Feedback,PageHeader} from '../components/AppPrimitives';
import {countMeaningfulStoredDrafts} from '../draftRecognition';
import {colors} from '../theme';

type Item={key:keyof AttentionSnapshot|'otherDrafts';title:string;hint:string;route:GlobalSearchRoute|'drafts'|'attention';tone:'danger'|'warning'|'navy'};
const items:Item[]=[{key:'missingReportsToday',title:'Missing Daily Reports',hint:'Active projects with a load today but no daily report.',route:'reports',tone:'danger'},{key:'blockedSchedule',title:'Blocked Scheduled Work',hint:'Planned work explicitly marked Blocked.',route:'schedule',tone:'danger'},{key:'openIssues',title:'Open Project Issues',hint:'Project blockers and follow-up work still open.',route:'projects',tone:'warning'},{key:'unpricedLoads',title:'Unpriced Receipts',hint:'Confirmed loads that still need a price.',route:'loads',tone:'warning'},{key:'outstandingRecords',title:'Outstanding Balances',hint:'Unpaid or partially paid customer and supplier records.',route:'financials',tone:'warning'},{key:'incompleteWaste',title:'Incomplete Waste Details',hint:'Active dumps missing material, location, driver, or truck.',route:'waste',tone:'warning'},{key:'syncPending',title:'Pending Synchronization',hint:'Local changes waiting in the offline synchronization queue.',route:'attention',tone:'navy'},{key:'loadDrafts',title:'Receipt Drafts',hint:'Unfinished outgoing-load entries saved locally.',route:'drafts',tone:'navy'},{key:'otherDrafts',title:'Other Drafts',hint:'Unfinished daily report, quarry, fuel, or Quick Text work.',route:'drafts',tone:'navy'}];

export function AttentionScreen({repository,onBack,onOpen}:{repository:WorkspaceRepository;onBack:()=>void;onOpen:(route:GlobalSearchRoute|'drafts')=>void}){
  const[snapshot,setSnapshot]=useState<AttentionSnapshot|null>(null);const[otherDrafts,setOtherDrafts]=useState(0);const[error,setError]=useState<string|null>(null);const refresh=useCallback(async()=>{const[next,keys]=await Promise.all([repository.getAttentionSnapshot(),Storage.getAllKeys()]);const draftKeys=keys.filter(key=>key.startsWith('dromex.draft.'));const values=await Promise.all(draftKeys.map(key=>Storage.getItem(key)));setSnapshot(next);setOtherDrafts(countMeaningfulStoredDrafts(draftKeys.map((key,index)=>[key,values[index]??null])));},[repository]);useEffect(()=>{void refresh().catch(cause=>setError(cause instanceof Error?cause.message:'Needs Attention could not be loaded.'));},[refresh]);if(!snapshot)return <View style={styles.loading}><Text style={styles.helper}>Checking records that need attention…</Text></View>;const active=items.map(item=>({...item,count:item.key==='otherDrafts'?otherDrafts:snapshot[item.key]})).filter(item=>item.count>0);return <AppPage><PageHeader eyebrow="DAILY CONTROL" title="Needs Attention" onBack={onBack}/><View style={styles.hero}><Text style={styles.heroNumber}>{active.reduce((sum,item)=>sum+item.count,0)}</Text><View style={styles.flex}><Text style={styles.heroTitle}>items need review</Text><Text style={styles.heroHint}>Every label opens the related records. Nothing here silently changes a confirmed record.</Text></View></View>{error?<Feedback kind="error">{error}</Feedback>:null}{active.length?active.map(item=><TouchableOpacity key={item.key} style={[styles.item,item.tone==='danger'?styles.danger:item.tone==='warning'?styles.warning:styles.navy]} onPress={()=>item.route==='attention'?undefined:onOpen(item.route)} disabled={item.route==='attention'}><View style={styles.flex}><Text style={[styles.title,item.tone==='navy'&&styles.light]}>{item.title}</Text><Text style={[styles.hint,item.tone==='navy'&&styles.lightHint]}>{item.hint}</Text></View><View style={[styles.count,item.tone==='navy'&&styles.countLight]}><Text style={[styles.countText,item.tone==='navy'&&styles.countTextDark]}>{item.count}</Text></View>{item.route!=='attention'?<Text style={[styles.arrow,item.tone==='navy'&&styles.light]}>›</Text>:null}</TouchableOpacity>):<EmptyState title="Nothing needs attention" body="No missing reports, blocked work, open issues, incomplete dumps, drafts, or outstanding record alerts were found."/>}</AppPage>;
}
const styles=StyleSheet.create({loading:{flex:1,alignItems:'center',justifyContent:'center'},helper:{color:colors.muted,fontSize:12},hero:{backgroundColor:colors.brand,borderRadius:17,padding:17,flexDirection:'row',alignItems:'center',gap:14},heroNumber:{color:colors.navy,fontSize:38,fontWeight:'900'},flex:{flex:1,minWidth:0},heroTitle:{color:colors.navy,fontSize:19,fontWeight:'900'},heroHint:{color:'#173F67',fontSize:10,lineHeight:15,marginTop:3},item:{minHeight:78,borderRadius:14,padding:14,flexDirection:'row',alignItems:'center',gap:10},danger:{backgroundColor:'#FCE8E6',borderLeftWidth:4,borderLeftColor:colors.danger},warning:{backgroundColor:'#FFF3D8',borderLeftWidth:4,borderLeftColor:colors.warning},navy:{backgroundColor:colors.navy},title:{color:colors.ink,fontSize:15,fontWeight:'900'},hint:{color:colors.muted,fontSize:10,lineHeight:15,marginTop:3},light:{color:'#FFF8ED'},lightHint:{color:'#D5E4EF'},count:{minWidth:32,height:32,borderRadius:16,backgroundColor:colors.brand,alignItems:'center',justifyContent:'center'},countLight:{backgroundColor:'#FFF8ED'},countText:{color:'#FFF',fontWeight:'900'},countTextDark:{color:colors.navy},arrow:{color:colors.brand,fontSize:25,fontWeight:'900'}});
