import {useState} from 'react';
import {Alert,Platform,StyleSheet,Text,View} from 'react-native';
import type {BackupPreview,SelectedBackup} from '../../domain/backup';
import type {BackupRepository} from '../../data/repositories/BackupRepository';
import {AppButton,AppCard,AppField,AppPage,Feedback,MetricCard,PageHeader} from '../components/AppPrimitives';
import {colors} from '../theme';

export function BackupRestoreScreen({repository,onBack,onRestored}:{repository:BackupRepository;onBack:()=>void;onRestored:()=>void}){
  const[exportPassword,setExportPassword]=useState(''),[exportConfirmation,setExportConfirmation]=useState('');
  const[selected,setSelected]=useState<SelectedBackup|null>(null),[restorePassword,setRestorePassword]=useState(''),[preview,setPreview]=useState<BackupPreview|null>(null);
  const[safetyPassword,setSafetyPassword]=useState(''),[safetyConfirmation,setSafetyConfirmation]=useState('');
  const[busy,setBusy]=useState<string|null>(null),[error,setError]=useState<string|null>(null),[message,setMessage]=useState<string|null>(null);
  const run=async(label:string,action:()=>Promise<void>)=>{setBusy(label);setError(null);setMessage(null);try{await action();}catch(cause){setError(cause instanceof Error?cause.message:'The backup operation could not be completed.');}finally{setBusy(null);}};
  const create=()=>void run('Creating encrypted backup…',async()=>{if(exportPassword!==exportConfirmation)throw new Error('The backup passwords do not match.');const result=await repository.exportToSelectedFolder(exportPassword);setMessage(Platform.OS==='ios'?`${result.filename} was encrypted. Keep it in the Apple Files location you selected; an app-owned copy is also retained.`:`${result.filename} was encrypted and saved to the selected folder. A local safety copy was also retained.`);setExportPassword('');setExportConfirmation('');});
  const choose=()=>void run('Opening files…',async()=>{const result=await repository.selectBackup();if(!result)return;setSelected(result);setPreview(null);setRestorePassword('');setSafetyPassword('');setSafetyConfirmation('');setMessage(`Selected ${result.name}. Enter its backup password to inspect it.`);});
  const inspect=()=>void run('Checking backup…',async()=>{if(!selected)throw new Error('Select a DROMEX backup first.');setPreview(await repository.inspectBackup(selected,restorePassword));setMessage('Backup unlocked and validated. Review the contents before replacing this phone.');});
  const restore=async()=>{if(!selected||!preview)return;if(safetyPassword!==safetyConfirmation){setError('The safety-backup passwords do not match.');return;}if(safetyPassword.length<12){setError('Use a safety-backup password of at least 12 characters.');return;}const confirmed=await confirmReplacement(preview);if(!confirmed)return;void run('Restoring complete backup…',async()=>{const result=await repository.restoreBackup(selected,restorePassword,safetyPassword);Alert.alert('Restore complete',`The selected backup now replaces this phone's DROMEX data. Your pre-restore safety copy was saved as ${result.safetyBackupFilename}.`,[{text:'Open restored DROMEX',onPress:onRestored}],{cancelable:false});});};
  return <AppPage keyboard><PageHeader eyebrow="OFFLINE DATA PROTECTION" title="Backup & Restore" onBack={onBack}/>
    <View style={styles.hero}><View style={styles.heroMark}><Text style={styles.heroMarkText}>B</Text></View><View style={styles.flex}><Text style={styles.heroTitle}>Your complete device copy</Text><Text style={styles.heroBody}>{Platform.OS==='ios'?'Create one encrypted file containing everything, then choose Save to Files and select iCloud Drive, On My iPhone, or another Files provider.':"Create one encrypted file containing everything, then choose Google Drive, Downloads, USB, or another Android document provider."}</Text></View></View>
    {busy?<Feedback kind="warning">{busy} Keep DROMEX open until this finishes.</Feedback>:null}{error?<Feedback kind="error">{error}</Feedback>:null}{message?<Feedback kind="success">{message}</Feedback>:null}
    <AppCard title="01 · Create encrypted backup" hint="The password is never stored. You will need it on a replacement phone.">
      <AppField label="Backup password *" value={exportPassword} onChangeText={setExportPassword} secureTextEntry autoCapitalize="none" placeholder="At least 12 characters"/>
      <AppField label="Confirm backup password *" value={exportConfirmation} onChangeText={setExportConfirmation} secureTextEntry autoCapitalize="none" placeholder="Enter it again"/>
      <AppButton label={Platform.OS==='ios'?'Create & Save to Apple Files':'Choose Drive Folder & Back Up'} busy={busy!==null} disabled={!exportPassword||!exportConfirmation} onPress={create}/>
    </AppCard>
    <AppCard title="02 · Select a backup to restore" hint={Platform.OS==='ios'?'Select a visible .dromexbackup file from iCloud Drive, On My iPhone, USB storage, or another Apple Files provider.':'Select a visible .dromexbackup file from Google Drive, USB storage, Downloads, or another Android document provider.'}>
      <AppButton label={selected?`Selected: ${selected.name}`:'Select Backup File'} tone="navy" disabled={busy!==null} onPress={choose}/>
      {selected?<><AppField label="Backup password *" value={restorePassword} onChangeText={value=>{setRestorePassword(value);setPreview(null);}} secureTextEntry autoCapitalize="none"/><AppButton label="Unlock & Preview" tone="secondary" busy={busy!==null} disabled={!restorePassword} onPress={inspect}/></>:null}
    </AppCard>
    {preview?<><BackupPreviewCard preview={preview}/><AppCard title="04 · Protect current data before restore" hint={Platform.OS==='ios'?'Choose a new password for the current phone’s safety copy. Apple Files will open first: save the file before returning to DROMEX.':'Choose a new password for the automatic safety copy of what is currently on this phone. Do not use the public demo password for real data.'}><AppField label="Safety-backup password *" value={safetyPassword} onChangeText={setSafetyPassword} secureTextEntry autoCapitalize="none" placeholder="At least 12 characters"/><AppField label="Confirm safety password *" value={safetyConfirmation} onChangeText={setSafetyConfirmation} secureTextEntry autoCapitalize="none"/><AppButton label={Platform.OS==='ios'?'Confirm, Save Safety File & Replace':'Confirm, Choose Safety Folder & Replace'} tone="danger" disabled={busy!==null||!safetyPassword||!safetyConfirmation} onPress={()=>void restore()}/></AppCard></>:null}
    <Feedback kind="warning">Keep at least two copies of important backups. If the backup password is forgotten, DROMEX cannot decrypt the file.</Feedback>
  </AppPage>;
}

function BackupPreviewCard({preview}:{preview:BackupPreview}){const counts=preview.recordCounts;return <AppCard tone="orange" title="03 · Verified restore preview" hint={`Created ${new Date(preview.createdAt).toLocaleString()} · DROMEX ${preview.appVersion}`}><View style={styles.metrics}><MetricCard label="Loads" value={String(counts.loads??0)} accent/><MetricCard label="Projects" value={String(counts.projects??0)} accent/></View><View style={styles.metrics}><MetricCard label="Payments" value={String(counts.payment_entries??counts.payment_entries_v2??0)}/><MetricCard label="Media files" value={String(preview.mediaCount)}/></View><View style={styles.previewRows}><PreviewRow label="Customers" value={counts.customers??0}/><PreviewRow label="Daily reports" value={counts.daily_project_reports??0}/><PreviewRow label="Pavement calculations" value={counts.pavement_calculations??0}/><PreviewRow label="Walls / consumption" value={(counts.walls??0)+(counts.wall_consumptions??0)}/><PreviewRow label="Waste dumps" value={counts.waste_dumps??0}/><PreviewRow label="Fuel movements" value={counts.fuel_movements??0}/><PreviewRow label="Preferences & drafts" value={preview.preferenceCount}/><View style={styles.rule}/><Text style={styles.size}>{formatBytes(preview.encryptedBytes)} encrypted package · database version {preview.databaseVersion}</Text></View><Text style={styles.replaceWarning}>{Platform.OS==='ios'?'This replaces all DROMEX data on this iPhone and does not merge. Before replacement, Apple Files opens so you can save the encrypted current-data safety copy.':'This replaces all DROMEX data on this phone and does not merge. Before replacement, DROMEX requires a folder and saves an encrypted current-data safety copy.'}</Text></AppCard>;}
function PreviewRow({label,value}:{label:string;value:number}){return <View style={styles.row}><Text style={styles.rowLabel}>{label}</Text><Text style={styles.rowValue}>{value}</Text></View>;}
function formatBytes(value:number){if(value<1024)return`${value} B`;if(value<1024*1024)return`${(value/1024).toFixed(1)} KB`;return`${(value/1024/1024).toFixed(1)} MB`;}
function confirmReplacement(preview:BackupPreview){return new Promise<boolean>(resolve=>Alert.alert('Replace all data on this phone?',`Restore the backup from ${new Date(preview.createdAt).toLocaleString()}? DROMEX will first save a safety backup. Records will not be merged.`,[{text:'Cancel',style:'cancel',onPress:()=>resolve(false)},{text:'Replace & Restore',style:'destructive',onPress:()=>resolve(true)}],{cancelable:true,onDismiss:()=>resolve(false)}));}

const styles=StyleSheet.create({hero:{backgroundColor:colors.cream,borderRadius:18,borderWidth:1,borderColor:'#E5D6C4',padding:16,flexDirection:'row',gap:13,alignItems:'center'},heroMark:{width:48,height:48,borderRadius:14,backgroundColor:colors.brand,alignItems:'center',justifyContent:'center'},heroMarkText:{color:'#FFF',fontSize:24,fontWeight:'900'},flex:{flex:1,minWidth:0},heroTitle:{color:colors.navy,fontSize:17,fontWeight:'900'},heroBody:{color:colors.muted,fontSize:12,lineHeight:18,marginTop:3},metrics:{flexDirection:'row',gap:10},previewRows:{backgroundColor:'#FFF8ED',borderRadius:12,padding:13,gap:8},row:{flexDirection:'row',justifyContent:'space-between',gap:12},rowLabel:{color:colors.muted,fontSize:12,fontWeight:'700'},rowValue:{color:colors.navy,fontSize:13,fontWeight:'900'},rule:{height:1,backgroundColor:'#E7D6C3'},size:{color:colors.brandDark,fontSize:11,fontWeight:'900'},replaceWarning:{color:'#FFF',fontSize:12,lineHeight:18,fontWeight:'800'}});
