import {useCallback,useEffect,useState} from 'react';
import {Alert,StyleSheet,Text,TouchableOpacity,View} from 'react-native';
import Storage from 'expo-sqlite/kv-store';
import type {LoadRepository} from '../../data/repositories/LoadRepository';
import {isMeaningfulLoadDraft,type LoadDraft} from '../../domain/loads';
import {AppPage,EmptyState,Feedback,PageHeader} from '../components/AppPrimitives';
import {ExpandableMenuSection} from '../components/ExpandableMenu';
import {isMeaningfulStoredDraft} from '../draftRecognition';
import {colors} from '../theme';

export type DraftRoute='receipt'|'dailyReport'|'quarry'|'fuel'|'quickText';
type DraftEntry={id:string;key:string;type:string;title:string;detail:string;route:DraftRoute;projectId:string|null;payload:unknown;source:'load'|'storage'};
type TrashEntry={entry:DraftEntry;deletedAt:string};
const trashKey='dromex.draft.trash.v1';

export function DraftCenterScreen({repository,onBack,onContinue}:{repository:LoadRepository;onBack:()=>void;onContinue:(route:DraftRoute,projectId:string|null)=>void}){
  const[drafts,setDrafts]=useState<DraftEntry[]>([]);const[trash,setTrash]=useState<TrashEntry[]>([]);const[trashOpen,setTrashOpen]=useState(false);const[error,setError]=useState<string|null>(null);const[message,setMessage]=useState<string|null>(null);
  const refresh=useCallback(async()=>{const[load,keys,trashValue]=await Promise.all([repository.getDraft(),Storage.getAllKeys(),Storage.getItem(trashKey)]);const next:DraftEntry[]=[];if(load&&isMeaningfulLoadDraft(load))next.push({id:'load-current',key:'current',type:'Receipt',title:'Outgoing load draft',detail:load.projectId?'Project selected · continue weighing and review':'Customer, load, and weighing workflow',route:'receipt',projectId:load.projectId||null,payload:load,source:'load'});for(const key of keys.filter(value=>value.startsWith('dromex.draft.')&&value!==trashKey)){const value=await Storage.getItem(key);if(!value)continue;try{const payload=JSON.parse(value) as Record<string,unknown>;const entry=entryFromStorage(key,payload);if(entry)next.push(entry);}catch{}}setDrafts(next);try{setTrash(trashValue?JSON.parse(trashValue) as TrashEntry[]:[]);}catch{setTrash([]);}},[repository]);useEffect(()=>{void refresh().catch(cause=>setError(cause instanceof Error?cause.message:'Draft Center could not be loaded.'));},[refresh]);
  async function move(entry:DraftEntry){const next=[{entry,deletedAt:new Date().toISOString()},...trash].slice(0,50);await Storage.setItem(trashKey,JSON.stringify(next));if(entry.source==='load')await repository.clearDraft();else await Storage.removeItem(entry.key);await refresh();setMessage(`${entry.type} draft moved to Trash.`);}
  async function restore(item:TrashEntry){if(item.entry.source==='load')await repository.saveDraft(item.entry.payload as LoadDraft);else await Storage.setItem(item.entry.key,JSON.stringify(item.entry.payload));const next=trash.filter(value=>value!==item);await Storage.setItem(trashKey,JSON.stringify(next));await refresh();setMessage(`${item.entry.type} draft restored.`);}
  function confirmMove(entry:DraftEntry){Alert.alert('Move draft to Trash?',`${entry.title} can be restored later from this Draft Center.`,[{text:'Keep draft',style:'cancel'},{text:'Move to Trash',style:'destructive',onPress:()=>void move(entry).catch(cause=>setError(cause instanceof Error?cause.message:'Could not move the draft.'))}]);}
  return <AppPage><PageHeader eyebrow="UNFINISHED WORK" title="Draft Center" onBack={onBack}/><View style={styles.hero}><Text style={styles.heroEyebrow}>AUTOSAVE IS VISIBLE</Text><Text style={styles.heroTitle}>{drafts.length} active draft{drafts.length===1?'':'s'}</Text><Text style={styles.heroHint}>Continue unfinished work from one place. Moving a draft to Trash never affects a confirmed record.</Text></View>{error?<Feedback kind="error">{error}</Feedback>:null}{message?<Feedback kind="success">{message}</Feedback>:null}{drafts.length?drafts.map((entry,index)=><View key={entry.id} style={[styles.card,index%2===1&&styles.cardCream]}><View style={styles.row}><View style={styles.number}><Text style={styles.numberText}>{String(index+1).padStart(2,'0')}</Text></View><View style={styles.flex}><Text style={styles.type}>{entry.type.toUpperCase()}</Text><Text style={styles.title}>{entry.title}</Text><Text style={styles.detail}>{entry.detail}</Text></View></View><View style={styles.actions}><TouchableOpacity style={styles.continue} onPress={()=>onContinue(entry.route,entry.projectId)}><Text style={styles.continueText}>Continue</Text></TouchableOpacity><TouchableOpacity style={styles.trash} onPress={()=>confirmMove(entry)}><Text style={styles.trashText}>Move to Trash</Text></TouchableOpacity></View></View>):<EmptyState title="No active drafts" body="Autosaved receipt, report, quarry, fuel, and Quick Text work will appear here when it contains entered information."/>}<ExpandableMenuSection title="Trash" hint={`${trash.length} recoverable draft${trash.length===1?'':'s'}.`} tone="cream" open={trashOpen} onToggle={()=>setTrashOpen(value=>!value)}>{trash.length?trash.map(item=><View key={`${item.entry.id}-${item.deletedAt}`} style={styles.trashCard}><View style={styles.flex}><Text style={styles.title}>{item.entry.title}</Text><Text style={styles.detail}>Moved {new Date(item.deletedAt).toLocaleString()}</Text></View><TouchableOpacity onPress={()=>void restore(item).catch(cause=>setError(cause instanceof Error?cause.message:'Could not restore the draft.'))}><Text style={styles.restore}>Restore</Text></TouchableOpacity></View>):<Text style={styles.detail}>Trash is empty.</Text>}</ExpandableMenuSection></AppPage>;
}

function entryFromStorage(key:string,payload:Record<string,unknown>):DraftEntry|null{
  if(!isMeaningfulStoredDraft(key,payload))return null;
  if(key==='dromex.draft.quarry.v1')return{id:key,key,type:'Quarry Purchase',title:'Incoming material draft',detail:'Supplier, project, item, transport, and pricing',route:'quarry',projectId:String(payload.projectId??'')||null,payload,source:'storage'};
  if(key==='dromex.draft.quick-text.v1')return{id:key,key,type:'Quick Text',title:String(payload.title||'Company document draft'),detail:String(payload.message||'Printable 58/80 mm document').slice(0,90),route:'quickText',projectId:String(payload.projectId??'')||null,payload,source:'storage'};
  if(key==='dromex.draft.fuel.v1'){const activeTab=String(payload.tab??'history');const active=(payload[activeTab]??{}) as Record<string,unknown>;return{id:key,key,type:'Fuel',title:activeTab==='fill'?'Equipment fill draft':activeTab==='delivery'?'Fuel delivery draft':'Gauge reading draft',detail:'Tank-ledger movement saved locally',route:'fuel',projectId:String(active.projectId??'')||null,payload,source:'storage'};}
  if(key.startsWith('dromex.draft.daily-report.')){const projectId=String(payload.projectId??key.split('.')[3]??'');return{id:key,key,type:'Daily Report',title:'Daily project report draft',detail:String(payload.workDescription||'Work, people, materials, time, and photos').slice(0,90),route:'dailyReport',projectId:projectId||null,payload,source:'storage'};}
  return null;
}
const styles=StyleSheet.create({hero:{backgroundColor:colors.navy,borderRadius:17,padding:17,gap:4},heroEyebrow:{color:'#F2A184',fontSize:9,fontWeight:'900',letterSpacing:1},heroTitle:{color:'#FFF8ED',fontSize:23,fontWeight:'900'},heroHint:{color:'#D5E4EF',fontSize:11,lineHeight:16},card:{backgroundColor:colors.surface,borderRadius:15,padding:15,gap:12,borderLeftWidth:4,borderLeftColor:colors.navy},cardCream:{backgroundColor:'#FFF8ED',borderLeftColor:colors.brand},row:{flexDirection:'row',gap:11},number:{width:34,height:34,borderRadius:17,backgroundColor:colors.brand,alignItems:'center',justifyContent:'center'},numberText:{color:'#FFF',fontSize:9,fontWeight:'900'},flex:{flex:1,minWidth:0},type:{color:colors.brand,fontSize:8,fontWeight:'900',letterSpacing:.8},title:{color:colors.ink,fontSize:15,fontWeight:'900',marginTop:2},detail:{color:colors.muted,fontSize:11,lineHeight:16,marginTop:3},actions:{flexDirection:'row',gap:8},continue:{flex:1,backgroundColor:colors.navy,borderRadius:10,padding:11,alignItems:'center'},continueText:{color:'#FFF',fontWeight:'900'},trash:{flex:1,borderWidth:1,borderColor:colors.danger,borderRadius:10,padding:11,alignItems:'center'},trashText:{color:colors.danger,fontWeight:'900'},trashCard:{backgroundColor:colors.surface,borderRadius:12,padding:13,flexDirection:'row',alignItems:'center',gap:10},restore:{color:colors.brand,fontWeight:'900'}});
