import { useCallback, useEffect, useState } from 'react';
import { ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';

import type { LoadRepository } from '../../data/repositories/LoadRepository';
import type { LoadSetupOptions } from '../../domain/loads';
import { colors } from '../theme';

export function DriversTrucksScreen({ repository, onBack }: { repository: LoadRepository; onBack: () => void }) {
  const [options, setOptions] = useState<LoadSetupOptions | null>(null); const [tab, setTab] = useState<'drivers' | 'trucks'>('drivers');
  const [name, setName] = useState(''); const [phone, setPhone] = useState(''); const [license, setLicense] = useState(''); const [driverNotes, setDriverNotes] = useState('');
  const [plate, setPlate] = useState(''); const [makeModel, setMakeModel] = useState(''); const [capacity, setCapacity] = useState(''); const [owner, setOwner] = useState(''); const [truckNotes, setTruckNotes] = useState('');
  const [error, setError] = useState<string | null>(null); const [message, setMessage] = useState<string | null>(null); const [busy, setBusy] = useState(false);
  const refresh = useCallback(async () => setOptions(await repository.getSetupOptions()), [repository]); useEffect(() => { void refresh(); }, [refresh]);
  async function saveDriver() { setBusy(true); setError(null); setMessage(null); try { await repository.createDriver({ name, phone, licenseNumber: license, notes: driverNotes }); setName(''); setPhone(''); setLicense(''); setDriverNotes(''); await refresh(); setMessage('Driver saved and available in Make Receipt.'); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Could not save driver.'); } finally { setBusy(false); } }
  async function saveTruck() { setBusy(true); setError(null); setMessage(null); try { await repository.createTruck({ plate, makeModel, capacityKg: capacity.trim() ? Number(capacity) : null, ownerName: owner, notes: truckNotes }); setPlate(''); setMakeModel(''); setCapacity(''); setOwner(''); setTruckNotes(''); await refresh(); setMessage('Truck saved and available in Make Receipt.'); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Could not save truck.'); } finally { setBusy(false); } }
  return <ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><View style={styles.header}><TouchableOpacity style={styles.back} onPress={onBack}><Text style={styles.backText}>Back</Text></TouchableOpacity><View><Text style={styles.eyebrow}>DIRECTORY</Text><Text style={styles.title}>Drivers & trucks</Text></View></View><Text style={styles.helper}>Create reusable records once, then select them from searchable dropdowns in every load.</Text>{error ? <Text style={styles.error}>{error}</Text> : null}{message ? <Text style={styles.success}>{message}</Text> : null}<View style={styles.tabs}><Tab label="Drivers" selected={tab === 'drivers'} onPress={() => setTab('drivers')} /><Tab label="Trucks" selected={tab === 'trucks'} onPress={() => setTab('trucks')} /></View>{tab === 'drivers' ? <><View style={styles.card}><Text style={styles.cardTitle}>Add driver</Text><Field label="Driver name *" value={name} onChangeText={setName} /><Field label="Phone" value={phone} onChangeText={setPhone} keyboardType="phone-pad" /><Field label="Licence number" value={license} onChangeText={setLicense} /><Field label="Notes" value={driverNotes} onChangeText={setDriverNotes} multiline /><Save label="Save driver" busy={busy} onPress={() => void saveDriver()} /></View><Text style={styles.sectionTitle}>Saved drivers ({options?.drivers.length ?? 0})</Text>{options?.drivers.map((driver) => <View key={driver.id} style={styles.record}><Text style={styles.recordTitle}>{driver.name}</Text><Text style={styles.helper}>{[driver.phone, driver.licenseNumber ? `Licence ${driver.licenseNumber}` : null].filter(Boolean).join(' · ') || 'No additional information'}</Text>{driver.notes ? <Text style={styles.notes}>{driver.notes}</Text> : null}</View>)}</> : <><View style={styles.card}><Text style={styles.cardTitle}>Add truck</Text><Field label="Number plate *" value={plate} onChangeText={setPlate} autoCapitalize="characters" /><Field label="Make / model" value={makeModel} onChangeText={setMakeModel} /><Field label="Capacity kg" value={capacity} onChangeText={setCapacity} keyboardType="number-pad" /><Field label="Owner / company" value={owner} onChangeText={setOwner} /><Field label="Notes" value={truckNotes} onChangeText={setTruckNotes} multiline /><Save label="Save truck" busy={busy} onPress={() => void saveTruck()} /></View><Text style={styles.sectionTitle}>Saved trucks ({options?.trucks.length ?? 0})</Text>{options?.trucks.map((truck) => <View key={truck.id} style={styles.record}><Text style={styles.recordTitle}>{truck.plate}</Text><Text style={styles.helper}>{[truck.makeModel, truck.capacityKg ? `${truck.capacityKg} kg capacity` : null, truck.ownerName].filter(Boolean).join(' · ') || 'No additional information'}</Text>{truck.notes ? <Text style={styles.notes}>{truck.notes}</Text> : null}</View>)}</>}</ScrollView>;
}
function Tab({ label, selected, onPress }: { label: string; selected: boolean; onPress: () => void }) { return <TouchableOpacity style={[styles.tab, selected && styles.tabSelected]} onPress={onPress}><Text style={[styles.tabText, selected && styles.tabTextSelected]}>{label}</Text></TouchableOpacity>; }
function Field({ label, ...props }: { label: string; value: string; onChangeText: (value: string) => void; multiline?: boolean; keyboardType?: 'default' | 'phone-pad' | 'number-pad'; autoCapitalize?: 'none' | 'sentences' | 'characters' }) { return <View style={styles.field}><Text style={styles.label}>{label}</Text><TextInput style={[styles.input, props.multiline && styles.multiline]} placeholderTextColor="#89939B" {...props} /></View>; }
function Save({ label, busy, onPress }: { label: string; busy: boolean; onPress: () => void }) { return <TouchableOpacity style={styles.save} disabled={busy} onPress={onPress}><Text style={styles.saveText}>{busy ? 'Saving…' : label}</Text></TouchableOpacity>; }
const styles = StyleSheet.create({ content: { padding: 20, paddingBottom: 42, gap: 15 }, header: { flexDirection: 'row', alignItems: 'center', gap: 14 }, back: { backgroundColor: colors.surface, padding: 10, borderRadius: 10 }, backText: { color: colors.ink, fontWeight: '800' }, eyebrow: { color: colors.brand, fontSize: 11, fontWeight: '900', letterSpacing: 1.4 }, title: { color: colors.ink, fontSize: 27, fontWeight: '900' }, helper: { color: colors.muted, fontSize: 12, lineHeight: 18 }, error: { color: colors.danger, backgroundColor: '#FCE8E6', padding: 12, borderRadius: 10 }, success: { color: colors.success, backgroundColor: '#E5F3EC', padding: 12, borderRadius: 10, fontWeight: '700' }, tabs: { flexDirection: 'row', gap: 8 }, tab: { flex: 1, borderWidth: 1, borderColor: colors.line, padding: 11, borderRadius: 10, alignItems: 'center', backgroundColor: colors.surface }, tabSelected: { borderColor: colors.brand, backgroundColor: '#FBE9E4' }, tabText: { color: colors.muted, fontWeight: '800' }, tabTextSelected: { color: colors.brandDark }, card: { backgroundColor: colors.surface, borderRadius: 16, padding: 17, gap: 12 }, cardTitle: { color: colors.ink, fontSize: 19, fontWeight: '900' }, field: { gap: 6 }, label: { color: colors.ink, fontSize: 13, fontWeight: '800' }, input: { borderWidth: 1, borderColor: colors.line, borderRadius: 11, paddingHorizontal: 13, paddingVertical: 11, color: colors.ink, backgroundColor: '#FCFBF8' }, multiline: { minHeight: 70, textAlignVertical: 'top' }, save: { backgroundColor: colors.ink, borderRadius: 11, padding: 14, alignItems: 'center' }, saveText: { color: '#FFF', fontWeight: '900' }, sectionTitle: { color: colors.ink, fontSize: 18, fontWeight: '900' }, record: { backgroundColor: colors.surface, borderRadius: 13, padding: 14, gap: 3 }, recordTitle: { color: colors.ink, fontSize: 16, fontWeight: '900' }, notes: { color: colors.muted, fontSize: 12, fontStyle: 'italic', marginTop: 3 } });
