import {useCallback,useEffect,useMemo,useState} from 'react';
import {Alert,StyleSheet,Text,TouchableOpacity,View} from 'react-native';
import Storage from 'expo-sqlite/kv-store';
import type {FuelRepository} from '../../data/repositories/FuelRepository';
import {emptyFuelDelivery,emptyFuelFill,emptyFuelGauge,filterFuelMovements,groupProjectFuelByEquipment,type FuelDeliveryDraft,type FuelFillDraft,type FuelGaugeDraft,type FuelMovement,type FuelMovementStatus,type FuelMovementType,type FuelOverview,type FuelSetup} from '../../domain/fuel';
import {AppButton,AppCard,AppField,AppPage,EmptyState,Feedback,MetricCard,PageHeader} from '../components/AppPrimitives';
import {CollapsibleFilterCard} from '../components/CollapsibleFilterCard';
import {DatePickerField,todayIso} from '../components/DatePickerField';
import {SearchableSelect} from '../components/SearchableSelect';
import {colors} from '../theme';
type Tab='history'|'delivery'|'fill'|'gauge';
export function FuelTrackingScreen({repository,onBack,initialProjectId,lockedProjectId,initialTab}:{repository:FuelRepository;onBack:()=>void;initialProjectId?:string|null;lockedProjectId?:string|null;initialTab?:'delivery'|'fill'}){const[setup,setSetup]=useState<FuelSetup|null>(null),[overview,setOverview]=useState<FuelOverview|null>(null),[tab,setTab]=useState<Tab>(initialTab??'history'),[delivery,setDelivery]=useState<FuelDeliveryDraft>(emptyFuelDelivery),[fill,setFill]=useState<FuelFillDraft>({...emptyFuelFill,projectId:initialProjectId??''}),[gauge,setGauge]=useState<FuelGaugeDraft>(emptyFuelGauge),[selected,setSelected]=useState<FuelMovement|null>(null),[openEquipment,setOpenEquipment]=useState<Set<string>>(new Set()),[projectFilter,setProjectFilter]=useState(''),[equipmentFilter,setEquipmentFilter]=useState(''),[typeFilter,setTypeFilter]=useState<FuelMovementType|'all'>('all'),[statusFilter,setStatusFilter]=useState<FuelMovementStatus|'all'>('all'),[fromDate,setFromDate]=useState(''),[toDate,setToDate]=useState(''),[cancelReason,setCancelReason]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null),[message,setMessage]=useState<string|null>(null);
const refresh=useCallback(async()=>{const[s,o]=await Promise.all([repository.getSetup(),repository.getOverview()]);setSetup(s);setOverview(o);},[repository]);useEffect(()=>{void refresh().catch(c=>setError(c instanceof Error?c.message:'Could not load fuel tracking.'));},[refresh]);
useEffect(()=>{void Storage.getItem('dromex.draft.fuel.v1').then(value=>{if(!value){if(initialTab)setTab(initialTab);return;}try{const saved=JSON.parse(value) as {delivery?:Partial<FuelDeliveryDraft>;fill?:Partial<FuelFillDraft>;gauge?:Partial<FuelGaugeDraft>;tab?:Tab};setDelivery({...emptyFuelDelivery,...saved.delivery});setFill(current=>({...emptyFuelFill,...saved.fill,projectId:String(lockedProjectId||saved.fill?.projectId||current.projectId||initialProjectId||'')}));setGauge({...emptyFuelGauge,...saved.gauge});if(initialTab)setTab(initialTab);else if(saved.tab&&saved.tab!=='history')setTab(saved.tab);}catch{}});},[initialProjectId,initialTab,lockedProjectId]);
useEffect(()=>{const timer=setTimeout(()=>void Storage.setItem('dromex.draft.fuel.v1',JSON.stringify({delivery,fill,gauge,tab})),450);return()=>clearTimeout(timer);},[delivery,fill,gauge,tab]);
const run=async(action:()=>Promise<unknown>,success:string,clearDraft=true)=>{setBusy(true);setError(null);setMessage(null);try{await action();if(clearDraft)await Storage.removeItem('dromex.draft.fuel.v1');await refresh();setMessage(success);setTab('history');setSelected(null);}catch(c){setError(c instanceof Error?c.message:'The fuel record could not be saved.');}finally{setBusy(false);}};
const projectFills=useMemo(()=>overview&&lockedProjectId?overview.movements.filter(value=>value.type==='fill'&&value.status==='Active'&&value.projectId===lockedProjectId):[],[lockedProjectId,overview]);
const equipmentUsage=useMemo(()=>overview&&lockedProjectId?groupProjectFuelByEquipment(overview.movements,lockedProjectId):[],[lockedProjectId,overview]);
const projectName=setup?.projects.find(value=>value.id===lockedProjectId)?.name??projectFills[0]?.projectName??'Selected project';
const projectIsActive=Boolean(setup?.projects.some(value=>value.id===lockedProjectId));
const historyMovements=useMemo(()=>overview?filterFuelMovements(overview.movements,{projectId:projectFilter,equipmentId:equipmentFilter,type:typeFilter,status:statusFilter,fromDate,toDate}):[],[equipmentFilter,fromDate,overview,projectFilter,statusFilter,toDate,typeFilter]);
const projectOptions=useMemo(()=>{const values=new Map<string,string>();overview?.movements.forEach(value=>{if(value.projectId&&value.projectName)values.set(value.projectId,value.projectName);});setup?.projects.forEach(value=>values.set(value.id,value.name));return [...values].map(([id,label])=>({id,label})).sort((a,b)=>a.label.localeCompare(b.label));},[overview,setup]);
const equipmentOptions=useMemo(()=>{const values=new Map<string,{id:string;label:string;detail?:string}>();setup?.equipment.forEach(value=>values.set(value.id,{id:value.id,label:value.name,detail:value.detail}));overview?.movements.forEach(value=>{if(value.equipmentId&&value.equipmentName&&(!projectFilter||value.projectId===projectFilter))values.set(value.equipmentId,{id:value.equipmentId,label:value.equipmentName});});return [...values.values()].filter(value=>!projectFilter||overview?.movements.some(movement=>movement.projectId===projectFilter&&movement.equipmentId===value.id)).sort((a,b)=>a.label.localeCompare(b.label));},[overview,projectFilter,setup]);
const clearFilters=()=>{setProjectFilter('');setEquipmentFilter('');setTypeFilter('all');setStatusFilter('all');setFromDate('');setToDate('');};
useEffect(()=>{if(lockedProjectId&&!projectIsActive&&setup)setTab('history');},[lockedProjectId,projectIsActive,setup]);
useEffect(()=>{if(equipmentFilter&&!equipmentOptions.some(value=>value.id===equipmentFilter))setEquipmentFilter('');},[equipmentFilter,equipmentOptions]);
if(!setup||!overview)return <View style={styles.loading}><Text>Loading fuel tracking...</Text></View>;
if(selected)return <AppPage keyboard><PageHeader eyebrow="FUEL MOVEMENT" title={movementTitle(selected)} onBack={()=>setSelected(null)}/>{error?<Feedback kind="error">{error}</Feedback>:null}<AppCard title={`${selected.litres.toFixed(2)} L`} hint={`${new Date(selected.confirmedAt).toLocaleString()} · ${selected.status}`}><Detail label="Balance after" value={`${selected.balanceAfterLitres.toFixed(2)} L`}/><Detail label="Supplier / equipment" value={selected.supplierName??selected.equipmentName??'Physical tank gauge'}/>{selected.projectName?<Detail label="Project" value={selected.projectName}/>:null}{selected.ticketNumber?<Detail label="Ticket" value={selected.ticketNumber}/>:null}{selected.reason?<Detail label="Reason" value={selected.reason}/>:null}{selected.finalTotalUsd!=null?<Detail label="Total / status" value={`$${selected.finalTotalUsd.toFixed(2)} · ${selected.paymentStatus}`}/>:null}{selected.notes?<Detail label="Notes" value={selected.notes}/>:null}{selected.status==='Cancelled'?<Feedback kind="warning">Cancelled: {selected.cancellationReason}</Feedback>:<><AppField label="Cancellation reason *" value={cancelReason} onChangeText={setCancelReason} multiline/><AppButton label="Cancel Fuel Movement" tone="danger" busy={busy} onPress={()=>Alert.alert('Cancel fuel movement?','The record stays in history and its stock effect is recalculated.',[{text:'Keep record',style:'cancel'},{text:'Cancel movement',style:'destructive',onPress:()=>void run(()=>repository.cancelMovement(selected.id,cancelReason),'Fuel movement cancelled.',false)}])}/></>}</AppCard></AppPage>;
const visibleTabs:Tab[]=lockedProjectId?(projectIsActive?['history','fill']:['history']):['history','delivery','fill','gauge'];
return <AppPage keyboard>
  <PageHeader eyebrow={lockedProjectId?'PROJECT COMMAND CENTER · FUEL':'SLICE 7 · DAILY OPERATIONS'} title={lockedProjectId?`${projectName} Fuel`:'Fuel Tracking'} onBack={onBack}/>
  <Text style={styles.helper}>{lockedProjectId?'Only active equipment fills recorded for this project are shown here, organized by equipment.':'One tank and one fuel type. Deliveries add litres, equipment fills subtract litres, and physical readings reset the calculated baseline.'}</Text>
  {error?<Feedback kind="error">{error}</Feedback>:null}{message?<Feedback kind="success">{message}</Feedback>:null}
  {lockedProjectId?<View style={styles.metrics}><MetricCard label="Project fuel used" value={`${projectFills.reduce((sum,value)=>sum+value.litres,0).toFixed(2)} L`} accent/><MetricCard label="Equipment / fills" value={`${equipmentUsage.length} / ${projectFills.length}`}/></View>:<><View style={styles.metrics}><MetricCard label="Current calculated balance" value={`${overview.currentBalanceLitres.toFixed(2)} L`} accent/><MetricCard label="Active movements" value={String(overview.movements.filter(v=>v.status==='Active').length)}/></View>{overview.latestGauge?<Feedback kind="warning">Latest physical reading: {overview.latestGauge.litres.toFixed(2)} L on {new Date(overview.latestGauge.confirmedAt).toLocaleDateString()}.</Feedback>:<Feedback kind="warning">Enter the physical tank reading before relying on the calculated balance.</Feedback>}</>}
  <View style={styles.tabs}>{visibleTabs.map(value=><TouchableOpacity key={value} style={[styles.tab,tab===value&&styles.tabActive]} onPress={()=>{setTab(value);setError(null);setMessage(null);}}><Text style={[styles.tabText,tab===value&&styles.tabTextActive]}>{value==='history'?(lockedProjectId?'Project Usage':'History'):value==='delivery'?'Delivery':value==='fill'?'Equipment Fill':'Gauge'}</Text></TouchableOpacity>)}</View>
  {tab==='delivery'?<AppCard title="Record fuel delivery" hint={`Optional pricing uses the current ${setup.vatRatePercent.toFixed(2)}% VAT setting and appears in Supplier Payments & Balances.`}><AppField label="Litres delivered *" value={delivery.litres} onChangeText={v=>setDelivery({...delivery,litres:v})} keyboardType="decimal-pad"/><SearchableSelect label="Supplier (optional)" options={setup.suppliers.map(v=>({id:v.id,label:v.name,detail:v.detail}))} selectedId={delivery.supplierId} onSelect={v=>setDelivery({...delivery,supplierId:v})} allowClear/><AppField label="Ticket / invoice number" value={delivery.ticketNumber} onChangeText={v=>setDelivery({...delivery,ticketNumber:v})}/><AppField label="USD price per litre" value={delivery.pricePerLitreUsd} onChangeText={v=>setDelivery({...delivery,pricePerLitreUsd:v})} keyboardType="decimal-pad"/><AppField label="Notes" value={delivery.notes} onChangeText={v=>setDelivery({...delivery,notes:v})} multiline/><AppButton label="Save Fuel Delivery" busy={busy} onPress={()=>void run(async()=>{await repository.recordDelivery(delivery);setDelivery(emptyFuelDelivery);},'Fuel delivery saved.')}/></AppCard>:null}
  {tab==='fill'?<AppCard title="Record equipment fill" hint={lockedProjectId?`This fill will be saved only under ${projectName}.`:'A fill may exceed the calculated balance; the app records the observed operation without blocking it.'}><SearchableSelect label="Equipment *" options={setup.equipment.map(v=>({id:v.id,label:v.name,detail:v.detail}))} selectedId={fill.equipmentId} onSelect={v=>setFill({...fill,equipmentId:v})}/><AppField label="Litres filled *" value={fill.litres} onChangeText={v=>setFill({...fill,litres:v})} keyboardType="decimal-pad"/>{lockedProjectId?<Detail label="Project (locked)" value={projectName}/>:<SearchableSelect label="Project (optional)" options={setup.projects.map(v=>({id:v.id,label:v.name,detail:v.detail}))} selectedId={fill.projectId} onSelect={v=>setFill({...fill,projectId:v})} allowClear/>}<AppField label="Odometer (reference only)" value={fill.odometerReading} onChangeText={v=>setFill({...fill,odometerReading:v})}/><AppField label="Notes" value={fill.notes} onChangeText={v=>setFill({...fill,notes:v})} multiline/><AppButton label="Save Equipment Fill" tone="navy" busy={busy} onPress={()=>void run(async()=>{await repository.recordFill({...fill,projectId:lockedProjectId??fill.projectId});setFill({...emptyFuelFill,projectId:lockedProjectId??''});},'Equipment fill saved.')}/></AppCard>:null}
  {tab==='gauge'?<AppCard title="Physical tank reading" hint="This becomes the new balance baseline. The prior calculated balance and signed difference remain in history."><AppField label="Actual gauge litres *" value={gauge.actualLitres} onChangeText={v=>setGauge({...gauge,actualLitres:v})} keyboardType="decimal-pad"/><AppField label="Reason *" value={gauge.reason} onChangeText={v=>setGauge({...gauge,reason:v})} multiline/><AppField label="Notes" value={gauge.notes} onChangeText={v=>setGauge({...gauge,notes:v})} multiline/><AppButton label="Save Physical Reading" tone="navy" busy={busy} onPress={()=>void run(async()=>{await repository.recordGauge(gauge);setGauge(emptyFuelGauge);},'Physical reading saved.')}/></AppCard>:null}
  {tab==='history'&&lockedProjectId?<><Text style={styles.sectionTitle}>Fuel used by equipment</Text>{equipmentUsage.length?equipmentUsage.map(group=>{const key=group.equipmentId??group.equipmentName,isOpen=openEquipment.has(key);return <View key={key} style={styles.equipmentGroup}><TouchableOpacity style={styles.equipmentHeader} onPress={()=>setOpenEquipment(current=>{const next=new Set(current);if(next.has(key))next.delete(key);else next.add(key);return next;})}><View style={styles.flex}><Text style={styles.recordTitle}>{group.equipmentName}</Text><Text style={styles.helper}>{group.fillCount} fill{group.fillCount===1?'':'s'}</Text></View><Text style={styles.equipmentTotal}>{group.totalLitres.toFixed(2)} L</Text><Text style={styles.fold}>{isOpen?'×':'+'}</Text></TouchableOpacity>{isOpen?group.fills.map(m=><TouchableOpacity key={m.id} style={styles.projectFill} onPress={()=>{setSelected(m);setCancelReason('');}}><View style={styles.row}><View style={styles.flex}><Text style={styles.fillDate}>{new Date(m.confirmedAt).toLocaleString()}</Text><Text style={styles.helper}>{[m.odometerReading?`Odometer ${m.odometerReading}`:null,m.notes].filter(Boolean).join(' · ')||'No additional notes'}</Text></View><Text style={styles.equipmentTotal}>{m.litres.toFixed(2)} L</Text></View></TouchableOpacity>):null}</View>}):<EmptyState title="No project fuel usage" body="Record an equipment fill from this project to see it grouped here."/>}</>:null}
  {tab==='history'&&!lockedProjectId?<><CollapsibleFilterCard title="Filter fuel history" summary={`${historyMovements.length} matching record${historyMovements.length===1?'':'s'}`}><View style={styles.filterTop}><Text style={styles.helper}>Narrow the complete fuel ledger without changing it.</Text><TouchableOpacity onPress={clearFilters}><Text style={styles.clear}>Clear filters</Text></TouchableOpacity></View><SearchableSelect label="Project" options={projectOptions} selectedId={projectFilter} onSelect={setProjectFilter} placeholder="All projects" allowClear/><SearchableSelect label="Equipment" options={equipmentOptions} selectedId={equipmentFilter} onSelect={setEquipmentFilter} placeholder="All equipment" allowClear/><Text style={styles.filterLabel}>Movement type</Text><View style={styles.chips}>{(['all','delivery','fill','gauge'] as const).map(value=><FilterChip key={value} label={value==='all'?'All':value==='delivery'?'Deliveries':value==='fill'?'Equipment Fills':'Gauge Readings'} selected={typeFilter===value} onPress={()=>setTypeFilter(value)}/>)}</View><Text style={styles.filterLabel}>Record status</Text><View style={styles.chips}>{(['all','Active','Cancelled'] as const).map(value=><FilterChip key={value} label={value} selected={statusFilter===value} onPress={()=>setStatusFilter(value)}/>)}</View><View style={styles.dateRow}><View style={styles.flex}><DatePickerField label="From date" value={fromDate} onChange={setFromDate} maxDate={toDate||todayIso()} allowClear/></View><View style={styles.flex}><DatePickerField label="To date" value={toDate} onChange={setToDate} minDate={fromDate||undefined} maxDate={todayIso()} allowClear/></View></View></CollapsibleFilterCard><Text style={styles.sectionTitle}>Movement history · {historyMovements.length}</Text>{historyMovements.length?historyMovements.map(m=><TouchableOpacity key={m.id} style={[styles.record,m.status==='Cancelled'&&styles.cancelled]} onPress={()=>{setSelected(m);setCancelReason('');}}><View style={styles.row}><View style={styles.flex}><Text style={styles.recordTitle}>{movementTitle(m)}</Text><Text style={styles.helper}>{new Date(m.confirmedAt).toLocaleString()} · {m.supplierName??m.equipmentName??'Physical gauge'}{m.projectName?` · ${m.projectName}`:''}</Text></View><Text style={[styles.amount,m.type==='fill'&&styles.negative]}>{m.type==='fill'?'-':m.type==='delivery'?'+':'='}{m.litres.toFixed(2)} L</Text></View><Text style={styles.balance}>Balance after: {m.balanceAfterLitres.toFixed(2)} L · {m.status}</Text></TouchableOpacity>):<EmptyState title={overview.movements.length?'No matching fuel movements':'No fuel movements'} body={overview.movements.length?'Change or clear one of the filters.':'Start with the physical tank reading, then record each delivery and equipment fill.'}/>}</>:null}
</AppPage>}
function movementTitle(v:FuelMovement){return v.type==='delivery'?'Fuel delivery':v.type==='fill'?'Equipment fill':'Physical gauge reading';}function Detail({label,value}:{label:string;value:string}){return <View style={styles.detail}><Text style={styles.detailLabel}>{label}</Text><Text style={styles.detailValue}>{value}</Text></View>}function FilterChip({label,selected,onPress}:{label:string;selected:boolean;onPress:()=>void}){return <TouchableOpacity style={[styles.chip,selected&&styles.chipOn]} onPress={onPress}><Text style={[styles.chipText,selected&&styles.chipTextOn]}>{label}</Text></TouchableOpacity>}
const styles=StyleSheet.create({loading:{flex:1,alignItems:'center',justifyContent:'center'},helper:{color:colors.muted,fontSize:13,lineHeight:19},metrics:{flexDirection:'row',flexWrap:'wrap',gap:10},tabs:{flexDirection:'row',flexWrap:'wrap',gap:8},tab:{paddingHorizontal:12,paddingVertical:10,borderRadius:18,borderWidth:1,borderColor:colors.line,backgroundColor:colors.surface},tabActive:{backgroundColor:colors.navy,borderColor:colors.navy},tabText:{color:colors.muted,fontWeight:'800',fontSize:12},tabTextActive:{color:'#FFF'},sectionTitle:{color:colors.ink,fontSize:19,fontWeight:'900'},record:{backgroundColor:colors.surface,borderRadius:14,padding:15,gap:5,borderLeftWidth:3,borderLeftColor:colors.brand},cancelled:{opacity:.65,borderLeftColor:colors.danger},row:{flexDirection:'row',gap:10,alignItems:'flex-start'},flex:{flex:1,minWidth:0},recordTitle:{color:colors.ink,fontSize:16,fontWeight:'900'},amount:{color:colors.success,fontWeight:'900'},negative:{color:colors.danger},balance:{color:colors.navy,fontWeight:'800',fontSize:12},filterTop:{flexDirection:'row',alignItems:'center',gap:10},clear:{color:colors.brandDark,fontWeight:'900'},filterLabel:{color:colors.ink,fontSize:13,fontWeight:'800'},chips:{flexDirection:'row',flexWrap:'wrap',gap:8},chip:{borderWidth:1,borderColor:colors.line,backgroundColor:colors.surface,borderRadius:18,paddingHorizontal:12,paddingVertical:9},chipOn:{backgroundColor:colors.navy,borderColor:colors.navy},chipText:{color:colors.muted,fontSize:12,fontWeight:'800'},chipTextOn:{color:'#FFF'},dateRow:{flexDirection:'row',gap:10},equipmentGroup:{backgroundColor:colors.surface,borderRadius:14,borderWidth:1,borderColor:colors.line,overflow:'hidden'},equipmentHeader:{padding:15,flexDirection:'row',gap:10,alignItems:'center',borderLeftWidth:4,borderLeftColor:colors.brand},equipmentTotal:{color:colors.navy,fontWeight:'900'},fold:{color:colors.brand,fontSize:24,fontWeight:'900',width:24,textAlign:'center'},projectFill:{padding:14,borderTopWidth:StyleSheet.hairlineWidth,borderTopColor:colors.line,backgroundColor:colors.background},fillDate:{color:colors.ink,fontSize:14,fontWeight:'800'},detail:{paddingBottom:9,borderBottomWidth:StyleSheet.hairlineWidth,borderBottomColor:colors.line,gap:3},detailLabel:{color:colors.muted,fontSize:11,fontWeight:'800'},detailValue:{color:colors.ink,fontSize:14,fontWeight:'800'}});
