import {useEffect,useMemo,useState} from 'react';
import {ActivityIndicator,StyleSheet,Text,TextInput,TouchableOpacity,View} from 'react-native';
import type {WorkspaceRepository} from '../../data/repositories/WorkspaceRepository';
import type {GlobalSearchResult} from '../../domain/workspace';
import {AppPage,EmptyState,Feedback,PageHeader} from '../components/AppPrimitives';
import {colors} from '../theme';

export function GlobalSearchScreen({repository,onBack,onOpen}:{repository:WorkspaceRepository;onBack:()=>void;onOpen:(result:GlobalSearchResult)=>void}){
  const[query,setQuery]=useState('');const[results,setResults]=useState<GlobalSearchResult[]>([]);const[loading,setLoading]=useState(false);const[error,setError]=useState<string|null>(null);
  useEffect(()=>{const value=query.trim();if(value.length<2){setResults([]);setLoading(false);return;}let active=true;const timer=setTimeout(()=>{setLoading(true);setError(null);void repository.search(value).then(next=>{if(active)setResults(next);}).catch(cause=>{if(active)setError(cause instanceof Error?cause.message:'Search could not be completed.');}).finally(()=>{if(active)setLoading(false);});},220);return()=>{active=false;clearTimeout(timer);};},[query,repository]);
  const groups=useMemo(()=>{const map=new Map<string,GlobalSearchResult[]>();for(const result of results)map.set(result.kind,[...(map.get(result.kind)??[]),result]);return[...map.entries()];},[results]);
  return <AppPage keyboard><PageHeader eyebrow="FIND ANY RECORD" title="Global Search" onBack={onBack}/><View style={styles.searchBox}><Text style={styles.searchMark}>⌕</Text><TextInput autoFocus value={query} onChangeText={setQuery} style={styles.input} placeholder="Transaction, project, plate, driver, material…" placeholderTextColor="#89939B" returnKeyType="search"/>{query?<TouchableOpacity onPress={()=>setQuery('')}><Text style={styles.clear}>×</Text></TouchableOpacity>:null}</View><Text style={styles.helper}>Search works across loads, customers, projects, drivers, trucks, materials, suppliers, reports, Quick Text, waste, schedules, and payments.</Text>{error?<Feedback kind="error">{error}</Feedback>:null}{loading?<View style={styles.loading}><ActivityIndicator color={colors.brand}/><Text style={styles.helper}>Searching local records…</Text></View>:null}{!loading&&query.trim().length<2?<EmptyState title="Search all DROMEX records" body="Enter at least two characters. A plate or transaction number can be found without opening its history first."/>:null}{!loading&&query.trim().length>=2&&!results.length?<EmptyState title="No matching records" body="Try a project, customer, plate, transaction, person, material, or reference."/>:null}{groups.map(([kind,items],groupIndex)=><View key={kind} style={styles.group}><View style={[styles.groupHeader,groupIndex%2===1&&styles.groupHeaderOrange]}><Text style={styles.groupTitle}>{kind}</Text><Text style={styles.groupCount}>{items.length}</Text></View><View style={styles.groupBody}>{items.map(result=><TouchableOpacity key={`${result.kind}-${result.id}`} style={styles.result} onPress={()=>onOpen(result)}><View style={styles.flex}><Text style={styles.resultTitle}>{result.title}</Text><Text style={styles.resultSub} numberOfLines={2}>{result.subtitle}</Text>{result.date?<Text style={styles.date}>{formatDate(result.date)}</Text>:null}</View><Text style={styles.arrow}>›</Text></TouchableOpacity>)}</View></View>)}</AppPage>;
}
const formatDate=(value:string)=>{const date=new Date(value);return Number.isNaN(date.valueOf())?value:new Date(value).toLocaleString();};
const styles=StyleSheet.create({searchBox:{minHeight:55,backgroundColor:colors.surface,borderWidth:2,borderColor:colors.navy,borderRadius:15,flexDirection:'row',alignItems:'center',paddingHorizontal:13,gap:9},searchMark:{color:colors.brand,fontSize:24,fontWeight:'900'},input:{flex:1,color:colors.ink,fontSize:16,paddingVertical:12},clear:{width:30,textAlign:'center',color:colors.navy,fontSize:25,fontWeight:'700'},helper:{color:colors.muted,fontSize:11,lineHeight:17},loading:{flexDirection:'row',alignItems:'center',justifyContent:'center',gap:10,padding:18},group:{backgroundColor:colors.surface,borderRadius:15,overflow:'hidden'},groupHeader:{backgroundColor:colors.navy,paddingHorizontal:14,paddingVertical:11,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},groupHeaderOrange:{backgroundColor:colors.brand},groupTitle:{color:'#FFF8ED',fontSize:16,fontWeight:'900'},groupCount:{minWidth:28,height:28,borderRadius:14,backgroundColor:'#FFF8ED',color:colors.navy,textAlign:'center',textAlignVertical:'center',paddingTop:5,fontWeight:'900'},groupBody:{borderTopWidth:3,borderTopColor:colors.brand},result:{padding:14,flexDirection:'row',alignItems:'center',gap:10,borderBottomWidth:StyleSheet.hairlineWidth,borderBottomColor:colors.line},flex:{flex:1,minWidth:0},resultTitle:{color:colors.ink,fontSize:15,fontWeight:'900'},resultSub:{color:colors.muted,fontSize:11,lineHeight:16,marginTop:3},date:{color:colors.brandDark,fontSize:9,fontWeight:'800',marginTop:4},arrow:{color:colors.brand,fontSize:27,fontWeight:'900'}});
