import {Children,useEffect,useRef,useState,type ReactNode} from 'react';
import {Animated,Image,LayoutAnimation,Pressable,ScrollView,StyleSheet,Text,View} from 'react-native';
import Storage from 'expo-sqlite/kv-store';
import type {BusinessReportRepository} from '../../data/repositories/BusinessReportRepository';
import type {DashboardRange} from '../../domain/dashboard';
import {DashboardOverview} from '../components/DashboardOverview';
import {colors} from '../theme';

type HomeProps={businessReportRepository:BusinessReportRepository;onMakeReceipt:()=>void;onOpenLoads:(range?:DashboardRange)=>void;onOpenReceiptSetup:()=>void;onOpenDirectory:()=>void;onOpenCustomers:()=>void;onOpenCatalog:()=>void;onOpenReports:(range?:DashboardRange)=>void;onOpenQuarry:()=>void;onOpenProjects:()=>void;onOpenFinancials:(range?:DashboardRange)=>void;onOpenWaste:()=>void;onOpenFuel:()=>void;onOpenQuickText:()=>void;onOpenLoadCorrections:()=>void;onOpenSettings:()=>void};
type SectionKey='daily'|'records'|'finance'|'setup';
type ExpandedSections=Record<SectionKey,boolean>;
const storageKey='dromex.home.expanded-sections.v1';
const defaults:ExpandedSections={daily:true,records:false,finance:false,setup:false};

export function HomeScreen(props:HomeProps){
  const[expanded,setExpanded]=useState<ExpandedSections>(defaults);const entrance=useState(()=>Array.from({length:7},()=>new Animated.Value(0)))[0];
  useEffect(()=>{let active=true;void Storage.getItem(storageKey).then(value=>{if(!active||!value)return;try{const saved=JSON.parse(value) as Partial<ExpandedSections>;setExpanded({...defaults,...saved});}catch{}});Animated.stagger(65,entrance.map(value=>Animated.timing(value,{toValue:1,duration:260,useNativeDriver:true}))).start();return()=>{active=false;};},[entrance]);
  const toggle=(key:SectionKey)=>{LayoutAnimation.configureNext(LayoutAnimation.Presets.easeInEaseOut);setExpanded(current=>{const next={...current,[key]:!current[key]};void Storage.setItem(storageKey,JSON.stringify(next));return next;});};
  const motion=(index:number)=>{const value=entrance[index]!;return{opacity:value,transform:[{translateY:value.interpolate({inputRange:[0,1],outputRange:[14,0]})}]};};
  const date=new Date().toLocaleDateString(undefined,{weekday:'long',day:'numeric',month:'long',year:'numeric'});
  return <ScrollView contentContainerStyle={styles.content}>
    <Animated.View style={[styles.header,motion(0)]}><View style={styles.headerLine}><DromexWordmark/><View style={styles.statusBadge}><View style={styles.statusDot}/><View><Text style={styles.statusText}>Offline ready</Text><Text style={styles.statusHint}>Local records protected</Text></View></View></View><Text style={styles.eyebrow}>PLANT MANAGEMENT</Text><Text style={styles.date}>{date}</Text></Animated.View>
    <Animated.View style={motion(1)}><MotionAction primary onPress={props.onMakeReceipt}><Text style={styles.primaryEyebrow}>NEW OUTGOING LOAD</Text><Text style={styles.primaryActionLabel}>Make Receipt</Text><Text style={styles.primaryActionHint}>Enter the load once, calculate it, preview both documents, and confirm.</Text></MotionAction></Animated.View>
    <Animated.View style={motion(2)}><DashboardOverview repository={props.businessReportRepository} onOpenLoads={props.onOpenLoads} onOpenReports={props.onOpenReports} onOpenFinancials={props.onOpenFinancials} onOpenFuel={props.onOpenFuel} onOpenQuarry={props.onOpenQuarry}/></Animated.View>
    <Animated.View style={motion(3)}><ActionSection title="Daily Operations" hint="Use these while site or plant work is happening." expanded={expanded.daily} onToggle={()=>toggle('daily')}>
      <QuickAction number="01" title="Fuel Tracking" body="Record tank readings, deliveries, equipment fills, supplier cost, and current balance." onPress={props.onOpenFuel}/><QuickAction number="02" title="Waste Dump Tracking" body="Tap once per waste truck, then add material and destination details." onPress={props.onOpenWaste}/><QuickAction number="03" title="Quarry Purchases" body="Connect incoming material to suppliers, projects, items, transport, payments, and Excel." onPress={props.onOpenQuarry} connected/><QuickAction number="04" title="Daily project reports" body="Record work, people, equipment, loads, waste dumps, notes, and photos." onPress={props.onOpenReports}/><QuickAction number="05" title="Quick Text" body="Create full-size company-letterhead documents in 58 or 80 mm." onPress={props.onOpenQuickText}/>
    </ActionSection></Animated.View>
    <Animated.View style={motion(4)}><ActionSection title="Records" hint="Find confirmed work and maintain reusable information." expanded={expanded.records} onToggle={()=>toggle('records')}>
      <QuickAction number="01" title="Load History" body="Open confirmed loads, documents, signatures, payment status, and PDFs." onPress={props.onOpenLoads}/><QuickAction number="02" title="Customers" body="Search customers and review project-organized billing and balances." onPress={props.onOpenCustomers}/><QuickAction number="03" title="Projects" body="Create projects, manage Active or Completed status, and review details." onPress={props.onOpenProjects}/><QuickAction number="04" title="People & equipment" body="Manage workers, drivers, trucks, and machines used in dropdowns." onPress={props.onOpenDirectory}/>
    </ActionSection></Animated.View>
    <Animated.View style={motion(5)}><ActionSection title="Reports & Finance" hint="Review results, money, exports, and corrections." expanded={expanded.finance} onToggle={()=>toggle('finance')}>
      <QuickAction number="01" title="Reports center" body="Choose a project, open daily history, and create detailed PDF reports." onPress={props.onOpenReports}/><QuickAction number="02" title="Payments & balances" body="Open the financial overview, customers, suppliers, activity, and urgent balances." onPress={props.onOpenFinancials}/><QuickAction number="03" title="Correct confirmed loads" body="Correct allowed values while preserving transaction identity and payments." onPress={props.onOpenLoadCorrections}/>
    </ActionSection></Animated.View>
    <Animated.View style={motion(6)}><ActionSection title="Setup" hint="Configure choices used when creating future records." expanded={expanded.setup} onToggle={()=>toggle('setup')}>
      <QuickAction number="01" title="Item catalog" body="Create categories and items for loads, quarry purchases, and reports." onPress={props.onOpenCatalog}/><QuickAction number="02" title="Receipt setup" body="Manage measurement units, conversions, and receipt-related choices." onPress={props.onOpenReceiptSetup}/><QuickAction number="03" title="Company & VAT" body="Set company identity, logo, contact details, footer, and VAT rate." onPress={props.onOpenSettings}/>
    </ActionSection></Animated.View>
  </ScrollView>;
}

function ActionSection({title,hint,expanded,onToggle,children}:{title:string;hint:string;expanded:boolean;onToggle:()=>void;children:ReactNode}){
  const items=Children.toArray(children);const[renderItems,setRenderItems]=useState(expanded);const progress=useState(()=>new Animated.Value(expanded?1:0))[0];const press=useState(()=>new Animated.Value(0))[0];const itemMotion=useState(()=>items.map(()=>new Animated.Value(expanded?1:0)))[0];
  useEffect(()=>{if(expanded){setRenderItems(true);const animation=Animated.parallel([Animated.timing(progress,{toValue:1,duration:240,useNativeDriver:false}),Animated.stagger(55,itemMotion.map(value=>Animated.timing(value,{toValue:1,duration:220,useNativeDriver:true})))]);animation.start();return()=>animation.stop();}const animation=Animated.parallel([Animated.timing(progress,{toValue:0,duration:180,useNativeDriver:false}),Animated.stagger(30,[...itemMotion].reverse().map(value=>Animated.timing(value,{toValue:0,duration:150,useNativeDriver:true})))]);animation.start(({finished})=>{if(finished)setRenderItems(false);});return()=>animation.stop();},[expanded,itemMotion,progress]);
  const pressTo=(toValue:number)=>Animated.spring(press,{toValue,useNativeDriver:true,speed:30,bounciness:2}).start();
  return <View style={styles.section}><Pressable onPress={onToggle} onPressIn={()=>pressTo(1)} onPressOut={()=>pressTo(0)} accessibilityRole="button" accessibilityState={{expanded}}><Animated.View style={[styles.sectionHeader,styles.sectionHeaderNavy,{transform:[{translateX:press.interpolate({inputRange:[0,1],outputRange:[0,3]})},{scale:press.interpolate({inputRange:[0,1],outputRange:[1,.992]})}]}]}><View style={styles.sectionCopy}><Text style={styles.sectionTitle}>{title}</Text><Text style={styles.sectionHint}>{hint}</Text></View><Animated.Text style={[styles.sectionChevron,{transform:[{rotate:progress.interpolate({inputRange:[0,1],outputRange:['0deg','45deg']})}]}]}>+</Animated.Text><Animated.View style={[styles.sectionAccent,{width:progress.interpolate({inputRange:[0,1],outputRange:['0%','100%']})}]}/></Animated.View></Pressable>{renderItems?<View style={styles.actionList}>{items.map((item,index)=>{const value=itemMotion[index]!;return <Animated.View key={index} style={{opacity:value,transform:[{translateY:value.interpolate({inputRange:[0,1],outputRange:[-7,0]})}]}}>{item}</Animated.View>;})}</View>:null}</View>
}

function QuickAction({number,title,body,onPress,connected=false}:{number:string;title:string;body:string;onPress:()=>void;connected?:boolean}){return <MotionAction onPress={onPress} connected={connected}><Text style={styles.actionNumber}>{number}</Text><View style={styles.actionCopy}>{connected?<Text style={styles.connectedLabel}>CONNECTED WORKFLOW</Text>:null}<Text style={styles.quickActionTitle}>{title}</Text><Text style={styles.quickActionBody}>{body}</Text></View><Text style={styles.chevron}>{'\u203A'}</Text></MotionAction>}

function DromexWordmark(){return <Image source={require('../../../output/imagegen/dromex-logo-v2.png')} style={styles.wordmark} resizeMode="contain" accessibilityLabel="DROMEX"/>}

function MotionAction({onPress,primary=false,connected=false,children}:{onPress:()=>void;primary?:boolean;connected?:boolean;children:ReactNode}){
  const value=useState(()=>new Animated.Value(0))[0];const animate=(toValue:number)=>Animated.spring(value,{toValue,useNativeDriver:true,speed:28,bounciness:2}).start();
  return <Pressable onPress={onPress} onPressIn={()=>animate(1)} onPressOut={()=>animate(0)} accessibilityRole="button"><Animated.View style={[primary?styles.primaryAction:styles.quickAction,connected&&styles.connectedAction,{transform:[{translateX:value.interpolate({inputRange:[0,1],outputRange:[0,primary?0:3]})},{scale:value.interpolate({inputRange:[0,1],outputRange:[1,primary ? .955 : .985]})}]}]}>{children}</Animated.View></Pressable>
}

const styles=StyleSheet.create({content:{padding:20,paddingBottom:40,gap:18},header:{gap:7},headerLine:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',gap:12},eyebrow:{width:168,textAlign:'center',color:colors.brand,fontWeight:'900',fontSize:11,letterSpacing:1.6},wordmark:{width:168,height:87,alignSelf:'flex-start'},date:{width:168,textAlign:'center',color:colors.muted,fontSize:11},statusBadge:{flexDirection:'row',alignItems:'center',gap:8,paddingHorizontal:11,paddingVertical:8,borderRadius:16,backgroundColor:'#E8F3FB',borderWidth:1,borderColor:'#C4DDEA'},statusDot:{width:8,height:8,borderRadius:4,backgroundColor:colors.success},statusText:{color:'#173F67',fontSize:12,fontWeight:'900'},statusHint:{color:colors.muted,fontSize:9,marginTop:1},primaryAction:{backgroundColor:colors.brand,borderRadius:19,padding:21,gap:5,shadowColor:'#8E2E1B',shadowOpacity:.24,shadowRadius:10,shadowOffset:{width:0,height:5},elevation:5},primaryEyebrow:{color:'#173F67',fontSize:10,fontWeight:'900',letterSpacing:1.2},primaryActionLabel:{color:'#082D61',fontSize:25,fontWeight:'900'},primaryActionHint:{color:'#173F67',fontSize:13,lineHeight:18,fontWeight:'700'},section:{gap:9},sectionHeader:{minHeight:64,flexDirection:'row',alignItems:'center',gap:10,paddingHorizontal:14,paddingVertical:11,borderRadius:14,position:'relative',overflow:'hidden'},sectionHeaderNavy:{backgroundColor:'#173F67',borderWidth:1,borderColor:'#173F67'},sectionCopy:{flex:1,gap:3},sectionTitle:{color:'#FFF',fontWeight:'900',fontSize:20},sectionHint:{color:'#D5E4EF',fontSize:12,lineHeight:17},sectionChevron:{color:'#FFF',fontSize:25,fontWeight:'700',width:24,textAlign:'center'},sectionAccent:{position:'absolute',left:0,bottom:0,height:3,backgroundColor:colors.brand},actionList:{gap:8,paddingLeft:10},quickAction:{minHeight:82,flexDirection:'row',alignItems:'center',gap:12,padding:14,borderRadius:14,backgroundColor:colors.surface,borderLeftWidth:4,borderLeftColor:'#173F67',shadowColor:'#17212B',shadowOpacity:.04,shadowRadius:4,shadowOffset:{width:0,height:2},elevation:1},connectedAction:{backgroundColor:'#FFF2E8',borderLeftColor:colors.brand,borderWidth:1,borderColor:'#F0C5B4'},connectedLabel:{color:colors.brandDark,fontSize:8,fontWeight:'900',letterSpacing:.8},actionNumber:{width:28,color:colors.brand,fontSize:11,fontWeight:'900'},actionCopy:{flex:1,gap:3},quickActionTitle:{color:colors.ink,fontSize:16,fontWeight:'900'},quickActionBody:{color:colors.muted,fontSize:12,lineHeight:17},chevron:{color:colors.brand,fontSize:27,fontWeight:'900'}});
