import {useCallback,useEffect,useMemo,useState} from 'react';
import {ScrollView,StyleSheet,Text,TextInput,TouchableOpacity,View} from 'react-native';
import type {LoadRepository} from '../../data/repositories/LoadRepository';
import type {ConfirmedLoad,LoadCorrectionDraft} from '../../domain/loads';
import {SearchableSelect} from '../components/SearchableSelect';
import {CollapsibleFilterCard} from '../components/CollapsibleFilterCard';
import {colors} from '../theme';

type GroupMode='project'|'customer';
const draftFrom=(load:ConfirmedLoad):LoadCorrectionDraft=>({requestedQuantityKg:load.requestedQuantityKg==null?'':String(load.requestedQuantityKg),emptyWeightKg:String(load.emptyWeightKg),fullWeightKg:String(load.fullWeightKg),unitPriceUsd:load.unitPriceUsd==null?'':load.unitPriceUsd.toFixed(2),destinationAddress:load.destinationAddress??'',notes:load.notes??''});
const localDate=(value:string)=>{const date=new Date(value);return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;};
const unique=(values:string[])=>[...new Set(values)].sort((a,b)=>a.localeCompare(b));

export function LoadCorrectionsScreen({repository,onBack}:{repository:LoadRepository;onBack:()=>void}){
  const[loads,setLoads]=useState<ConfirmedLoad[]>([]);const[selected,setSelected]=useState<ConfirmedLoad|null>(null);const[draft,setDraft]=useState<LoadCorrectionDraft|null>(null);
  const[groupMode,setGroupMode]=useState<GroupMode>('project');const[projectFilter,setProjectFilter]=useState('');const[customerFilter,setCustomerFilter]=useState('');const[fromDate,setFromDate]=useState('');const[toDate,setToDate]=useState('');const[search,setSearch]=useState('');
  const[busy,setBusy]=useState(false);const[error,setError]=useState<string|null>(null);const[message,setMessage]=useState<string|null>(null);
  const refresh=useCallback(async()=>setLoads(await repository.listLoads()),[repository]);useEffect(()=>{void refresh();},[refresh]);
  const projectOptions=useMemo(()=>unique(loads.map(load=>load.projectName??'No project')).map(value=>({id:value,label:value})),[loads]);
  const customerOptions=useMemo(()=>unique(loads.map(load=>load.customerName)).map(value=>({id:value,label:value})),[loads]);
  const filtered=useMemo(()=>{const query=search.trim().toLocaleLowerCase('en-US');return loads.filter(load=>{const date=localDate(load.confirmedAt);if(projectFilter&&(load.projectName??'No project')!==projectFilter)return false;if(customerFilter&&load.customerName!==customerFilter)return false;if(fromDate&&date<fromDate)return false;if(toDate&&date>toDate)return false;if(query&&!`${load.transactionNumber} ${load.customerName} ${load.projectName??''} ${load.itemName} ${load.driverName} ${load.truckPlate}`.toLocaleLowerCase('en-US').includes(query))return false;return true;});},[customerFilter,fromDate,loads,projectFilter,search,toDate]);
  const groups=useMemo(()=>{const map=new Map<string,ConfirmedLoad[]>();for(const load of filtered){const key=groupMode==='project'?(load.projectName??'No project'):load.customerName;map.set(key,[...(map.get(key)??[]),load]);}return [...map].sort(([a],[b])=>a.localeCompare(b));},[filtered,groupMode]);
  function choose(load:ConfirmedLoad){setSelected(load);setDraft(draftFrom(load));setError(null);setMessage(null);}
  function update<K extends keyof LoadCorrectionDraft>(key:K,value:string){if(draft)setDraft({...draft,[key]:value});}
  async function save(){if(!selected||!draft)return;setBusy(true);setError(null);setMessage(null);try{const updated=await repository.correctLoad(selected.id,draft);setSelected(updated);setDraft(draftFrom(updated));await refresh();setMessage('Confirmed load corrected. Its number and original confirmation time did not change. Future PDFs use the corrected values.');}catch(cause){setError(cause instanceof Error?cause.message:'Could not correct the load.');}finally{setBusy(false);}}
  function clearFilters(){setProjectFilter('');setCustomerFilter('');setFromDate('');setToDate('');setSearch('');}
  return <ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><View style={styles.header}><TouchableOpacity style={styles.back} onPress={onBack}><Text style={styles.backText}>Back</Text></TouchableOpacity><View style={styles.flex}><Text style={styles.eyebrow}>SLICE 6</Text><Text style={styles.title}>Correct confirmed load</Text></View></View><Text style={styles.helper}>Find the load by project or customer, narrow it by date, or search its receipt number, item, driver, or truck plate.</Text>{error?<Text style={styles.error}>{error}</Text>:null}{message?<Text style={styles.success}>{message}</Text>:null}
    <CollapsibleFilterCard title="Find a load" summary={`${filtered.length} matching load${filtered.length===1?'':'s'}`}><View style={styles.row}><Text style={styles.helper}>Group and narrow confirmed loads</Text><TouchableOpacity onPress={clearFilters}><Text style={styles.clear}>Clear filters</Text></TouchableOpacity></View><View style={styles.segment}><Choice label="Under project" selected={groupMode==='project'} onPress={()=>setGroupMode('project')}/><Choice label="Under customer" selected={groupMode==='customer'} onPress={()=>setGroupMode('customer')}/></View><SearchableSelect label="Project" options={projectOptions} selectedId={projectFilter} onSelect={setProjectFilter} placeholder="All projects" allowClear/><SearchableSelect label="Customer" options={customerOptions} selectedId={customerFilter} onSelect={setCustomerFilter} placeholder="All customers" allowClear/><Field label="Search load" value={search} onChangeText={setSearch} placeholder="Receipt number, item, driver, or plate"/><View style={styles.twoColumns}><View style={styles.flex}><Field label="From date" value={fromDate} onChangeText={setFromDate} placeholder="YYYY-MM-DD"/></View><View style={styles.flex}><Field label="To date" value={toDate} onChangeText={setToDate} placeholder="YYYY-MM-DD"/></View></View><Text style={styles.resultCount}>{filtered.length} matching load{filtered.length===1?'':'s'}</Text></CollapsibleFilterCard>
    {!selected?<View style={styles.groups}>{groups.length?groups.map(([group,records])=><View key={group} style={styles.group}><View style={styles.groupHeader}><Text style={styles.groupTitle}>{group}</Text><Text style={styles.groupCount}>{records.length}</Text></View>{records.map(load=><TouchableOpacity key={load.id} style={styles.loadRow} onPress={()=>choose(load)}><View style={styles.row}><Text style={styles.loadNumber}>{load.transactionNumber}</Text><Text style={styles.date}>{localDate(load.confirmedAt)}</Text></View><Text style={styles.loadMain}>{load.itemName} · {load.billedQuantity.toFixed(3)} {load.outputUnitSymbol}</Text><Text style={styles.helper}>{groupMode==='project'?load.customerName:(load.projectName??'No project')} · {load.driverName} · {load.truckPlate}</Text></TouchableOpacity>)}</View>):<View style={styles.empty}><Text style={styles.cardTitle}>No matching loads</Text><Text style={styles.helper}>Change or clear one of the filters.</Text></View>}</View>:null}
    {selected&&draft?<View style={styles.card}><View style={styles.row}><View style={styles.flex}><Text style={styles.cardTitle}>{selected.transactionNumber}</Text><Text style={styles.helper}>{selected.projectName??'No project'} · {selected.customerName}</Text></View><TouchableOpacity onPress={()=>{setSelected(null);setDraft(null);setMessage(null);}}><Text style={styles.clear}>Choose another load</Text></TouchableOpacity></View><Text style={styles.helper}>Confirmed {new Date(selected.confirmedAt).toLocaleString()} · {selected.itemName}</Text><Text style={styles.notice}>Transaction number, original confirmation time, customer, project, item, conversion identity, and existing payments remain unchanged.</Text><Field label="Requested quantity kg" value={draft.requestedQuantityKg} onChangeText={(v)=>update('requestedQuantityKg',v)} keyboardType="number-pad"/><Field label="Empty weight kg *" value={draft.emptyWeightKg} onChangeText={(v)=>update('emptyWeightKg',v)} keyboardType="number-pad"/><Field label="Full weight kg *" value={draft.fullWeightKg} onChangeText={(v)=>update('fullWeightKg',v)} keyboardType="number-pad"/><Field label="Unit price USD (blank = Unpriced)" value={draft.unitPriceUsd} onChangeText={(v)=>update('unitPriceUsd',v)} keyboardType="decimal-pad"/><Field label="Destination address" value={draft.destinationAddress} onChangeText={(v)=>update('destinationAddress',v)} multiline/><Field label="Notes" value={draft.notes} onChangeText={(v)=>update('notes',v)} multiline/><View style={styles.result}><Text style={styles.resultText}>Current quantity: {selected.billedQuantity.toFixed(3)} {selected.outputUnitSymbol}</Text><Text style={styles.resultText}>Current status: {selected.paymentStatus}</Text></View><TouchableOpacity style={styles.save} disabled={busy} onPress={()=>void save()}><Text style={styles.saveText}>{busy?'Recalculating…':'Save confirmed correction'}</Text></TouchableOpacity></View>:null}
  </ScrollView>;
}

function Choice({label,selected,onPress}:{label:string;selected:boolean;onPress:()=>void}){return <TouchableOpacity style={[styles.choice,selected&&styles.choiceSelected]} onPress={onPress}><Text style={[styles.choiceText,selected&&styles.choiceTextSelected]}>{label}</Text></TouchableOpacity>;}
function Field({label,...props}:{label:string;value:string;onChangeText:(v:string)=>void;placeholder?:string;multiline?:boolean;keyboardType?:'default'|'number-pad'|'decimal-pad'}){return <View style={styles.field}><Text style={styles.label}>{label}</Text><TextInput style={[styles.input,props.multiline&&styles.multiline]} placeholderTextColor="#89939B" {...props}/></View>;}
const styles=StyleSheet.create({content:{padding:20,paddingBottom:42,gap:15},header:{flexDirection:'row',alignItems:'center',gap:14},back:{backgroundColor:colors.surface,padding:10,borderRadius:10},backText:{color:colors.ink,fontWeight:'800'},flex:{flex:1},eyebrow:{color:colors.brand,fontSize:11,fontWeight:'900',letterSpacing:1.3},title:{color:colors.ink,fontSize:27,fontWeight:'900'},helper:{color:colors.muted,fontSize:12,lineHeight:18},filterCard:{backgroundColor:colors.surface,borderRadius:15,padding:16,gap:12},card:{backgroundColor:colors.surface,borderRadius:15,padding:16,gap:12},cardTitle:{color:colors.ink,fontSize:18,fontWeight:'900'},row:{flexDirection:'row',justifyContent:'space-between',alignItems:'flex-start',gap:10},twoColumns:{flexDirection:'row',gap:10},segment:{flexDirection:'row',backgroundColor:'#EEEAE2',borderRadius:11,padding:4,gap:4},choice:{flex:1,padding:10,borderRadius:8,alignItems:'center'},choiceSelected:{backgroundColor:colors.ink},choiceText:{color:colors.muted,fontWeight:'800'},choiceTextSelected:{color:'#FFF'},clear:{color:colors.brandDark,fontWeight:'900',fontSize:12},field:{gap:6},label:{color:colors.ink,fontSize:13,fontWeight:'800'},input:{borderWidth:1,borderColor:colors.line,borderRadius:10,padding:12,color:colors.ink,backgroundColor:'#FCFBF8'},multiline:{minHeight:70,textAlignVertical:'top'},resultCount:{color:colors.brandDark,fontWeight:'900'},groups:{gap:14},group:{gap:8},groupHeader:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},groupTitle:{color:colors.ink,fontSize:18,fontWeight:'900'},groupCount:{backgroundColor:'#EEEAE2',color:colors.brandDark,fontWeight:'900',paddingHorizontal:9,paddingVertical:4,borderRadius:12},loadRow:{backgroundColor:colors.surface,borderRadius:13,padding:14,gap:4},loadNumber:{color:colors.ink,fontWeight:'900'},loadMain:{color:colors.ink,fontSize:14,fontWeight:'800'},date:{color:colors.brandDark,fontWeight:'800',fontSize:12},empty:{borderWidth:1,borderColor:colors.line,borderStyle:'dashed',borderRadius:15,padding:16,gap:5},notice:{backgroundColor:'#FFF3D8',color:colors.warning,padding:11,borderRadius:9,lineHeight:17,fontSize:12},result:{backgroundColor:'#EEEAE2',borderRadius:10,padding:12,gap:4},resultText:{color:colors.ink,fontWeight:'800'},save:{backgroundColor:colors.ink,borderRadius:11,padding:15,alignItems:'center'},saveText:{color:'#FFF',fontWeight:'900'},error:{color:colors.danger,backgroundColor:'#FCE8E6',padding:12,borderRadius:10,fontWeight:'700'},success:{color:colors.success,backgroundColor:'#E5F3EC',padding:12,borderRadius:10,fontWeight:'700'}});
