import { useEffect, useMemo, useState } from 'react';
import { Alert, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';

import type { LoadRepository } from '../../data/repositories/LoadRepository';
import { calculateLoad, emptyLoadDraft, formatUsd, type ConfirmedLoad, type LoadDraft, type LoadSetupOptions, validateLoadDraft } from '../../domain/loads';
import { LoadDocuments, type DocumentViewData } from '../components/LoadDocuments';
import { SearchableSelect } from '../components/SearchableSelect';
import { colors } from '../theme';

export function MakeReceiptScreen({ repository, onBack, onOpenSetup, onOpenDirectory, onOpenProjects }: { repository: LoadRepository; onBack: () => void; onOpenSetup: () => void; onOpenDirectory: () => void; onOpenProjects: () => void }) {
  const [options, setOptions] = useState<LoadSetupOptions | null>(null); const [draft, setDraft] = useState<LoadDraft>(emptyLoadDraft);
  const [loaded, setLoaded] = useState(false); const [preview, setPreview] = useState(false); const [issues, setIssues] = useState<string[]>([]);
  const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState(false); const [confirmed, setConfirmed] = useState<ConfirmedLoad | null>(null);
  useEffect(() => { let active = true; void Promise.all([repository.getSetupOptions(), repository.getDraft()]).then(([nextOptions, saved]) => { if (!active) return; setOptions(nextOptions); setDraft(saved ?? emptyLoadDraft); setLoaded(true); }); return () => { active = false; }; }, [repository]);
  useEffect(() => { if (!loaded || confirmed) return; const timer = setTimeout(() => { void repository.saveDraft(draft); }, 450); return () => clearTimeout(timer); }, [confirmed, draft, loaded, repository]);
  const conversion = options?.conversions.find((value) => value.id === draft.conversionId);
  const calculation = useMemo(() => calculateLoad(draft, conversion, options?.companySettings.vatRatePercent ?? 0), [conversion, draft, options?.companySettings.vatRatePercent]);
  const customer = options?.customers.find((value) => value.id === draft.customerId); const item = options?.items.find((value) => value.id === draft.itemId);
  const project = options?.projects.find((value) => value.id === draft.projectId);
  function update<K extends keyof LoadDraft>(key: K, value: LoadDraft[K]) { setDraft((current) => ({ ...current, [key]: value })); setIssues([]); }
  function selectCustomer(id: string) { setDraft((current) => { const currentProject = options?.projects.find((value) => value.id === current.projectId); return { ...current, customerId: id, projectId: currentProject?.customerId === id ? current.projectId : '' }; }); setIssues([]); }
  function selectProject(id: string) { const selected = options?.projects.find((value) => value.id === id); setDraft((current) => ({ ...current, projectId: id, customerId: selected?.customerId ?? current.customerId, destinationAddress: selected ? '' : current.destinationAddress })); setIssues([]); }
  function selectItem(id: string) { const selected = options?.items.find((value) => value.id === id); setDraft((current) => ({ ...current, itemId: id, unitPriceUsd: selected?.defaultPriceUsd == null ? current.unitPriceUsd : String(selected.defaultPriceUsd) })); }
  function selectDriver(id: string) { const selected = options?.drivers.find((value) => value.id === id); setDraft((current) => ({ ...current, driverId: id, driverName: selected?.name ?? '' })); }
  function selectTruck(id: string) { const selected = options?.trucks.find((value) => value.id === id); setDraft((current) => ({ ...current, truckId: id, truckPlate: selected?.plate ?? '' })); }

  async function doConfirm() {
    if (!options) return; const nextIssues = validateLoadDraft(draft, options); setIssues(nextIssues); if (nextIssues.length) return;
    Alert.alert('Confirm this load?', 'Confirmation assigns the permanent transaction number. The record cannot return to Draft.', [
      { text: 'Review again', style: 'cancel' },
      { text: 'Confirm load', onPress: () => { setBusy(true); setError(null); void repository.confirmLoad(draft).then((record) => { setConfirmed(record); setPreview(false); setDraft(emptyLoadDraft); }).catch((cause) => setError(cause instanceof Error ? cause.message : 'Could not confirm load.')).finally(() => setBusy(false)); } },
    ]);
  }
  if (!options) return <View style={styles.loading}><Text style={styles.helper}>Loading receipt workflow…</Text></View>;
  if (confirmed) return <ScrollView contentContainerStyle={styles.content}><Header title="Load confirmed" onBack={onBack} /><Text style={styles.success}>Saved offline as {confirmed.transactionNumber}. Open it in Load History to add the driver signature or share either PDF.</Text><LoadDocuments data={confirmedDocument(confirmed)} isDraft={false} /><TouchableOpacity style={styles.primary} onPress={() => setConfirmed(null)}><Text style={styles.primaryText}>Start another load</Text></TouchableOpacity></ScrollView>;
  if (preview) return <ScrollView contentContainerStyle={styles.content}><Header title="Document preview" onBack={() => setPreview(false)} /><LoadDocuments data={draftDocument(options, draft, calculation)} isDraft /><TouchableOpacity style={styles.primary} disabled={busy} onPress={() => void doConfirm()}><Text style={styles.primaryText}>{busy ? 'Confirming…' : 'Review validation and confirm'}</Text></TouchableOpacity>{issues.map((issue) => <Text key={issue} style={styles.issue}>• {issue}</Text>)}</ScrollView>;
  return (
    <ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled">
      <Header title="Make Receipt" onBack={onBack} />
      <Text style={styles.autosave}>Draft autosaves locally</Text>{error ? <Text style={styles.error}>{error}</Text> : null}
      {(!options.customers.length || !options.items.length || !options.conversions.length || !options.drivers.length || !options.trucks.length) ? <View style={styles.warning}><Text style={styles.warningTitle}>Setup required</Text><Text style={styles.helper}>Create a customer, load-enabled item, saved driver, and saved truck. Units and the kg-to-ton conversion are already seeded.</Text><TouchableOpacity onPress={onOpenDirectory}><Text style={styles.link}>Open Drivers & trucks →</Text></TouchableOpacity></View> : null}

      <Section title="Customer and destination">
        <SearchableSelect label="Project" options={options.projects.map((value) => ({ id: value.id, label: value.name, detail: `${value.customerName} · ${value.location}` }))} selectedId={draft.projectId} onSelect={selectProject} allowClear placeholder={options.projects.length ? 'Search and select a project' : 'Create a project first'} />
        <Text style={styles.helper}>Selecting a project automatically selects its customer and links the confirmed load to that project's daily report.</Text>
        <SearchableSelect label="Customer *" options={options.customers.map((value) => ({ id: value.id, label: value.name, detail: value.isOwnCompany ? 'Own company' : value.type }))} selectedId={draft.customerId} onSelect={selectCustomer} />
        {customer ? <Text style={styles.helper}>{customer.isOwnCompany ? 'Own company: a saved project is required.' : 'Outside customer: select a project or enter a destination.'}</Text> : null}
        {!project && customer && !customer.isOwnCompany ? <Field label="Destination address *" value={draft.destinationAddress} onChangeText={(value) => update('destinationAddress', value)} multiline /> : null}
      </Section>
      <Section title="Load information">
        <SearchableSelect label="Load-enabled item *" options={options.items.map((value) => ({ id: value.id, label: value.name, detail: [value.categoryName, value.internalCode].filter(Boolean).join(' · ') }))} selectedId={draft.itemId} onSelect={selectItem} />
        <SearchableSelect label="Driver *" options={options.drivers.map((value) => ({ id: value.id, label: value.name, detail: [value.phone, value.licenseNumber ? `Licence ${value.licenseNumber}` : null].filter(Boolean).join(' · ') }))} selectedId={draft.driverId} onSelect={selectDriver} />
        <SearchableSelect label="Truck *" options={options.trucks.map((value) => ({ id: value.id, label: value.plate, detail: [value.makeModel, value.ownerName].filter(Boolean).join(' · ') }))} selectedId={draft.truckId} onSelect={selectTruck} />
        <Field label="Requested quantity (kg, optional)" value={draft.requestedQuantityKg} onChangeText={(value) => update('requestedQuantityKg', value)} keyboardType="number-pad" />
        <View style={styles.columns}><View style={styles.column}><Field label="Empty weight kg *" value={draft.emptyWeightKg} onChangeText={(value) => update('emptyWeightKg', value)} keyboardType="number-pad" /></View><View style={styles.column}><Field label="Full weight kg *" value={draft.fullWeightKg} onChangeText={(value) => update('fullWeightKg', value)} keyboardType="number-pad" /></View></View>
        <View style={styles.calculation}><Text style={styles.calculationLabel}>Calculated net weight</Text><Text style={styles.calculationValue}>{calculation.netWeightKg == null ? '—' : `${calculation.netWeightKg} kg`}</Text></View>
      </Section>
      <Section title="Conversion and price">
        <SearchableSelect label="Conversion *" options={options.conversions.map((value) => ({ id: value.id, label: value.name, detail: `${value.inputQuantity} ${value.inputUnitSymbol} = ${value.outputQuantity} ${value.outputUnitSymbol}` }))} selectedId={draft.conversionId} onSelect={(id) => update('conversionId', id)} />
        {conversion ? <Text style={styles.helper}>{conversion.inputQuantity} {conversion.inputUnitSymbol} = {conversion.outputQuantity} {conversion.outputUnitSymbol} · result: {calculation.billedQuantity == null ? '—' : calculation.billedQuantity.toFixed(conversion.decimalPlaces)} {conversion.outputUnitSymbol}</Text> : null}
        <Field label="Price per converted unit USD (optional)" value={draft.unitPriceUsd} onChangeText={(value) => update('unitPriceUsd', value)} keyboardType="decimal-pad" />
        <View style={styles.totalRow}><Total label="Subtotal" value={formatUsd(calculation.subtotalUsd)} /><Total label={`VAT ${options.companySettings.vatRatePercent}%`} value={formatUsd(calculation.vatAmountUsd)} /><Total label="Final" value={formatUsd(calculation.finalTotalUsd)} /></View>
        <Field label="Notes" value={draft.notes} onChangeText={(value) => update('notes', value)} multiline />
      </Section>
      {issues.map((issue) => <Text key={issue} style={styles.issue}>• {issue}</Text>)}
      <TouchableOpacity style={styles.primary} onPress={() => { const next = validateLoadDraft(draft, options); setIssues(next); setPreview(true); }}><Text style={styles.primaryText}>Preview receipt and authorization</Text></TouchableOpacity>
      <TouchableOpacity style={styles.secondary} onPress={onOpenProjects}><Text style={styles.secondaryText}>Manage projects</Text></TouchableOpacity>
      <TouchableOpacity style={styles.secondary} onPress={onOpenSetup}><Text style={styles.secondaryText}>Manage units and conversions</Text></TouchableOpacity>
    </ScrollView>
  );
}

function draftDocument(options: LoadSetupOptions, draft: LoadDraft, calculation: ReturnType<typeof calculateLoad>): DocumentViewData { const customer = options.customers.find((v) => v.id === draft.customerId); const project = options.projects.find((v) => v.id === draft.projectId); const item = options.items.find((v) => v.id === draft.itemId); const conversion = options.conversions.find((v) => v.id === draft.conversionId); return { companyName: options.companySettings.companyName, companyAddress: options.companySettings.address, companyPhone: options.companySettings.phone, companyEmail: options.companySettings.email, companyTaxVatNumber: options.companySettings.taxVatNumber, companyReceiptFooter: options.companySettings.receiptFooter, transactionNumber: '', dateTime: new Date().toISOString(), customerName: customer?.name ?? '', projectName: project?.name ?? null, destinationAddress: project?.location ?? (draft.destinationAddress.trim() || null), itemName: item?.name ?? '', driverName: draft.driverName.trim(), truckPlate: draft.truckPlate.trim(), requestedQuantityKg: draft.requestedQuantityKg ? Number(draft.requestedQuantityKg) : null, emptyWeightKg: draft.emptyWeightKg ? Number(draft.emptyWeightKg) : null, fullWeightKg: draft.fullWeightKg ? Number(draft.fullWeightKg) : null, netWeightKg: calculation.netWeightKg, convertedQuantity: calculation.billedQuantity, outputUnitSymbol: conversion?.outputUnitSymbol ?? null, unitPriceUsd: draft.unitPriceUsd.trim() ? Number(draft.unitPriceUsd.replace(',', '.')) : null, subtotalUsd: calculation.subtotalUsd, vatRatePercent: draft.unitPriceUsd.trim() ? options.companySettings.vatRatePercent : null, vatAmountUsd: calculation.vatAmountUsd, finalTotalUsd: calculation.finalTotalUsd, signaturePaths: [] }; }
export function confirmedDocument(record: ConfirmedLoad): DocumentViewData { return { companyName: record.companyName, companyAddress: record.companyAddress, companyPhone: record.companyPhone, companyEmail: record.companyEmail, companyTaxVatNumber: record.companyTaxVatNumber, companyReceiptFooter: record.companyReceiptFooter, transactionNumber: record.transactionNumber, dateTime: record.confirmedAt, customerName: record.customerName, projectName: record.projectName, destinationAddress: record.projectLocation ?? record.destinationAddress, itemName: record.itemName, driverName: record.driverName, truckPlate: record.truckPlate, requestedQuantityKg: record.requestedQuantityKg, emptyWeightKg: record.emptyWeightKg, fullWeightKg: record.fullWeightKg, netWeightKg: record.netWeightKg, convertedQuantity: record.billedQuantity, outputUnitSymbol: record.outputUnitSymbol, unitPriceUsd: record.unitPriceUsd, subtotalUsd: record.subtotalUsd, vatRatePercent: record.vatRatePercent, vatAmountUsd: record.vatAmountUsd, finalTotalUsd: record.finalTotalUsd, signaturePaths: record.signaturePaths }; }
function Header({ title, onBack }: { title: string; onBack: () => void }) { return <View style={styles.header}><TouchableOpacity style={styles.back} onPress={onBack}><Text style={styles.backText}>Back</Text></TouchableOpacity><View><Text style={styles.eyebrow}>LOAD WORKFLOW</Text><Text style={styles.title}>{title}</Text></View></View>; }
function Section({ title, children }: { title: string; children: React.ReactNode }) { return <View style={styles.card}><Text style={styles.sectionTitle}>{title}</Text>{children}</View>; }
function Label({ text }: { text: string }) { return <Text style={styles.label}>{text}</Text>; }
function Field({ label, ...props }: { label: string; value: string; onChangeText: (value: string) => void; multiline?: boolean; keyboardType?: 'default' | 'number-pad' | 'decimal-pad'; autoCapitalize?: 'none' | 'sentences' | 'characters' }) { return <View style={styles.field}><Text style={styles.label}>{label}</Text><TextInput style={[styles.input, props.multiline && styles.multiline]} placeholderTextColor="#89939B" {...props} /></View>; }
function Chips({ values, selected, onSelect, allowClear = false }: { values: { id: string; label: string }[]; selected: string; onSelect: (id: string) => void; allowClear?: boolean }) { return <View style={styles.chips}>{allowClear ? <TouchableOpacity onPress={() => onSelect('')} style={[styles.chip, !selected && styles.chipSelected]}><Text style={[styles.chipText, !selected && styles.chipTextSelected]}>No project</Text></TouchableOpacity> : null}{values.map((value) => <TouchableOpacity key={value.id} onPress={() => onSelect(value.id)} style={[styles.chip, selected === value.id && styles.chipSelected]}><Text style={[styles.chipText, selected === value.id && styles.chipTextSelected]}>{value.label}</Text></TouchableOpacity>)}</View>; }
function Total({ label, value }: { label: string; value: string }) { return <View style={styles.total}><Text style={styles.totalValue}>{value}</Text><Text style={styles.totalLabel}>{label}</Text></View>; }
const styles = StyleSheet.create({
  loading: { flex: 1, alignItems: 'center', justifyContent: 'center' }, content: { padding: 20, paddingBottom: 42, gap: 16 }, header: { flexDirection: 'row', alignItems: 'center', gap: 14 }, back: { backgroundColor: colors.surface, padding: 10, borderRadius: 10 }, backText: { color: colors.ink, fontWeight: '800' }, eyebrow: { color: colors.brand, fontSize: 11, fontWeight: '900', letterSpacing: 1.4 }, title: { color: colors.ink, fontSize: 28, fontWeight: '900' }, autosave: { color: colors.success, fontSize: 12, fontWeight: '800' }, helper: { color: colors.muted, fontSize: 13, lineHeight: 19 }, error: { color: colors.danger, backgroundColor: '#FCE8E6', padding: 12, borderRadius: 10 }, success: { color: colors.success, backgroundColor: '#E5F3EC', padding: 12, borderRadius: 10, fontWeight: '700' }, warning: { backgroundColor: '#FFF3D6', padding: 14, borderRadius: 12, gap: 5 }, warningTitle: { color: colors.warning, fontWeight: '900' }, link: { color: colors.brandDark, fontWeight: '900', marginTop: 4 }, card: { backgroundColor: colors.surface, borderRadius: 16, padding: 17, gap: 12 }, sectionTitle: { color: colors.ink, fontSize: 19, fontWeight: '900' }, label: { color: colors.ink, fontSize: 13, fontWeight: '800' }, field: { gap: 6 }, input: { borderWidth: 1, borderColor: colors.line, borderRadius: 11, paddingHorizontal: 13, paddingVertical: 11, color: colors.ink, backgroundColor: '#FCFBF8' }, multiline: { minHeight: 72, textAlignVertical: 'top' }, chips: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 }, chip: { borderWidth: 1, borderColor: colors.line, borderRadius: 18, paddingHorizontal: 11, paddingVertical: 8 }, chipSelected: { borderColor: colors.brand, backgroundColor: '#FBE9E4' }, chipText: { color: colors.muted, fontWeight: '700' }, chipTextSelected: { color: colors.brandDark }, columns: { flexDirection: 'row', gap: 10 }, column: { flex: 1 }, calculation: { backgroundColor: '#EEF3F7', borderRadius: 11, padding: 13 }, calculationLabel: { color: colors.muted, fontSize: 12 }, calculationValue: { color: colors.ink, fontSize: 21, fontWeight: '900' }, totalRow: { flexDirection: 'row', gap: 7 }, total: { flex: 1, backgroundColor: '#F5F2EC', borderRadius: 10, padding: 10 }, totalValue: { color: colors.ink, fontSize: 14, fontWeight: '900' }, totalLabel: { color: colors.muted, fontSize: 10, marginTop: 4 }, issue: { color: colors.danger, backgroundColor: '#FCE8E6', padding: 9, borderRadius: 8 }, primary: { backgroundColor: colors.brand, borderRadius: 12, padding: 15, alignItems: 'center' }, primaryText: { color: '#FFF', fontWeight: '900' }, secondary: { borderWidth: 1, borderColor: colors.line, borderRadius: 12, padding: 13, alignItems: 'center' }, secondaryText: { color: colors.ink, fontWeight: '800' },
});
