import {useCallback,useEffect,useMemo,useState} from 'react';
import {StyleSheet,Text,TouchableOpacity,View} from 'react-native';
import type {PavementRepository} from '../../data/repositories/PavementRepository';
import {DEFAULT_PAVEMENT_DENSITY,calculatePavement,looseThickness,pavementSpreadRates,type PavementCalculation,type PavementCalculationDraft,type PavementSetup} from '../../domain/pavement';
import {AppButton,AppCard,AppField,AppPage,EmptyState,Feedback,MetricCard,PageHeader} from '../components/AppPrimitives';
import {SearchableSelect} from '../components/SearchableSelect';
import {ExpandableMenuSection} from '../components/ExpandableMenu';
import {PavementAdvancedSections} from '../components/PavementAdvancedSections';
import {exportPavementExcel,exportPavementPdf} from '../../services/pavementExport';
import {colors} from '../theme';

type Form={projectId:string;name:string;length:string;width:string;directArea:string;rateId:string;customRate:string;density:string;looseFactorId:string;customLooseFactor:string;allowance:string;notes:string};
const looseFactors=[1.15,1.20,1.25,1.30] as const;
const empty=(projectId=''):Form=>({projectId,name:'',length:'',width:'',directArea:'',rateId:'90',customRate:'',density:DEFAULT_PAVEMENT_DENSITY.toFixed(2),looseFactorId:'',customLooseFactor:'',allowance:'0',notes:''});
const number=(value:string)=>{const parsed=Number(value.replace(',','.'));return Number.isFinite(parsed)?parsed:0;};
const optional=(value:string)=>value.trim()?number(value):null;
const format=(value:number,digits=1)=>value.toLocaleString(undefined,{minimumFractionDigits:digits,maximumFractionDigits:digits});

export function PavementCalculatorScreen({repository,onBack,initialProjectId}:{repository:PavementRepository;onBack:()=>void;initialProjectId?:string|null}){
  const[setup,setSetup]=useState<PavementSetup|null>(null);const[form,setForm]=useState<Form>(()=>empty(initialProjectId??''));const[records,setRecords]=useState<PavementCalculation[]>([]);const[editingId,setEditingId]=useState<string|null>(null);const[openCore,setOpenCore]=useState<Set<string>>(()=>new Set());const[busy,setBusy]=useState(false);const[error,setError]=useState<string|null>(null);const[message,setMessage]=useState<string|null>(null);
  const toggleCore=(key:string)=>setOpenCore(current=>{const next=new Set(current);if(next.has(key))next.delete(key);else next.add(key);return next;});
  const locked=!!initialProjectId;
  const refresh=useCallback(async()=>{const next=await repository.getSetup();setSetup(next);setRecords(await repository.listCalculations(initialProjectId??null));},[initialProjectId,repository]);
  useEffect(()=>{void refresh().catch(cause=>setError(cause instanceof Error?cause.message:'Could not load pavement calculations.'));},[refresh]);
  const density=number(form.density),rate=form.rateId==='custom'?number(form.customRate):number(form.rateId),looseFactor=form.looseFactorId==='custom'?number(form.customLooseFactor):form.looseFactorId?number(form.looseFactorId):null,length=number(form.length),width=number(form.width),directArea=number(form.directArea),area=directArea>0?directArea:length*width,allowance=number(form.allowance);
  const result=useMemo(()=>area>0&&rate>0&&density>0?calculatePavement(area,rate,density,Math.max(0,allowance)):null,[allowance,area,density,rate]);
  const rateOptions=useMemo(()=>[...pavementSpreadRates.map(value=>({id:String(value),label:`${value} kg/m²`,detail:density>0?`${(value/density).toFixed(1)} mm compacted at ${density.toFixed(2)} t/m³`:'Enter density to see thickness'})),{id:'custom',label:'Custom kg/m²',detail:'Enter any positive spread rate'}],[density]);
  const looseFactorOptions=useMemo(()=>[...looseFactors.map(value=>({id:value.toFixed(2),label:`${value.toFixed(2)} × project factor`,detail:'Planning option — confirm from the project mix and paver trial'})),{id:'custom',label:'Custom project factor',detail:'Use your calibrated loose-to-compacted factor'}],[]);
  const projects=setup?.projects??[],activeProjects=projects.filter(project=>project.status==='active');
  function draft():PavementCalculationDraft{return{projectId:form.projectId,name:form.name,lengthM:optional(form.length),widthM:optional(form.width),areaM2:area,spreadRateKgM2:rate,densityTM3:density,looseThicknessFactor:looseFactor,allowancePercent:allowance,notes:form.notes};}
  async function save(){setBusy(true);setError(null);setMessage(null);try{await repository.saveCalculation(draft(),editingId??undefined);setMessage(editingId?'Pavement calculation updated.':'Pavement calculation saved under the project.');setEditingId(null);setForm(empty(initialProjectId??form.projectId));await refresh();}catch(cause){setError(cause instanceof Error?cause.message:'Could not save the pavement calculation.');}finally{setBusy(false);}}
  function edit(record:PavementCalculation){const preset=record.looseThicknessFactor!==null&&looseFactors.includes(record.looseThicknessFactor as never);setEditingId(record.id);setForm({projectId:record.projectId,name:record.name,length:record.lengthM?.toString()??'',width:record.widthM?.toString()??'',directArea:record.lengthM&&record.widthM?'':record.areaM2.toString(),rateId:pavementSpreadRates.includes(record.spreadRateKgM2 as never)?String(record.spreadRateKgM2):'custom',customRate:pavementSpreadRates.includes(record.spreadRateKgM2 as never)?'':record.spreadRateKgM2.toString(),density:record.densityTM3.toString(),looseFactorId:record.looseThicknessFactor===null?'':preset?record.looseThicknessFactor.toFixed(2):'custom',customLooseFactor:record.looseThicknessFactor!==null&&!preset?record.looseThicknessFactor.toString():'',allowance:record.allowancePercent.toString(),notes:record.notes});setMessage(null);setError(null);}
  const visible=initialProjectId?records:form.projectId?records.filter(value=>value.projectId===form.projectId):records;
  const totalArea=visible.reduce((sum,value)=>sum+value.areaM2,0),totalPlanned=visible.reduce((sum,value)=>sum+value.plannedKg,0)/1000,exportProject=form.projectId?projects.find(value=>value.id===form.projectId)?.name??'Selected project':initialProjectId?projects.find(value=>value.id===initialProjectId)?.name??'Selected project':'All Projects';
  async function runExport(kind:'pdf'|'excel'){setBusy(true);setError(null);setMessage(null);try{if(kind==='pdf')await exportPavementPdf(visible,exportProject);else await exportPavementExcel(visible,exportProject);setMessage(`${kind==='pdf'?'PDF':'Excel workbook'} created and ready to share.`);}catch(cause){setError(cause instanceof Error?cause.message:'Could not export pavement calculations.');}finally{setBusy(false);}}
  return <AppPage keyboard><PageHeader eyebrow="PAVEMENT QUANTITY" title="Asphalt Calculator" onBack={onBack}/><AppCard tone="navy" title="kg/m² is the main rule" hint="Choose a spread rate. DROMEX converts it to compacted thickness, kilograms, and tonnes."><Text style={styles.formula}>Quantity (kg) = area (m²) × kg/m²</Text><Text style={styles.formula}>Thickness (mm) = kg/m² ÷ compacted density (t/m³)</Text></AppCard>{error?<Feedback kind="error">{error}</Feedback>:null}{message?<Feedback kind="success">{message}</Feedback>:null}
    <AppCard tone="orange" title={editingId?'Edit pavement calculation':'New pavement calculation'} hint="Saved calculations stay under their project and keep each layer separate.">{locked?<View style={styles.locked}><Text style={styles.lockedLabel}>PROJECT LOCKED</Text><Text style={styles.lockedValue}>{projects.find(value=>value.id===form.projectId)?.name??'Selected project'}</Text></View>:<SearchableSelect label="Project *" options={activeProjects.map(project=>({id:project.id,label:project.name,detail:`${project.customerName} · ${project.location}`}))} selectedId={form.projectId} onSelect={projectId=>setForm({...form,projectId})} placeholder="Choose an active project"/>}<AppField label="Section or layer name *" value={form.name} onChangeText={name=>setForm({...form,name})} placeholder="Example: Wearing course · Station 0+000–0+500"/></AppCard>
    <ExpandableMenuSection title="1 · Paved area" hint="Length × width or a directly entered net area." open={openCore.has('area')} onToggle={()=>toggleCore('area')}><AppCard><View style={styles.two}><View style={styles.half}><AppField label="Length (m)" value={form.length} onChangeText={length=>setForm({...form,length})} keyboardType="decimal-pad"/></View><View style={styles.half}><AppField label="Average width (m)" value={form.width} onChangeText={width=>setForm({...form,width})} keyboardType="decimal-pad"/></View></View><View style={styles.or}><View style={styles.line}/><Text style={styles.orText}>OR</Text><View style={styles.line}/></View><AppField label="Direct net area (m²)" value={form.directArea} onChangeText={directArea=>setForm({...form,directArea})} keyboardType="decimal-pad" placeholder="Overrides length × width when entered"/><View style={styles.areaBand}><Text style={styles.areaLabel}>CALCULATED NET AREA</Text><Text style={styles.areaValue}>{format(area,2)} m²</Text></View></AppCard></ExpandableMenuSection>
    <ExpandableMenuSection title="2 · Spread rate and thickness" hint="kg/m², density, loose factor, and allowance." tone="cream" open={openCore.has('rate')} onToggle={()=>toggleCore('rate')}><AppCard tone="cream"><SearchableSelect label="Target spread rate *" options={rateOptions} selectedId={form.rateId} onSelect={rateId=>setForm({...form,rateId})}/>{form.rateId==='custom'?<AppField label="Custom rate (kg/m²) *" value={form.customRate} onChangeText={customRate=>setForm({...form,customRate})} keyboardType="decimal-pad"/>:null}<AppField label="Compacted density (t/m³) *" value={form.density} onChangeText={densityValue=>setForm({...form,density:densityValue})} keyboardType="decimal-pad"/><SearchableSelect label="Loose-to-compacted thickness factor" options={looseFactorOptions} selectedId={form.looseFactorId} onSelect={looseFactorId=>setForm({...form,looseFactorId})} placeholder="Choose your project/paver factor (optional)"/>{form.looseFactorId==='custom'?<AppField label="Custom loose-thickness factor" value={form.customLooseFactor} onChangeText={customLooseFactor=>setForm({...form,customLooseFactor})} keyboardType="decimal-pad" placeholder="Example: 1.20"/>:null}<Text style={styles.factorNote}>No universal factor is assumed. Use the value established by the mix, paver setup, trial strip, or project specification.</Text><AppField label="Waste / contingency allowance (%)" value={form.allowance} onChangeText={allowanceValue=>setForm({...form,allowance:allowanceValue})} keyboardType="decimal-pad"/></AppCard></ExpandableMenuSection>
    <View style={styles.metrics}><MetricCard label="Selected rate" value={`${format(rate,0)} kg/m²`} result/><MetricCard label="Before compaction · loose" value={result&&looseFactor?`${format(looseThickness(result.thicknessMm,looseFactor),1)} mm`:'Choose factor'} result/><MetricCard label="After compaction · finished" value={result?`${format(result.thicknessMm,1)} mm`:'—'} result/><MetricCard label="Theoretical quantity" value={result?`${format(result.theoreticalTonnes,3)} t`:'—'} result/><MetricCard label="Allowance" value={result?`${format(result.allowanceKg/1000,3)} t`:'—'} result/><MetricCard label="Planned quantity" value={result?`${format(result.plannedTonnes,3)} t`:'—'} result/></View><PavementAdvancedSections areaM2={area} plannedTonnes={result?.plannedTonnes??0} onUseArea={value=>setForm({...form,directArea:value.toFixed(2)})}/><AppField label="Notes" value={form.notes} onChangeText={notes=>setForm({...form,notes})} multiline placeholder="Mix, station limits, exclusions, or site notes"/><AppButton label={editingId?'Update Calculation':'Save Under Project'} busy={busy} disabled={!result||!form.projectId||!form.name.trim()} onPress={()=>void save()}/>{editingId?<AppButton label="Cancel Editing" tone="secondary" disabled={busy} onPress={()=>{setEditingId(null);setForm(empty(initialProjectId??form.projectId));}}/>:null}
    <AppCard title="Saved pavement calculations" hint={form.projectId?'Showing this project’s saved layers and sections.':'Choose a project above or review all saved calculations.'}><View style={styles.metrics}><MetricCard label="Saved calculations" value={String(visible.length)} result/><MetricCard label="Combined entered area" value={`${format(totalArea,2)} m²`} result/><MetricCard label="Combined planned asphalt" value={`${format(totalPlanned,3)} t`} result/></View>{visible.length?<View style={styles.exportRow}><View style={styles.half}><AppButton label="Export PDF" tone="navy" disabled={busy} onPress={()=>void runExport('pdf')}/></View><View style={styles.half}><AppButton label="Export Excel" tone="secondary" disabled={busy} onPress={()=>void runExport('excel')}/></View></View>:null}{visible.length?visible.map(record=><TouchableOpacity key={record.id} style={styles.record} onPress={()=>edit(record)}><View style={styles.recordTop}><View style={styles.flex}><Text style={styles.recordProject}>{record.projectName.toUpperCase()}</Text><Text style={styles.recordTitle}>{record.name}</Text></View><Text style={styles.edit}>Edit ›</Text></View><View style={styles.recordNumbers}><Text style={styles.recordStrong}>{format(record.spreadRateKgM2,0)} kg/m²</Text><Text style={styles.recordStrong}>{format(record.thicknessMm,1)} mm finished</Text>{record.looseThicknessMm!==null?<Text style={styles.recordStrong}>{format(record.looseThicknessMm,1)} mm loose</Text>:null}<Text style={styles.recordStrong}>{format(record.plannedKg/1000,3)} t planned</Text></View><Text style={styles.recordDetail}>{format(record.areaM2,2)} m² · {format(record.densityTM3,2)} t/m³{record.looseThicknessFactor!==null?` · ${format(record.looseThicknessFactor,2)}× loose factor`:''} · {format(record.allowancePercent,1)}% allowance</Text></TouchableOpacity>):<EmptyState title="No saved calculations" body="Your project-linked asphalt layers and quantities will appear here."/>}</AppCard>
  </AppPage>;
}

const styles=StyleSheet.create({formula:{color:'#FFF8ED',fontSize:14,fontWeight:'900'},locked:{backgroundColor:'#FFF8ED',borderRadius:12,padding:13,gap:3},lockedLabel:{color:colors.brandDark,fontSize:9,fontWeight:'900',letterSpacing:1},lockedValue:{color:colors.ink,fontSize:16,fontWeight:'900'},two:{flexDirection:'row',gap:10},half:{flex:1},exportRow:{flexDirection:'row',gap:10},or:{flexDirection:'row',alignItems:'center',gap:10},line:{flex:1,height:1,backgroundColor:colors.line},orText:{color:colors.muted,fontSize:9,fontWeight:'900'},areaBand:{backgroundColor:colors.result,borderWidth:2,borderColor:colors.resultDark,borderRadius:13,padding:15,flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:10},areaLabel:{color:colors.resultSoft,fontSize:9,fontWeight:'900',letterSpacing:.8},areaValue:{color:'#FFF',fontSize:22,fontWeight:'900'},factorNote:{color:colors.resultDark,backgroundColor:colors.resultSoft,borderRadius:10,padding:10,fontSize:11,fontWeight:'700',lineHeight:16},metrics:{flexDirection:'row',flexWrap:'wrap',gap:8},record:{backgroundColor:colors.surface,borderRadius:13,padding:14,gap:9,borderLeftWidth:4,borderLeftColor:colors.brand},recordTop:{flexDirection:'row',gap:10},flex:{flex:1,minWidth:0},recordProject:{color:colors.brand,fontSize:8,fontWeight:'900',letterSpacing:.7},recordTitle:{color:colors.ink,fontSize:16,fontWeight:'900',marginTop:2},edit:{color:colors.navy,fontSize:11,fontWeight:'900'},recordNumbers:{flexDirection:'row',flexWrap:'wrap',gap:7},recordStrong:{color:'#FFF',backgroundColor:colors.result,borderRadius:9,paddingHorizontal:8,paddingVertical:5,fontSize:11,fontWeight:'900'},recordDetail:{color:colors.muted,fontSize:11}});
