import { useCallback, useEffect, useState } from 'react';
import { ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';

import type { DirectoryProfiles, LoadRepository } from '../../data/repositories/LoadRepository';
import { colors } from '../theme';

type TabName = 'workers' | 'drivers' | 'trucks' | 'machines';

export function PeopleEquipmentScreen({ repository, onBack }: { repository: LoadRepository; onBack: () => void }) {
  const [options, setOptions] = useState<DirectoryProfiles | null>(null); const [tab, setTab] = useState<TabName>('workers');
  const [workerName,setWorkerName]=useState(''); const [workerRole,setWorkerRole]=useState(''); const [workerPhone,setWorkerPhone]=useState(''); const [workerNotes,setWorkerNotes]=useState('');
  const [driverName,setDriverName]=useState(''); const [driverPhone,setDriverPhone]=useState(''); const [license,setLicense]=useState(''); const [driverNotes,setDriverNotes]=useState('');
  const [plate,setPlate]=useState(''); const [makeModel,setMakeModel]=useState(''); const [capacity,setCapacity]=useState(''); const [owner,setOwner]=useState(''); const [truckNotes,setTruckNotes]=useState('');
  const [machineName,setMachineName]=useState(''); const [machineType,setMachineType]=useState(''); const [identifier,setIdentifier]=useState(''); const [machineNotes,setMachineNotes]=useState('');
  const [error,setError]=useState<string|null>(null); const [message,setMessage]=useState<string|null>(null); const [busy,setBusy]=useState(false);
  const refresh=useCallback(async()=>setOptions(await repository.getDirectoryProfiles()),[repository]); useEffect(()=>{void refresh();},[refresh]);
  async function execute(action:()=>Promise<void>, success:string){setBusy(true);setError(null);setMessage(null);try{await action();await refresh();setMessage(success);}catch(cause){setError(cause instanceof Error?cause.message:'Could not save the record.');}finally{setBusy(false);}}
  function saveWorker(){return execute(async()=>{await repository.createWorker({name:workerName,role:workerRole,phone:workerPhone,notes:workerNotes});setWorkerName('');setWorkerRole('');setWorkerPhone('');setWorkerNotes('');},'Worker saved and available in Project Reports.');}
  function saveDriver(){return execute(async()=>{await repository.createDriver({name:driverName,phone:driverPhone,licenseNumber:license,notes:driverNotes});setDriverName('');setDriverPhone('');setLicense('');setDriverNotes('');},'Driver saved and available in loads and Project Reports.');}
  function saveTruck(){return execute(async()=>{await repository.createTruck({plate,makeModel,capacityKg:capacity.trim()?Number(capacity):null,ownerName:owner,notes:truckNotes});setPlate('');setMakeModel('');setCapacity('');setOwner('');setTruckNotes('');},'Truck saved and available in loads and Project Reports.');}
  function saveMachine(){return execute(async()=>{await repository.createMachine({name:machineName,machineType,identifier,notes:machineNotes});setMachineName('');setMachineType('');setIdentifier('');setMachineNotes('');},'Machine saved and available in Project Reports.');}
  function toggle(kind:TabName,id:string,isActive:boolean){const action=kind==='workers'?repository.setWorkerActive(id,isActive):kind==='drivers'?repository.setDriverActive(id,isActive):kind==='trucks'?repository.setTruckActive(id,isActive):repository.setMachineActive(id,isActive);return execute(()=>action,isActive?'Profile reactivated.':'Profile deactivated and removed from new-entry selections.');}
  return <ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled">
    <View style={styles.header}><TouchableOpacity style={styles.back} onPress={onBack}><Text style={styles.backText}>Back</Text></TouchableOpacity><View style={styles.flex}><Text style={styles.eyebrow}>DIRECTORY</Text><Text style={styles.title}>People & equipment</Text></View></View>
    <Text style={styles.helper}>Create reusable workers, drivers, trucks, and machines, then choose them from searchable dropdowns.</Text>
    {error?<Text style={styles.error}>{error}</Text>:null}{message?<Text style={styles.success}>{message}</Text>:null}
    <View style={styles.tabs}><Tab label="Workers" selected={tab==='workers'} onPress={()=>setTab('workers')}/><Tab label="Drivers" selected={tab==='drivers'} onPress={()=>setTab('drivers')}/><Tab label="Trucks" selected={tab==='trucks'} onPress={()=>setTab('trucks')}/><Tab label="Machines" selected={tab==='machines'} onPress={()=>setTab('machines')}/></View>
    {tab==='workers'?<><Card title="Add worker"><Field label="Worker name *" value={workerName} onChangeText={setWorkerName}/><Field label="Role / trade" value={workerRole} onChangeText={setWorkerRole}/><Field label="Phone" value={workerPhone} onChangeText={setWorkerPhone} keyboardType="phone-pad"/><Field label="Notes" value={workerNotes} onChangeText={setWorkerNotes} multiline/><Save label="Save worker" busy={busy} onPress={()=>void saveWorker()}/></Card><Heading text={`Saved workers (${options?.workers.length??0})`}/>{options?.workers.map((v)=><Record key={v.id} title={v.name} detail={[v.role,v.phone].filter(Boolean).join(' · ')} notes={v.notes} isActive={v.isActive} busy={busy} onToggle={()=>void toggle('workers',v.id,!v.isActive)}/>)}</>:null}
    {tab==='drivers'?<><Card title="Add driver"><Field label="Driver name *" value={driverName} onChangeText={setDriverName}/><Field label="Phone" value={driverPhone} onChangeText={setDriverPhone} keyboardType="phone-pad"/><Field label="Licence number" value={license} onChangeText={setLicense}/><Field label="Notes" value={driverNotes} onChangeText={setDriverNotes} multiline/><Save label="Save driver" busy={busy} onPress={()=>void saveDriver()}/></Card><Heading text={`Saved drivers (${options?.drivers.length??0})`}/>{options?.drivers.map((v)=><Record key={v.id} title={v.name} detail={[v.phone,v.licenseNumber?`Licence ${v.licenseNumber}`:null].filter(Boolean).join(' · ')} notes={v.notes} isActive={v.isActive} busy={busy} onToggle={()=>void toggle('drivers',v.id,!v.isActive)}/>)}</>:null}
    {tab==='trucks'?<><Card title="Add truck"><Field label="Number plate *" value={plate} onChangeText={setPlate} autoCapitalize="characters"/><Field label="Make / model" value={makeModel} onChangeText={setMakeModel}/><Field label="Capacity kg" value={capacity} onChangeText={setCapacity} keyboardType="number-pad"/><Field label="Owner / company" value={owner} onChangeText={setOwner}/><Field label="Notes" value={truckNotes} onChangeText={setTruckNotes} multiline/><Save label="Save truck" busy={busy} onPress={()=>void saveTruck()}/></Card><Heading text={`Saved trucks (${options?.trucks.length??0})`}/>{options?.trucks.map((v)=><Record key={v.id} title={v.plate} detail={[v.makeModel,v.capacityKg?`${v.capacityKg} kg capacity`:null,v.ownerName].filter(Boolean).join(' · ')} notes={v.notes} isActive={v.isActive} busy={busy} onToggle={()=>void toggle('trucks',v.id,!v.isActive)}/>)}</>:null}
    {tab==='machines'?<><Card title="Add machine"><Field label="Machine name *" value={machineName} onChangeText={setMachineName}/><Field label="Type / make / model" value={machineType} onChangeText={setMachineType}/><Field label="Identifier / serial / plate" value={identifier} onChangeText={setIdentifier}/><Field label="Notes" value={machineNotes} onChangeText={setMachineNotes} multiline/><Save label="Save machine" busy={busy} onPress={()=>void saveMachine()}/></Card><Heading text={`Saved machines (${options?.machines.length??0})`}/>{options?.machines.map((v)=><Record key={v.id} title={v.name} detail={[v.machineType,v.identifier].filter(Boolean).join(' · ')} notes={v.notes} isActive={v.isActive} busy={busy} onToggle={()=>void toggle('machines',v.id,!v.isActive)}/>)}</>:null}
  </ScrollView>;
}

function Tab({label,selected,onPress}:{label:string;selected:boolean;onPress:()=>void}){return <TouchableOpacity style={[styles.tab,selected&&styles.tabSelected]} onPress={onPress}><Text style={[styles.tabText,selected&&styles.tabTextSelected]}>{label}</Text></TouchableOpacity>;}
function Card({title,children}:{title:string;children:React.ReactNode}){return <View style={styles.card}><Text style={styles.cardTitle}>{title}</Text>{children}</View>;}
function Heading({text}:{text:string}){return <Text style={styles.sectionTitle}>{text}</Text>;}
function Record({title,detail,notes,isActive,busy,onToggle}:{title:string;detail:string;notes:string|null;isActive:boolean;busy:boolean;onToggle:()=>void}){return <View style={[styles.record,!isActive&&styles.recordInactive]}><View style={styles.recordHeading}><Text style={styles.recordTitle}>{title}</Text><Text style={[styles.status,isActive?styles.statusActive:styles.statusInactive]}>{isActive?'ACTIVE':'INACTIVE'}</Text></View><Text style={styles.helper}>{detail||'No additional information'}</Text>{notes?<Text style={styles.notes}>{notes}</Text>:null}<TouchableOpacity style={styles.toggle} disabled={busy} onPress={onToggle}><Text style={styles.toggleText}>{isActive?'Deactivate':'Reactivate'}</Text></TouchableOpacity></View>;}
function Field({label,...props}:{label:string;value:string;onChangeText:(value:string)=>void;multiline?:boolean;keyboardType?:'default'|'phone-pad'|'number-pad';autoCapitalize?:'none'|'sentences'|'characters'}){return <View style={styles.field}><Text style={styles.label}>{label}</Text><TextInput style={[styles.input,props.multiline&&styles.multiline]} placeholderTextColor="#89939B" {...props}/></View>;}
function Save({label,busy,onPress}:{label:string;busy:boolean;onPress:()=>void}){return <TouchableOpacity style={styles.save} disabled={busy} onPress={onPress}><Text style={styles.saveText}>{busy?'Saving…':label}</Text></TouchableOpacity>;}

const styles=StyleSheet.create({content:{padding:20,paddingBottom:42,gap:15},header:{flexDirection:'row',alignItems:'center',gap:14},flex:{flex:1},back:{backgroundColor:colors.surface,padding:10,borderRadius:10},backText:{color:colors.ink,fontWeight:'800'},eyebrow:{color:colors.brand,fontSize:11,fontWeight:'900',letterSpacing:1.4},title:{color:colors.ink,fontSize:27,fontWeight:'900'},helper:{color:colors.muted,fontSize:12,lineHeight:18},error:{color:colors.danger,backgroundColor:'#FCE8E6',padding:12,borderRadius:10},success:{color:colors.success,backgroundColor:'#E5F3EC',padding:12,borderRadius:10,fontWeight:'700'},tabs:{flexDirection:'row',flexWrap:'wrap',gap:8},tab:{width:'48%',flexGrow:1,borderWidth:1,borderColor:colors.line,padding:11,borderRadius:10,alignItems:'center',backgroundColor:colors.surface},tabSelected:{borderColor:colors.brand,backgroundColor:'#FBE9E4'},tabText:{color:colors.muted,fontWeight:'800'},tabTextSelected:{color:colors.brandDark},card:{backgroundColor:colors.surface,borderRadius:16,padding:17,gap:12},cardTitle:{color:colors.ink,fontSize:19,fontWeight:'900'},field:{gap:6},label:{color:colors.ink,fontSize:13,fontWeight:'800'},input:{borderWidth:1,borderColor:colors.line,borderRadius:11,paddingHorizontal:13,paddingVertical:11,color:colors.ink,backgroundColor:'#FCFBF8'},multiline:{minHeight:70,textAlignVertical:'top'},save:{backgroundColor:colors.ink,borderRadius:11,padding:14,alignItems:'center'},saveText:{color:'#FFF',fontWeight:'900'},sectionTitle:{color:colors.ink,fontSize:18,fontWeight:'900'},record:{backgroundColor:colors.surface,borderRadius:13,padding:14,gap:5},recordInactive:{opacity:.72,borderWidth:1,borderColor:colors.line},recordHeading:{flexDirection:'row',alignItems:'center',gap:8},recordTitle:{flex:1,color:colors.ink,fontSize:16,fontWeight:'900'},status:{fontSize:9,fontWeight:'900',paddingHorizontal:7,paddingVertical:4,borderRadius:9,overflow:'hidden'},statusActive:{color:colors.success,backgroundColor:'#E5F3EC'},statusInactive:{color:colors.muted,backgroundColor:'#EEEAE3'},toggle:{alignSelf:'flex-start',marginTop:6,borderWidth:1,borderColor:colors.navy,borderRadius:9,paddingHorizontal:11,paddingVertical:7},toggleText:{color:colors.navy,fontSize:11,fontWeight:'900'},notes:{color:colors.muted,fontSize:12,fontStyle:'italic',marginTop:3}});
