import {useCallback,useEffect,useState} from 'react';
import {Image,StyleSheet,Text,TouchableOpacity,View} from 'react-native';
import type {WorkspaceRepository} from '../../data/repositories/WorkspaceRepository';
import type {Project} from '../../domain/loads';
import {emptyWorkspaceIssue,type ProjectWorkspaceSnapshot,type WorkspaceIssueDraft} from '../../domain/workspace';
import {capturePersistentImage,pickPersistentImage} from '../../services/media';
import {AppButton,AppCard,AppField,AppPage,EmptyState,Feedback,MetricCard,PageHeader} from '../components/AppPrimitives';
import {DatePickerField} from '../components/DatePickerField';
import {ExpandableMenuSection,MenuAction} from '../components/ExpandableMenu';
import {colors} from '../theme';

type Routes={onSchedule:()=>void;onPavement:()=>void;onWalls:()=>void;onDailyReport:()=>void;onReceipt:()=>void;onWaste:()=>void;onFuel:()=>void;onQuarry:()=>void;onQuickText:()=>void;onLoads:()=>void;onReports:()=>void;onManageProject:()=>void};

export function ProjectCommandCenterScreen({project,repository,routes,onBack,initialPanel}:{project:Project;repository:WorkspaceRepository;routes:Routes;onBack:()=>void;initialPanel?:'issues'|'photos'|null}){
  const[snapshot,setSnapshot]=useState<ProjectWorkspaceSnapshot|null>(null);const[open,setOpen]=useState<Set<string>>(()=>new Set(initialPanel?[initialPanel]:[]));const[issueDraft,setIssueDraft]=useState<WorkspaceIssueDraft>(emptyWorkspaceIssue);const[showIssueForm,setShowIssueForm]=useState(initialPanel==='issues');const[photoCaption,setPhotoCaption]=useState('');const[busy,setBusy]=useState(false);const[error,setError]=useState<string|null>(null);const[message,setMessage]=useState<string|null>(null);
  const refresh=useCallback(async()=>setSnapshot(await repository.getProjectWorkspace(project.id)),[project.id,repository]);useEffect(()=>{void refresh().catch(cause=>setError(cause instanceof Error?cause.message:'Could not load the project command center.'));},[refresh]);
  const toggle=(key:string)=>setOpen(current=>{const next=new Set(current);if(next.has(key))next.delete(key);else next.add(key);return next;});
  async function run(action:()=>Promise<void>,success:string){setBusy(true);setError(null);setMessage(null);try{await action();await refresh();setMessage(success);}catch(cause){setError(cause instanceof Error?cause.message:'The project action could not be completed.');}finally{setBusy(false);}}
  function addIssue(){void run(async()=>{await repository.createIssue(project.id,issueDraft);setIssueDraft(emptyWorkspaceIssue);setShowIssueForm(false);},'Project issue added.');}
  function resolveIssue(id:string,resolved:boolean){void run(()=>repository.setIssueResolved(id,resolved),resolved?'Issue resolved.':'Issue reopened.');}
  async function addPhoto(source:'camera'|'library'){setBusy(true);setError(null);try{const uri=source==='camera'?await capturePersistentImage('project-workspace'):await pickPersistentImage('project-workspace');if(!uri)return;await repository.addProjectPhoto(project.id,uri,photoCaption);setPhotoCaption('');await refresh();setMessage('Site photo added to the project.');}catch(cause){setError(cause instanceof Error?cause.message:'Could not add the project photo.');}finally{setBusy(false);}}
  if(!snapshot)return <View style={styles.loading}><Text style={styles.helper}>Loading {project.name}…</Text></View>;
  const m=snapshot.metrics;return <AppPage keyboard><PageHeader eyebrow="PROJECT COMMAND CENTER" title={project.name} onBack={onBack}/><AppCard tone="navy" title={project.name} hint={`${project.customerName} · ${project.location}`}><View style={styles.heroRow}><View style={[styles.status,project.status==='completed'&&styles.completed]}><Text style={styles.statusText}>{project.status.toUpperCase()}</Text></View><TouchableOpacity onPress={routes.onManageProject}><Text style={styles.manage}>Manage project ›</Text></TouchableOpacity></View>{project.notes?<Text style={styles.heroNotes}>{project.notes}</Text>:null}</AppCard>{project.status==='completed'?<Feedback kind="warning">This project is read-only. Reactivate it from Projects before adding new work, issues, or photos.</Feedback>:null}{error?<Feedback kind="error">{error}</Feedback>:null}{message?<Feedback kind="success">{message}</Feedback>:null}
    <View style={styles.metrics}><MetricCard label="Loads" value={String(m.loads)} accent/><MetricCard label="Delivered" value={`${m.netTonnes.toFixed(1)} t`}/><MetricCard label="Daily reports" value={String(m.dailyReports)}/><MetricCard label="Waste dumps" value={String(m.wasteDumps)}/><MetricCard label="Fuel used" value={`${m.fuelLitres.toFixed(0)} L`}/><MetricCard label="Quarry purchases" value={String(m.quarryPurchases)}/><MetricCard label="Open schedule" value={String(m.scheduled)}/><MetricCard label="Pavement calculations" value={String(m.pavementCalculations)}/><MetricCard label="Walls" value={String(m.walls)}/><MetricCard label="Open issues" value={String(m.openIssues)} accent={m.openIssues>0}/></View>
    <ExpandableMenuSection title="Planning and Today" hint="Open the project plan, calculate construction quantities, or record today’s work." open={open.has('planning')} onToggle={()=>toggle('planning')}><MenuAction number="01" title="Project Schedule" body="All tasks stay locked under this project." onPress={routes.onSchedule}/><MenuAction number="02" title="Asphalt Pavement Calculator" body="Choose kg/m² and save this project’s layer quantities." onPress={routes.onPavement}/><MenuAction number="03" title="Wall Construction" body="Calculate walls and record actual concrete, steel, stone, and site-mix consumption." onPress={routes.onWalls}/><MenuAction number="04" title="Make Daily Report" body="Record work, people, materials, issues, time, and photos." onPress={routes.onDailyReport}/><MenuAction number="05" title="Make Receipt" body="Start a load with this project already selected." onPress={routes.onReceipt}/></ExpandableMenuSection>
    <ExpandableMenuSection title="Field Operations" hint="Fast project-linked entries for site and plant work." tone="orange" open={open.has('operations')} onToggle={()=>toggle('operations')}><MenuAction number="01" title="Waste Dumps" body="Open this project’s driver/truck counters and history." onPress={routes.onWaste} tone="cream"/><MenuAction number="02" title="Equipment Fuel" body="Record equipment fills under this project." onPress={routes.onFuel} tone="cream"/><MenuAction number="03" title="Quarry Purchases" body="Record incoming material for this project." onPress={routes.onQuarry} tone="cream"/><MenuAction number="04" title="Quick Text" body="Create a project-linked company document." onPress={routes.onQuickText} tone="cream"/></ExpandableMenuSection>
    <ExpandableMenuSection title="Issues" hint={`${m.openIssues} open · record blockers, delays, and follow-up work.`} tone="cream" open={open.has('issues')} onToggle={()=>toggle('issues')}>{project.status==='active'?<AppButton label={showIssueForm?'Close Issue Form':'+ Add Project Issue'} onPress={()=>setShowIssueForm(value=>!value)}/>:null}{showIssueForm?<AppCard title="New project issue" hint="Use a short title and only the detail needed for follow-up."><AppField label="Issue title *" value={issueDraft.title} onChangeText={value=>setIssueDraft({...issueDraft,title:value})}/><AppField label="Description" value={issueDraft.description} onChangeText={value=>setIssueDraft({...issueDraft,description:value})} multiline/><Text style={styles.label}>Priority</Text><View style={styles.priorityRow}>{(['Low','Normal','High','Urgent'] as const).map(priority=><TouchableOpacity key={priority} style={[styles.priority,issueDraft.priority===priority&&styles.priorityOn]} onPress={()=>setIssueDraft({...issueDraft,priority})}><Text style={[styles.priorityText,issueDraft.priority===priority&&styles.priorityTextOn]}>{priority}</Text></TouchableOpacity>)}</View><DatePickerField label="Due date" value={issueDraft.dueDate} onChange={value=>setIssueDraft({...issueDraft,dueDate:value})} allowClear/><AppButton label="Save Issue" busy={busy} onPress={addIssue}/></AppCard>:null}{snapshot.issues.length?snapshot.issues.map(item=><View key={item.id} style={[styles.issue,item.status==='Resolved'&&styles.issueResolved]}><View style={styles.issueTop}><View style={styles.flex}><Text style={styles.issuePriority}>{item.priority.toUpperCase()}</Text><Text style={styles.issueTitle}>{item.title}</Text></View><Text style={[styles.issueStatus,item.status==='Resolved'&&styles.resolvedText]}>{item.status}</Text></View>{item.description?<Text style={styles.helper}>{item.description}</Text>:null}{item.dueDate?<Text style={styles.issueDue}>Due {item.dueDate}</Text>:null}{project.status==='active'?<AppButton label={item.status==='Open'?'Resolve Issue':'Reopen Issue'} tone="secondary" disabled={busy} onPress={()=>resolveIssue(item.id,item.status==='Open')}/>:null}</View>):<EmptyState title="No project issues" body="Open issues and resolved follow-ups will be kept here."/>}</ExpandableMenuSection>
    <ExpandableMenuSection title="Photos" hint={`${snapshot.photos.length} site photo${snapshot.photos.length===1?'':'s'} saved directly under this project.`} open={open.has('photos')} onToggle={()=>toggle('photos')}>{project.status==='active'?<><AppField label="Photo caption" value={photoCaption} onChangeText={setPhotoCaption} placeholder="Area, activity, or reason for the photo"/><View style={styles.photoActions}><AppButton label="Take Site Photo" tone="navy" busy={busy} onPress={()=>void addPhoto('camera')}/><AppButton label="Choose Photo" tone="secondary" disabled={busy} onPress={()=>void addPhoto('library')}/></View></>:null}{snapshot.photos.length?<View style={styles.photoGrid}>{snapshot.photos.map(value=><View key={value.id} style={styles.photoCard}><Image source={{uri:value.uri}} style={styles.photo}/><Text style={styles.photoCaption}>{value.caption??'Site photo'}</Text><Text style={styles.photoDate}>{new Date(value.createdAt).toLocaleString()}</Text></View>)}</View>:<EmptyState title="No project photos" body="Add site evidence here or keep detailed daily-report photos in Daily Reports."/>}</ExpandableMenuSection>
    <ExpandableMenuSection title="Activity" hint="Loads, reports, waste, fuel, quarry, plans, issues, and photos in one timeline." tone="orange" open={open.has('activity')} onToggle={()=>toggle('activity')}>{snapshot.activities.length?snapshot.activities.map(value=><View key={`${value.type}-${value.id}-${value.occurredAt}`} style={styles.activity}><View style={styles.timelineDot}/><View style={styles.flex}><Text style={styles.activityType}>{value.type.toUpperCase()}</Text><Text style={styles.activityTitle}>{value.title}</Text>{value.detail?<Text style={styles.helper}>{value.detail}</Text>:null}<Text style={styles.activityDate}>{new Date(value.occurredAt).toLocaleString()}</Text></View></View>):<EmptyState title="No project activity" body="New project-linked records will appear here automatically."/>}</ExpandableMenuSection>
    <ExpandableMenuSection title="Records and Documents" hint="Open project loads, reports, PDFs, and Excel output." tone="cream" open={open.has('documents')} onToggle={()=>toggle('documents')}><MenuAction number="01" title="Project Load Records" body="Open confirmed loads and documents." onPress={routes.onLoads}/><MenuAction number="02" title="Project Reports" body="Daily history, completed-project PDF, and Excel exports." onPress={routes.onReports}/></ExpandableMenuSection>
  </AppPage>;
}

const styles=StyleSheet.create({loading:{flex:1,alignItems:'center',justifyContent:'center'},helper:{color:colors.muted,fontSize:12,lineHeight:18},heroRow:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',gap:10,borderTopWidth:StyleSheet.hairlineWidth,borderTopColor:'#6F8FA9',paddingTop:11},status:{backgroundColor:colors.success,borderRadius:12,paddingHorizontal:9,paddingVertical:5},completed:{backgroundColor:'#6E7680'},statusText:{color:'#FFF',fontSize:9,fontWeight:'900'},manage:{color:'#F2A184',fontWeight:'900',fontSize:11},heroNotes:{color:'#E8E2D7',fontSize:12,fontStyle:'italic'},metrics:{flexDirection:'row',flexWrap:'wrap',gap:8},label:{color:colors.ink,fontSize:13,fontWeight:'800'},priorityRow:{flexDirection:'row',flexWrap:'wrap',gap:7},priority:{flex:1,minWidth:68,borderWidth:1,borderColor:colors.line,borderRadius:10,padding:10,alignItems:'center'},priorityOn:{backgroundColor:colors.navy,borderColor:colors.navy},priorityText:{color:colors.muted,fontSize:11,fontWeight:'900'},priorityTextOn:{color:'#FFF'},issue:{backgroundColor:colors.surface,borderRadius:13,padding:14,gap:8,borderLeftWidth:4,borderLeftColor:colors.brand},issueResolved:{borderLeftColor:colors.success,opacity:.78},issueTop:{flexDirection:'row',gap:10},flex:{flex:1,minWidth:0},issuePriority:{color:colors.brand,fontSize:8,fontWeight:'900',letterSpacing:.7},issueTitle:{color:colors.ink,fontSize:16,fontWeight:'900',marginTop:2},issueStatus:{color:colors.danger,fontSize:10,fontWeight:'900'},resolvedText:{color:colors.success},issueDue:{color:colors.warning,fontSize:11,fontWeight:'800'},photoActions:{gap:8},photoGrid:{flexDirection:'row',flexWrap:'wrap',gap:10},photoCard:{width:'47%',backgroundColor:colors.surface,borderRadius:12,overflow:'hidden',paddingBottom:9},photo:{width:'100%',height:125,backgroundColor:'#EEE'},photoCaption:{color:colors.ink,fontSize:11,fontWeight:'900',paddingHorizontal:9,marginTop:7},photoDate:{color:colors.muted,fontSize:8,paddingHorizontal:9,marginTop:3},activity:{backgroundColor:colors.surface,borderRadius:12,padding:13,flexDirection:'row',gap:10},timelineDot:{width:10,height:10,borderRadius:5,backgroundColor:colors.brand,marginTop:4},activityType:{color:colors.brand,fontSize:8,fontWeight:'900',letterSpacing:.7},activityTitle:{color:colors.ink,fontSize:14,fontWeight:'900',marginTop:2},activityDate:{color:colors.muted,fontSize:9,marginTop:3}});
