import { useCallback, useEffect, useState } from 'react';
import { ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import type { LoadRepository } from '../../data/repositories/LoadRepository';
import type { LoadSetupOptions, Project } from '../../domain/loads';
import { SearchableSelect } from '../components/SearchableSelect';
import { colors } from '../theme';

export function ProjectsScreen({repository,onBack,onOpenProject,onProjectStatusChange}:{repository:LoadRepository;onBack:()=>void;onOpenProject:(project:Project)=>void;onProjectStatusChange?:(project:Project,status:Project['status'])=>void}){
  const [setup,setSetup]=useState<LoadSetupOptions|null>(null); const [projects,setProjects]=useState<Project[]>([]); const [showForm,setShowForm]=useState(false);
  const [customerId,setCustomerId]=useState(''); const [name,setName]=useState(''); const [location,setLocation]=useState(''); const [notes,setNotes]=useState('');
  const [error,setError]=useState<string|null>(null); const [message,setMessage]=useState<string|null>(null); const [busy,setBusy]=useState(false);
  const refresh=useCallback(async()=>{const [nextSetup,nextProjects]=await Promise.all([repository.getSetupOptions(),repository.listProjects()]);setSetup(nextSetup);setProjects(nextProjects);},[repository]);
  useEffect(()=>{void refresh();},[refresh]);
  async function create(){setBusy(true);setError(null);setMessage(null);try{await repository.createProject({customerId,name,location,notes});await refresh();setCustomerId('');setName('');setLocation('');setNotes('');setShowForm(false);setMessage('Project created and available in Reports.');}catch(cause){setError(cause instanceof Error?cause.message:'Could not create project.');}finally{setBusy(false);}}
  async function changeStatus(project:Project){setBusy(true);setError(null);try{const next=project.status==='active'?'completed':'active';await repository.updateProjectStatus(project.id,next);onProjectStatusChange?.(project,next);await refresh();setMessage(next==='completed'?'Project marked completed.':'Project reactivated and available for new reports.');}catch(cause){setError(cause instanceof Error?cause.message:'Could not update project.');}finally{setBusy(false);}}
  if(!setup)return <View style={styles.loading}><Text style={styles.helper}>Loading projects…</Text></View>;
  const active=projects.filter((v)=>v.status==='active'); const completed=projects.filter((v)=>v.status==='completed');
  return <ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><Header onBack={onBack}/><Text style={styles.helper}>Projects are managed here. Active projects are selectable in Make Receipt and Reports.</Text>{error?<Text style={styles.error}>{error}</Text>:null}{message?<Text style={styles.success}>{message}</Text>:null}
    <TouchableOpacity style={styles.primary} onPress={()=>setShowForm(!showForm)}><Text style={styles.primaryText}>{showForm?'Close form':'Create Project'}</Text></TouchableOpacity>
    {showForm?<View style={styles.card}><Text style={styles.cardTitle}>New project</Text><SearchableSelect label="Customer / company *" options={setup.customers.map((c)=>({id:c.id,label:c.name,detail:c.isOwnCompany?'Own company':c.type}))} selectedId={customerId} onSelect={setCustomerId}/><Field label="Project name *" value={name} onChangeText={setName}/><Field label="Location / destination *" value={location} onChangeText={setLocation} multiline/><Field label="Notes" value={notes} onChangeText={setNotes} multiline/><TouchableOpacity style={styles.save} disabled={busy} onPress={()=>void create()}><Text style={styles.saveText}>{busy?'Saving…':'Save Project'}</Text></TouchableOpacity></View>:null}
    <Text style={styles.sectionTitle}>Active Projects</Text>{active.length?active.map((p)=><ProjectCard key={p.id} project={p} busy={busy} onOpenProject={()=>onOpenProject(p)} onStatus={()=>void changeStatus(p)}/>):<Empty text="No active projects. Create one above."/>}
    <Text style={styles.sectionTitle}>Completed Projects</Text>{completed.length?completed.map((p)=><ProjectCard key={p.id} project={p} busy={busy} onOpenProject={()=>onOpenProject(p)} onStatus={()=>void changeStatus(p)}/>):<Text style={styles.helper}>No completed projects.</Text>}
  </ScrollView>;
}
function Header({onBack}:{onBack:()=>void}){return <View style={styles.header}><TouchableOpacity onPress={onBack} style={styles.back}><Text style={styles.backText}>Back</Text></TouchableOpacity><View><Text style={styles.eyebrow}>DIRECTORY</Text><Text style={styles.title}>Projects</Text></View></View>}
function ProjectCard({project,busy,onOpenProject,onStatus}:{project:Project;busy:boolean;onOpenProject:()=>void;onStatus:()=>void}){return <View style={styles.card}><View style={styles.row}><TouchableOpacity activeOpacity={.68} style={styles.flex} onPress={onOpenProject} accessibilityRole="button" accessibilityLabel={`Open ${project.name} command center`}><Text style={styles.cardTitle}>{project.name}</Text><Text style={styles.scheduleLink}>Open project workspace →</Text><Text style={styles.helper}>{project.customerName}</Text><Text style={styles.helper}>{project.location}</Text>{project.notes?<Text style={styles.notes}>{project.notes}</Text>:null}</TouchableOpacity><View style={[styles.badge,project.status==='completed'&&styles.badgeCompleted]}><Text style={styles.badgeText}>{project.status}</Text></View></View><TouchableOpacity style={styles.outline} disabled={busy} onPress={onStatus}><Text style={styles.outlineText}>{project.status==='active'?'Mark Completed':'Reactivate Project'}</Text></TouchableOpacity></View>}
function Empty({text}:{text:string}){return <View style={styles.empty}><Text style={styles.helper}>{text}</Text></View>}
function Field({label,...props}:{label:string;value:string;onChangeText:(v:string)=>void;multiline?:boolean}){return <View style={styles.field}><Text style={styles.label}>{label}</Text><TextInput style={[styles.input,props.multiline&&styles.multiline]} placeholderTextColor="#89939B" {...props}/></View>}
const styles=StyleSheet.create({loading:{flex:1,alignItems:'center',justifyContent:'center'},content:{padding:20,paddingBottom:42,gap:16},header:{flexDirection:'row',alignItems:'center',gap:14},back:{backgroundColor:colors.surface,padding:10,borderRadius:10},backText:{color:colors.ink,fontWeight:'800'},eyebrow:{color:colors.brand,fontSize:11,fontWeight:'900',letterSpacing:1.4},title:{color:colors.ink,fontSize:29,fontWeight:'900'},helper:{color:colors.muted,fontSize:13,lineHeight:19},primary:{backgroundColor:colors.brand,borderRadius:14,padding:15,alignItems:'center'},primaryText:{color:'#FFF',fontSize:17,fontWeight:'900'},sectionTitle:{color:colors.ink,fontSize:19,fontWeight:'900'},card:{backgroundColor:colors.surface,borderRadius:16,padding:17,gap:12},cardTitle:{color:colors.ink,fontSize:17,fontWeight:'900'},scheduleLink:{color:colors.brand,fontSize:12,fontWeight:'900',marginTop:4,marginBottom:5},field:{gap:6},label:{color:colors.ink,fontSize:13,fontWeight:'800'},input:{borderWidth:1,borderColor:colors.line,borderRadius:11,paddingHorizontal:13,paddingVertical:11,color:colors.ink,backgroundColor:'#FCFBF8'},multiline:{minHeight:72,textAlignVertical:'top'},save:{backgroundColor:colors.ink,borderRadius:11,padding:13,alignItems:'center'},saveText:{color:'#FFF',fontWeight:'900'},row:{flexDirection:'row',gap:10},flex:{flex:1},badge:{alignSelf:'flex-start',backgroundColor:'#E5F3EC',borderRadius:15,paddingHorizontal:9,paddingVertical:5},badgeCompleted:{backgroundColor:'#EEEAE2'},badgeText:{color:colors.ink,fontWeight:'800',fontSize:11,textTransform:'capitalize'},notes:{color:colors.ink,fontSize:13,lineHeight:19,marginTop:3},outline:{borderWidth:1,borderColor:colors.line,borderRadius:10,padding:10,alignItems:'center'},outlineText:{color:colors.brandDark,fontWeight:'900'},empty:{borderWidth:1,borderColor:colors.line,borderStyle:'dashed',borderRadius:14,padding:16},error:{color:colors.danger,backgroundColor:'#FCE8E6',padding:12,borderRadius:10,fontWeight:'700'},success:{color:colors.success,backgroundColor:'#E5F3EC',padding:12,borderRadius:10,fontWeight:'700'}});
