import { useCallback, useEffect, useMemo, useState } from 'react';
import { Alert, Image, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import type { QuarryRepository } from '../../data/repositories/QuarryRepository';
import { calculateQuarryPurchase, emptyQuarryPurchaseDraft, type QuarryCorrectionDraft, type QuarryPurchase, type QuarryPurchaseDraft, type QuarrySetup } from '../../domain/quarry';
import { SearchableSelect } from '../components/SearchableSelect';
import { colors } from '../theme';
import { capturePersistentImage, pickPersistentImage } from '../../services/media';

export function QuarryPurchasesScreen({ repository, onBack }: { repository: QuarryRepository; onBack: () => void }) {
  const [setup,setSetup]=useState<QuarrySetup|null>(null); const [purchases,setPurchases]=useState<QuarryPurchase[]>([]); const [draft,setDraft]=useState<QuarryPurchaseDraft>({...emptyQuarryPurchaseDraft});
  const [showEntry,setShowEntry]=useState(false); const [showSupplier,setShowSupplier]=useState(false); const [supplierName,setSupplierName]=useState(''); const [supplierPhone,setSupplierPhone]=useState(''); const [supplierTax,setSupplierTax]=useState(''); const [supplierNotes,setSupplierNotes]=useState('');
  const [error,setError]=useState<string|null>(null); const [message,setMessage]=useState<string|null>(null); const [busy,setBusy]=useState(false);
  const [selected,setSelected]=useState<QuarryPurchase|null>(null);const[correction,setCorrection]=useState<QuarryCorrectionDraft|null>(null);const[cancelReason,setCancelReason]=useState('');
  const refresh=useCallback(async()=>{ const [nextSetup,nextPurchases]=await Promise.all([repository.getSetup(),repository.listPurchases()]); setSetup(nextSetup); setPurchases(nextPurchases); },[repository]);
  useEffect(()=>{void refresh();},[refresh]); const calculation=useMemo(()=>setup?calculateQuarryPurchase(draft,setup.vatRatePercent):null,[draft,setup]);
  const update=<K extends keyof QuarryPurchaseDraft>(key:K,value:QuarryPurchaseDraft[K])=>setDraft((current)=>({...current,[key]:value}));
  async function addPhoto(source:'camera'|'library'){if(draft.photos.length>=20){setError('A quarry purchase can contain up to 20 photos.');return;}try{setError(null);const uri=source==='camera'?await capturePersistentImage('quarry-tickets'):await pickPersistentImage('quarry-tickets');if(uri)update('photos',[...draft.photos,uri]);}catch(cause){setError(cause instanceof Error?cause.message:'Could not add photo.');}}
  async function addSupplier(){setBusy(true);setError(null);try{const supplier=await repository.createSupplier({name:supplierName,phone:supplierPhone,taxVatNumber:supplierTax,notes:supplierNotes});await refresh();update('supplierId',supplier.id);setSupplierName('');setSupplierPhone('');setSupplierTax('');setSupplierNotes('');setShowSupplier(false);setMessage('Supplier added and selected.');}catch(cause){setError(cause instanceof Error?cause.message:'Could not add supplier.');}finally{setBusy(false);}}
  async function confirm(){setBusy(true);setError(null);try{const saved=await repository.confirmPurchase(draft);await refresh();setDraft({...emptyQuarryPurchaseDraft});setShowEntry(false);setMessage(`Quarry purchase ${saved.purchaseNumber} confirmed.`);}catch(cause){setError(cause instanceof Error?cause.message:'Could not confirm purchase.');}finally{setBusy(false);}}
  function openPurchase(purchase:QuarryPurchase){setSelected(purchase);setCorrection({quantityCubicMetres:String(purchase.quantityCubicMetres),driverId:purchase.driverId,truckId:purchase.truckId,supplierTicketNumber:purchase.supplierTicketNumber??'',unitPriceUsd:purchase.unitPriceUsd==null?'':purchase.unitPriceUsd.toFixed(2),notes:purchase.notes??''});setCancelReason('');setError(null);setMessage(null);}
  async function saveCorrection(){if(!selected||!correction)return;setBusy(true);setError(null);try{const saved=await repository.correctPurchase(selected.id,correction);setSelected(saved);await refresh();setMessage('Quarry purchase corrected. Totals and payment status were recalculated.');}catch(cause){setError(cause instanceof Error?cause.message:'Could not correct purchase.');}finally{setBusy(false);}}
  function cancelPurchase(){if(!selected)return;if(!cancelReason.trim()){setError('Enter a cancellation reason first.');return;}Alert.alert('Cancel this quarry purchase?','The record will remain in history and be excluded from quantities, VAT, balances, and reports. This cannot be undone.',[{text:'Keep purchase',style:'cancel'},{text:'Cancel purchase',style:'destructive',onPress:async()=>{setBusy(true);setError(null);try{const saved=await repository.cancelPurchase(selected.id,cancelReason);setSelected(saved);await refresh();setMessage('Quarry purchase cancelled and retained in history.');}catch(cause){setError(cause instanceof Error?cause.message:'Could not cancel purchase.');}finally{setBusy(false);}}}]);}
  if(!setup)return <View style={styles.loading}><Text style={styles.helper}>Loading quarry purchases…</Text></View>;
  if(selected&&correction)return <ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><Header title={selected.purchaseNumber} onBack={()=>{setSelected(null);setCorrection(null);}}/>{error?<Text style={styles.error}>{error}</Text>:null}{message?<Text style={styles.success}>{message}</Text>:null}<Card title={`${selected.supplierName} · ${selected.itemName}`} hint={`${new Date(selected.confirmedAt).toLocaleString()} · ${selected.status}`}>
    {selected.status==='Active'?<><Text style={styles.helper}>Supplier, item, purchase number, and confirmation time stay fixed. Correct ordinary delivery and pricing mistakes below.</Text><Field label="Quantity (whole m³) *" value={correction.quantityCubicMetres} onChangeText={(value)=>setCorrection({...correction,quantityCubicMetres:value})} keyboardType="number-pad"/><SearchableSelect label="Driver *" options={setup.drivers.map(v=>({id:v.id,label:v.name,detail:v.phone??undefined}))} selectedId={correction.driverId} onSelect={(value)=>setCorrection({...correction,driverId:value})}/><SearchableSelect label="Truck plate *" options={setup.trucks.map(v=>({id:v.id,label:v.plate,detail:v.makeModel??undefined}))} selectedId={correction.truckId} onSelect={(value)=>setCorrection({...correction,truckId:value})}/><Field label="Supplier ticket / invoice number" value={correction.supplierTicketNumber} onChangeText={(value)=>setCorrection({...correction,supplierTicketNumber:value})}/><Field label="Price per m³ (USD, optional)" value={correction.unitPriceUsd} onChangeText={(value)=>setCorrection({...correction,unitPriceUsd:value})} keyboardType="decimal-pad"/><Field label="Notes" value={correction.notes} onChangeText={(value)=>setCorrection({...correction,notes:value})} multiline/><TouchableOpacity style={styles.darkButton} disabled={busy} onPress={()=>void saveCorrection()}><Text style={styles.darkButtonText}>{busy?'Saving…':'Save Correction'}</Text></TouchableOpacity><View style={styles.cancelArea}><Text style={styles.cardTitle}>Entered by mistake or duplicate?</Text><Text style={styles.helper}>Cancellation is permanent and is blocked until all active payments linked to this purchase are cancelled.</Text><Field label="Cancellation reason *" value={cancelReason} onChangeText={setCancelReason} multiline/><TouchableOpacity disabled={busy} onPress={cancelPurchase}><Text style={styles.cancelText}>Cancel Quarry Purchase</Text></TouchableOpacity></View></>:<Text style={styles.cancelled}>Cancelled {selected.cancelledAt?new Date(selected.cancelledAt).toLocaleString():''}{'\n'}Reason: {selected.cancellationReason}</Text>}
  </Card></ScrollView>;
  if(showEntry)return <ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><Header title="New quarry purchase" onBack={()=>setShowEntry(false)}/><Text style={styles.helper}>Record the quantity exactly from the supplier ticket. This does not change inventory.</Text>{error?<Text style={styles.error}>{error}</Text>:null}
    <Card title="Supplier"><SearchableSelect label="Quarry / supplier *" options={setup.suppliers.map((v)=>({id:v.id,label:v.name,detail:v.phone??undefined}))} selectedId={draft.supplierId} onSelect={(v)=>update('supplierId',v)} placeholder="Select supplier"/><TouchableOpacity style={styles.secondary} onPress={()=>setShowSupplier(!showSupplier)}><Text style={styles.secondaryText}>{showSupplier?'Close supplier form':'Quick add supplier'}</Text></TouchableOpacity>{showSupplier?<View style={styles.nested}><Field label="Supplier name *" value={supplierName} onChangeText={setSupplierName}/><Field label="Phone" value={supplierPhone} onChangeText={setSupplierPhone}/><Field label="Tax / VAT number" value={supplierTax} onChangeText={setSupplierTax}/><Field label="Notes" value={supplierNotes} onChangeText={setSupplierNotes} multiline/><TouchableOpacity style={styles.darkButton} disabled={busy} onPress={()=>void addSupplier()}><Text style={styles.darkButtonText}>Save supplier</Text></TouchableOpacity></View>:null}</Card>
    <Card title="Delivery information"><SearchableSelect label="Item *" options={setup.items.map((v)=>({id:v.id,label:v.name,detail:v.categoryName}))} selectedId={draft.itemId} onSelect={(v)=>update('itemId',v)} placeholder="Select quarry item"/><Field label="Quantity (whole m³) *" value={draft.quantityCubicMetres} onChangeText={(v)=>update('quantityCubicMetres',v)} keyboardType="number-pad"/><SearchableSelect label="Driver *" options={setup.drivers.map((v)=>({id:v.id,label:v.name,detail:v.phone??undefined}))} selectedId={draft.driverId} onSelect={(v)=>update('driverId',v)}/><SearchableSelect label="Truck plate *" options={setup.trucks.map((v)=>({id:v.id,label:v.plate,detail:v.makeModel??undefined}))} selectedId={draft.truckId} onSelect={(v)=>update('truckId',v)}/><Field label="Supplier ticket / invoice number" value={draft.supplierTicketNumber} onChangeText={(v)=>update('supplierTicketNumber',v)}/></Card>
    <Card title="Price and VAT" hint={`Universal VAT from Company profile: ${setup.vatRatePercent}%`}><Field label="Price per m³ (USD, optional)" value={draft.unitPriceUsd} onChangeText={(v)=>update('unitPriceUsd',v)} keyboardType="decimal-pad" placeholder="Leave blank for quantity-only"/>{calculation?.subtotalUsd!=null?<View style={styles.totalBox}><Total label="Subtotal" value={calculation.subtotalUsd}/><Total label={`VAT (${setup.vatRatePercent}%)`} value={calculation.vatAmountUsd??0}/><Total label="Final total" value={calculation.finalTotalUsd??0} strong/></View>:<Text style={styles.helper}>No price entered: VAT and payment balance do not apply.</Text>}<Field label="Notes" value={draft.notes} onChangeText={(v)=>update('notes',v)} multiline/></Card><Card title="Supplier ticket photos" hint="Optional camera or library photos. Maximum 20."><View style={styles.photoActions}><TouchableOpacity style={styles.secondary} onPress={()=>void addPhoto('camera')}><Text style={styles.secondaryText}>Take photo</Text></TouchableOpacity><TouchableOpacity style={styles.secondary} onPress={()=>void addPhoto('library')}><Text style={styles.secondaryText}>Choose photo</Text></TouchableOpacity></View><View style={styles.photoGrid}>{draft.photos.map((uri,index)=><View key={uri} style={styles.photoItem}><Image source={{uri}} style={styles.photo}/><TouchableOpacity onPress={()=>update('photos',draft.photos.filter((_,i)=>i!==index))}><Text style={styles.removePhoto}>Remove</Text></TouchableOpacity></View>)}</View></Card>
    <TouchableOpacity style={styles.confirm} disabled={busy} onPress={()=>void confirm()}><Text style={styles.confirmText}>{busy?'Confirming…':'Review and Confirm Purchase'}</Text></TouchableOpacity></ScrollView>;
  return <ScrollView contentContainerStyle={styles.content}><Header title="Quarry Purchases" onBack={onBack}/><Text style={styles.helper}>Incoming supplier deliveries are separate from outgoing Load History.</Text>{message?<Text style={styles.success}>{message}</Text>:null}<TouchableOpacity style={styles.primary} onPress={()=>{setError(null);setShowEntry(true);}}><Text style={styles.primaryText}>Add Quarry Purchase</Text><Text style={styles.primaryHint}>Supplier, item, m³ quantity, truck, price, and VAT</Text></TouchableOpacity><Text style={styles.sectionTitle}>Purchase history</Text>{purchases.length?purchases.map((p)=><TouchableOpacity key={p.id} style={styles.purchaseCard} onPress={()=>openPurchase(p)}><View style={styles.row}><Text style={styles.cardTitle}>{p.purchaseNumber}</Text><Text style={p.status==='Cancelled'?styles.cancelText:styles.status}>{p.status==='Cancelled'?'Cancelled':p.paymentStatus}</Text></View><Text style={styles.purchaseMain}>{p.supplierName} · {p.itemName}</Text><Text style={styles.helper}>{p.quantityCubicMetres} m³ · {p.driverName} · {p.truckPlate}</Text>{p.finalTotalUsd!=null?<Text style={styles.money}>${p.finalTotalUsd.toFixed(2)} including {p.vatRatePercent}% VAT</Text>:<Text style={styles.helper}>Quantity-only purchase</Text>}<Text style={styles.helper}>{p.photos.length} ticket photos · {new Date(p.confirmedAt).toLocaleString()} · Tap to open</Text></TouchableOpacity>):<View style={styles.empty}><Text style={styles.cardTitle}>No quarry purchases yet</Text><Text style={styles.helper}>Tap Add Quarry Purchase to record the first supplier delivery.</Text></View>}</ScrollView>;
}
function Header({title,onBack}:{title:string;onBack:()=>void}){return <View style={styles.header}><TouchableOpacity onPress={onBack} style={styles.back}><Text style={styles.backText}>Back</Text></TouchableOpacity><View><Text style={styles.eyebrow}>INCOMING MATERIAL</Text><Text style={styles.title}>{title}</Text></View></View>}
function Card({title,hint,children}:{title:string;hint?:string;children:React.ReactNode}){return <View style={styles.card}><Text style={styles.cardTitle}>{title}</Text>{hint?<Text style={styles.helper}>{hint}</Text>:null}{children}</View>}
function Field({label,...props}:{label:string;value:string;onChangeText:(v:string)=>void;placeholder?:string;multiline?:boolean;keyboardType?:'default'|'decimal-pad'|'number-pad'}){return <View style={styles.field}><Text style={styles.label}>{label}</Text><TextInput style={[styles.input,props.multiline&&styles.multiline]} placeholderTextColor="#89939B" {...props}/></View>}
function Total({label,value,strong}:{label:string;value:number;strong?:boolean}){return <View style={styles.row}><Text style={[styles.helper,strong&&styles.strong]}>{label}</Text><Text style={[styles.money,strong&&styles.strong]}>${value.toFixed(2)}</Text></View>}
const styles=StyleSheet.create({loading:{flex:1,alignItems:'center',justifyContent:'center'},content:{padding:20,paddingBottom:42,gap:16},header:{flexDirection:'row',alignItems:'center',gap:14},back:{backgroundColor:colors.surface,padding:10,borderRadius:10},backText:{color:colors.ink,fontWeight:'800'},eyebrow:{color:colors.brand,fontSize:11,fontWeight:'900',letterSpacing:1.4},title:{color:colors.ink,fontSize:27,fontWeight:'900'},helper:{color:colors.muted,fontSize:13,lineHeight:19},primary:{backgroundColor:colors.brand,borderRadius:16,padding:19,gap:4},primaryText:{color:'#FFF',fontSize:20,fontWeight:'900'},primaryHint:{color:'#F7D9D1',fontSize:13},sectionTitle:{color:colors.ink,fontSize:19,fontWeight:'900'},card:{backgroundColor:colors.surface,borderRadius:16,padding:17,gap:12},cardTitle:{color:colors.ink,fontSize:17,fontWeight:'900'},field:{gap:6},label:{color:colors.ink,fontSize:13,fontWeight:'800'},input:{borderWidth:1,borderColor:colors.line,borderRadius:11,paddingHorizontal:13,paddingVertical:11,color:colors.ink,backgroundColor:'#FCFBF8'},multiline:{minHeight:72,textAlignVertical:'top'},secondary:{flex:1,borderWidth:1,borderColor:colors.ink,borderRadius:11,padding:11,alignItems:'center'},secondaryText:{color:colors.ink,fontWeight:'900'},nested:{borderTopWidth:1,borderTopColor:colors.line,paddingTop:12,gap:10},darkButton:{backgroundColor:colors.ink,borderRadius:11,padding:13,alignItems:'center'},darkButtonText:{color:'#FFF',fontWeight:'900'},totalBox:{backgroundColor:'#F5F2EC',borderRadius:12,padding:13,gap:8},row:{flexDirection:'row',justifyContent:'space-between',gap:10},money:{color:colors.ink,fontWeight:'800'},strong:{fontSize:16,fontWeight:'900',color:colors.ink},confirm:{backgroundColor:colors.ink,borderRadius:13,padding:16,alignItems:'center'},confirmText:{color:'#FFF',fontWeight:'900',fontSize:16},purchaseCard:{backgroundColor:colors.surface,borderRadius:15,padding:16,gap:5},purchaseMain:{color:colors.ink,fontSize:15,fontWeight:'800'},status:{color:colors.brandDark,fontSize:12,fontWeight:'900'},empty:{borderWidth:1,borderColor:colors.line,borderStyle:'dashed',borderRadius:15,padding:16,gap:5},error:{color:colors.danger,backgroundColor:'#FCE8E6',padding:12,borderRadius:10,fontWeight:'700'},success:{color:colors.success,backgroundColor:'#E5F3EC',padding:12,borderRadius:10,fontWeight:'700'},photoActions:{flexDirection:'row',gap:8},photoGrid:{flexDirection:'row',flexWrap:'wrap',gap:10},photoItem:{width:'47%',gap:4},photo:{width:'100%',height:110,borderRadius:9,backgroundColor:'#EEE'},removePhoto:{color:colors.danger,fontWeight:'800'},cancelArea:{borderTopWidth:1,borderTopColor:colors.line,paddingTop:14,gap:10},cancelText:{color:colors.danger,fontWeight:'900'},cancelled:{color:colors.danger,lineHeight:21}});
