import {useCallback,useEffect,useMemo,useState} from 'react';
import {StyleSheet,Text,TouchableOpacity,View} from 'react-native';
import type {WallRepository} from '../../data/repositories/WallRepository';
import {calculateWallVolume,formatWallArea,summarizeWallConsumption,wallPurposeLabels,wallSystemLabels,type SavedConcretePurpose,type Wall,type WallDetail,type WallDraft,type WallSetup,type WallSystem} from '../../domain/walls';
import {AppButton,AppCard,AppField,AppPage,EmptyState,Feedback,MetricCard,PageHeader} from '../components/AppPrimitives';
import {ExpandableMenuSection} from '../components/ExpandableMenu';
import {SearchableSelect} from '../components/SearchableSelect';
import {emptyWallUseForm,wallDraftFromForm,WallConsumptionForm,wallUseFormFromEntry} from '../components/WallConsumptionForm';
import {WallConsumptionHistory} from '../components/WallConsumptionHistory';
import {colors} from '../theme';

type WallForm={projectId:string;name:string;system:WallSystem;purpose:WallDraft['purpose'];length:string;height:string;bottom:string;top:string;deduction:string;allowance:string;notes:string};
const n=(value:string)=>{const parsed=Number(value.replace(',','.'));return Number.isFinite(parsed)?parsed:0;},f=(value:number,digits=2)=>value.toLocaleString(undefined,{minimumFractionDigits:digits,maximumFractionDigits:digits});
const emptyWall=(projectId=''):WallForm=>({projectId,name:'',system:'reinforced_concrete',purpose:'retaining',length:'',height:'',bottom:'',top:'',deduction:'0',allowance:'0',notes:''});
const pair=(first:number,firstUnit:string,second:number,secondUnit:string)=>[first?`${f(first)} ${firstUnit}`:null,second?`${f(second)} ${secondUnit}`:null].filter(Boolean).join(' · ');

export function WallConstructionScreen({repository,onBack,initialProjectId}:{repository:WallRepository;onBack:()=>void;initialProjectId?:string|null}){
  const[setup,setSetup]=useState<WallSetup|null>(null),[walls,setWalls]=useState<Wall[]>([]),[purposes,setPurposes]=useState<SavedConcretePurpose[]>([]),[wallForm,setWallForm]=useState<WallForm>(()=>emptyWall(initialProjectId??'')),[editingId,setEditingId]=useState<string|null>(null),[selected,setSelected]=useState<WallDetail|null>(null),[formKey,setFormKey]=useState(0),[open,setOpen]=useState<Set<string>>(()=>new Set()),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null),[message,setMessage]=useState<string|null>(null);
  const locked=!!initialProjectId,toggle=(key:string)=>setOpen(current=>{const next=new Set(current);if(next.has(key))next.delete(key);else next.add(key);return next;});
  const refresh=useCallback(async()=>{const[nextSetup,nextWalls,nextPurposes]=await Promise.all([repository.getSetup(),repository.listWalls(initialProjectId??null),repository.listConcretePurposes()]);setSetup(nextSetup);setWalls(nextWalls);setPurposes(nextPurposes);if(selected){const current=nextWalls.find(value=>value.id===selected.wall.id);setSelected(current?await repository.getWall(current.id):null);}},[initialProjectId,repository,selected?.wall.id]);
  useEffect(()=>{setLoading(true);void refresh().catch(cause=>setError(cause instanceof Error?cause.message:'Could not load wall construction records.')).finally(()=>setLoading(false));},[initialProjectId,repository]);
  const wallResult=useMemo(()=>calculateWallVolume(n(wallForm.length),n(wallForm.height),n(wallForm.bottom),n(wallForm.top),n(wallForm.deduction),n(wallForm.allowance)),[wallForm]);
  const projects=setup?.projects??[],activeProjects=projects.filter(value=>value.status==='active'),visible=initialProjectId?walls:wallForm.projectId?walls.filter(value=>value.projectId===wallForm.projectId):walls;
  const wallDraft=():WallDraft=>({projectId:wallForm.projectId,name:wallForm.name,system:wallForm.system,purpose:wallForm.purpose,lengthM:n(wallForm.length),heightM:n(wallForm.height),bottomThicknessM:n(wallForm.bottom),topThicknessM:n(wallForm.top),deductionM3:n(wallForm.deduction),allowancePercent:n(wallForm.allowance),notes:wallForm.notes});
  async function run(action:()=>Promise<void>,success:string){setBusy(true);setError(null);setMessage(null);try{await action();setMessage(success);}catch(cause){setError(cause instanceof Error?cause.message:'The wall record could not be saved.');}finally{setBusy(false);}}
  function saveWall(){void run(async()=>{const saved=await repository.saveWall(wallDraft(),editingId??undefined);setEditingId(null);setWallForm(emptyWall(initialProjectId??wallForm.projectId));setSetup(await repository.getSetup());setWalls(await repository.listWalls(initialProjectId??null));setSelected(await repository.getWall(saved.id));setFormKey(key=>key+1);setOpen(current=>new Set([...current,'consumption','history']));},editingId?'Wall updated.':'Wall saved under the project.');}
  function editWall(value:Wall){setEditingId(value.id);setWallForm({projectId:value.projectId,name:value.name,system:value.system,purpose:value.purpose,length:String(value.lengthM),height:String(value.heightM),bottom:String(value.bottomThicknessM),top:String(value.topThicknessM),deduction:String(value.deductionM3),allowance:String(value.allowancePercent),notes:value.notes});setOpen(current=>new Set([...current,'wall']));}
  async function chooseWall(value:Wall){setBusy(true);setError(null);setMessage(null);try{setSelected(await repository.getWall(value.id));setFormKey(key=>key+1);setOpen(current=>new Set([...current,'consumption','history']));}catch(cause){setError(cause instanceof Error?cause.message:'Could not open the wall.');}finally{setBusy(false);}}
  async function reloadSelected(wallId:string){const[detail,nextWalls]=await Promise.all([repository.getWall(wallId),repository.listWalls(initialProjectId??null)]);setSelected(detail);setWalls(nextWalls);}
  async function createPurpose(label:string){const created=await repository.createConcretePurpose(label);setPurposes(await repository.listConcretePurposes());return created;}

  const totals=useMemo(()=>summarizeWallConsumption(selected?.entries??[]),[selected]);
  const rebarBySize=useMemo(()=>{const grouped=new Map<number,{bars:number;metres:number;kg:number}>();for(const value of selected?.entries??[]){if(value.type!=='rebar'||value.rebarDiameterMm===null)continue;const current=grouped.get(value.rebarDiameterMm)??{bars:0,metres:0,kg:0};current.bars+=value.rebarCount??0;current.metres+=value.totalRebarLengthM??0;current.kg+=value.totalRebarKg??0;grouped.set(value.rebarDiameterMm,current);}return[...grouped.entries()].sort((a,b)=>a[0]-b[0]);},[selected]);
  // Only totals that were actually recorded are shown; a material never used on this wall is omitted rather than shown as zero.
  const metrics=[
    {label:'Structural concrete used',value:totals.structural?`${f(totals.structural)} m³`:''},
    {label:'Filling / mortar used',value:totals.filling?`${f(totals.filling)} m³`:''},
    {label:'Other purposes',value:totals.otherConcrete?`${f(totals.otherConcrete)} m³`:''},
    {label:'Cement consumed',value:totals.cement?`${f(totals.cement,0)} bags${totals.cementKg?` · ${f(totals.cementKg,0)} kg`:''}`:''},
    {label:'Rebar installed',value:totals.rebarKg?`${f(totals.rebarKg,1)} kg`:''},
    {label:'Stone consumed',value:pair(totals.stoneM3,'m³',totals.stoneT,'t')},
    {label:'Sand consumed',value:pair(totals.sandM3,'m³',totals.sandT,'t')},
    {label:'Gravel consumed',value:pair(totals.gravelM3,'m³',totals.gravelT,'t')},
    {label:'Water recorded',value:totals.water?`${f(totals.water,0)} L`:''},
    {label:'Ready-mix area covered',value:totals.readyMixAreaM2?formatWallArea(totals.readyMixAreaM2):''},
    {label:'Stone area covered',value:totals.stoneAreaM2?formatWallArea(totals.stoneAreaM2):''},
  ].filter(metric=>metric.value);

  return <AppPage keyboard><PageHeader eyebrow="CONSTRUCTION QUANTITIES" title="Wall Construction" onBack={onBack}/><AppCard tone="navy" title="Calculate, then record actual consumption" hint="Each wall stays under its project."><Text style={styles.disclaimer}>Dimensions, reinforcement, material proportions, drainage, and stability come from approved drawings or the project engineer. DROMEX tracks quantities only.</Text></AppCard>{error?<Feedback kind="error">{error}</Feedback>:null}{message?<Feedback kind="success">{message}</Feedback>:null}
    <ExpandableMenuSection title="1 · Wall and geometry" hint="Project, wall system, tapered dimensions, deductions, and planned volume." tone="orange" open={open.has('wall')} onToggle={()=>toggle('wall')}><AppCard>{locked?<View style={styles.locked}><Text style={styles.small}>PROJECT LOCKED</Text><Text style={styles.lockedValue}>{projects.find(v=>v.id===wallForm.projectId)?.name??'Selected project'}</Text></View>:<SearchableSelect label="Project *" options={activeProjects.map(v=>({id:v.id,label:v.name,detail:`${v.customerName} · ${v.location}`}))} selectedId={wallForm.projectId} onSelect={projectId=>setWallForm({...wallForm,projectId})} placeholder="Choose an active project"/>}<AppField label="Wall or section name *" value={wallForm.name} onChangeText={name=>setWallForm({...wallForm,name})} placeholder="Example: Retaining wall · Section A"/><SearchableSelect label="Wall system *" options={(Object.keys(wallSystemLabels) as WallSystem[]).map(id=>({id,label:wallSystemLabels[id]}))} selectedId={wallForm.system} onSelect={system=>setWallForm({...wallForm,system:system as WallSystem})}/><SearchableSelect label="Wall purpose" options={(Object.keys(wallPurposeLabels) as WallDraft['purpose'][]).map(id=>({id,label:wallPurposeLabels[id]}))} selectedId={wallForm.purpose} onSelect={purpose=>setWallForm({...wallForm,purpose:purpose as WallDraft['purpose']})}/><Pair><AppField label="Length (m) *" value={wallForm.length} onChangeText={length=>setWallForm({...wallForm,length})} keyboardType="decimal-pad"/><AppField label="Height (m) *" value={wallForm.height} onChangeText={height=>setWallForm({...wallForm,height})} keyboardType="decimal-pad"/></Pair><Pair><AppField label="Bottom thickness (m) *" value={wallForm.bottom} onChangeText={bottom=>setWallForm({...wallForm,bottom})} keyboardType="decimal-pad"/><AppField label="Top thickness (m) *" value={wallForm.top} onChangeText={top=>setWallForm({...wallForm,top})} keyboardType="decimal-pad"/></Pair><Pair><AppField label="Volume deductions (m³)" value={wallForm.deduction} onChangeText={deduction=>setWallForm({...wallForm,deduction})} keyboardType="decimal-pad"/><AppField label="Allowance (%)" value={wallForm.allowance} onChangeText={allowance=>setWallForm({...wallForm,allowance})} keyboardType="decimal-pad"/></Pair><View style={styles.metrics}><MetricCard label="Net wall volume" value={`${f(wallResult.netVolumeM3)} m³`} result/><MetricCard label="Planned with allowance" value={`${f(wallResult.plannedVolumeM3)} m³`} result/></View><AppField label="Notes" value={wallForm.notes} onChangeText={notes=>setWallForm({...wallForm,notes})} multiline/><AppButton label={editingId?'Update Wall':'Save Wall Under Project'} busy={busy} disabled={!wallForm.projectId||!wallForm.name.trim()||wallResult.netVolumeM3<=0} onPress={saveWall}/>{editingId?<AppButton label="Cancel Editing" tone="secondary" onPress={()=>{setEditingId(null);setWallForm(emptyWall(initialProjectId??wallForm.projectId));}}/>:null}</AppCard></ExpandableMenuSection>
    <AppCard title="Saved project walls" hint="Open a wall to record and review its actual material consumption.">{loading?<Text style={styles.detail} accessibilityLiveRegion="polite">Loading saved walls…</Text>:visible.length?visible.map(value=>{const isSelected=selected?.wall.id===value.id;return <View key={value.id} style={[styles.wallRow,isSelected&&styles.wallSelected]}><TouchableOpacity style={styles.wallOpen} onPress={()=>void chooseWall(value)} accessibilityRole="button" accessibilityState={{selected:isSelected}} accessibilityHint="Opens this wall's consumption log"><Text style={styles.project}>{value.projectName.toUpperCase()}</Text><Text style={styles.wallName}>{value.name}</Text><Text style={styles.detail}>{wallSystemLabels[value.system]} · {f(value.plannedVolumeM3)} m³ planned</Text></TouchableOpacity><TouchableOpacity style={styles.editButton} onPress={()=>editWall(value)} accessibilityRole="button" accessibilityLabel={`Edit ${value.name}`}><Text style={styles.edit}>Edit</Text></TouchableOpacity></View>;}):<EmptyState title="No saved walls" body="Open section 1 to create the first project wall."/>}</AppCard>
    {selected?<>
      {metrics.length?<View style={styles.metrics}>{metrics.map(metric=><MetricCard key={metric.label} label={metric.label} value={metric.value} result/>)}</View>:<AppCard tone="cream"><Text style={styles.detail}>No consumption recorded under {selected.wall.name} yet. Totals appear here once materials are recorded.</Text></AppCard>}
      {rebarBySize.length?<AppCard title="Steel reinforcement by size" hint="Every diameter remains separate.">{rebarBySize.map(([diameter,value])=><View key={diameter} style={styles.rebarSummary}><Text style={styles.rebarDiameter}>Ø{f(diameter,0)} mm</Text><Text style={styles.rebarValue}>{f(value.bars,0)} bars · {f(value.metres)} m · {f(value.kg,1)} kg</Text></View>)}</AppCard>:null}
      <ExpandableMenuSection title="2 · Record consumed materials" hint={`Add concrete, site-mixed ingredients, rebar, or stone to ${selected.wall.name}. Stone and ready mix can also record the wall area they covered.`} open={open.has('consumption')} onToggle={()=>toggle('consumption')}><AppCard><WallConsumptionForm key={`${selected.wall.id}-${formKey}`} mode="add" initial={emptyWallUseForm()} savedPurposes={purposes} onCreatePurpose={createPurpose} onSubmit={async form=>{setMessage(null);await repository.addConsumption(wallDraftFromForm(form,selected.wall.id));await reloadSelected(selected.wall.id);setMessage('Wall consumption recorded.');}}/></AppCard></ExpandableMenuSection>
      <ExpandableMenuSection title="3 · Consumption history" hint={`${selected.entries.length} saved entr${selected.entries.length===1?'y':'ies'} under this wall. Open an entry to see its details or correct it.`} tone="cream" open={open.has('history')} onToggle={()=>toggle('history')}><WallConsumptionHistory entries={selected.entries} renderCorrection={(entry,close)=><WallConsumptionForm mode="correct" initial={wallUseFormFromEntry(entry)} savedPurposes={purposes} onCreatePurpose={createPurpose} onDiscard={close} onSubmit={async form=>{setMessage(null);await repository.correctConsumption(entry.id,{...wallDraftFromForm(form,entry.wallId),correctionReason:form.reason});close();await reloadSelected(entry.wallId);setMessage('Correction saved. The record keeps its identity and the change is in its history.');}}/>}/></ExpandableMenuSection>
    </>:null}
  </AppPage>;
}

function Pair({children}:{children:React.ReactNode}){return <View style={styles.pair}>{Array.isArray(children)?children.map((child,index)=><View key={index} style={styles.half}>{child}</View>):children}</View>;}
const styles=StyleSheet.create({disclaimer:{color:'#FFF8ED',fontSize:12,lineHeight:18,fontWeight:'700'},locked:{backgroundColor:colors.cream,borderRadius:12,padding:12},small:{color:colors.brandDark,fontSize:8,fontWeight:'900'},lockedValue:{color:colors.ink,fontSize:16,fontWeight:'900'},pair:{flexDirection:'row',gap:10},half:{flex:1,minWidth:0},metrics:{flexDirection:'row',flexWrap:'wrap',gap:8},wallRow:{backgroundColor:colors.cream,borderRadius:13,flexDirection:'row',alignItems:'center',borderLeftWidth:4,borderLeftColor:colors.navy},wallSelected:{borderLeftColor:colors.result,backgroundColor:colors.resultSoft},wallOpen:{flex:1,minWidth:0,padding:13,minHeight:64},project:{color:colors.brand,fontSize:8,fontWeight:'900'},wallName:{color:colors.ink,fontSize:16,fontWeight:'900'},detail:{color:colors.muted,fontSize:12,lineHeight:17},editButton:{minHeight:48,minWidth:56,alignItems:'center',justifyContent:'center',paddingHorizontal:10},edit:{color:colors.navy,fontWeight:'900'},rebarSummary:{backgroundColor:colors.resultSoft,borderRadius:10,padding:11,flexDirection:'row',alignItems:'center',gap:10},rebarDiameter:{color:colors.resultDark,fontSize:14,fontWeight:'900',minWidth:68},rebarValue:{color:colors.ink,fontSize:11,fontWeight:'800',flex:1}});
