import {useState} from 'react';
import {ScrollView,StyleSheet,Text,TouchableOpacity,View} from 'react-native';
import {ExpandableMenuSection,MenuAction} from '../components/ExpandableMenu';
import {colors} from '../theme';

type Routes={onSearch:()=>void;onDrafts:()=>void;onLoads:()=>void;onCustomers:()=>void;onProjects:()=>void;onDirectory:()=>void;onCatalog:()=>void;onSchedule:()=>void;onPavement:()=>void;onWalls:()=>void;onWaste:()=>void;onQuarry:()=>void;onFuel:()=>void;onQuickText:()=>void;onFinancials:()=>void;onCorrections:()=>void;onReports:()=>void;onReceiptSetup:()=>void;onSettings:()=>void;onBackup:()=>void;onCloud:()=>void;onAttention:()=>void};

export function WorkspaceHubScreen({kind,routes}:{kind:'records'|'more';routes:Routes}){
  const[open,setOpen]=useState<Set<string>>(()=>new Set());const toggle=(key:string)=>setOpen(current=>{const next=new Set(current);if(next.has(key))next.delete(key);else next.add(key);return next;});
  return <ScrollView contentContainerStyle={styles.content}><View style={styles.heading}><View style={styles.flex}><Text style={styles.eyebrow}>{kind==='records'?'FIND AND REVIEW':'REPORTS, SETUP, AND TOOLS'}</Text><Text style={styles.title}>{kind==='records'?'Records':'More'}</Text><Text style={styles.intro}>{kind==='records'?'Open a colored label to find related operational or business records.':'Open a label to find reports, configuration, and application tools.'}</Text></View><TouchableOpacity style={styles.search} onPress={routes.onSearch}><Text style={styles.searchMark}>⌕</Text><Text style={styles.searchText}>Search</Text></TouchableOpacity></View>
    {kind==='records'?<>
      <ExpandableMenuSection title="Operational Records" hint="Loads, plans, quantities, movements, and saved field documents." open={open.has('operations')} onToggle={()=>toggle('operations')}><MenuAction number="01" title="Load History" body="Confirmed receipts, authorizations, signatures, and payment state." onPress={routes.onLoads}/><MenuAction number="02" title="Project Schedule" body="Today, weekly, and three-week plans across projects." onPress={routes.onSchedule}/><MenuAction number="03" title="Asphalt Pavement Calculator" body="Choose kg/m² and calculate compacted thickness, kilograms, and tonnes." onPress={routes.onPavement}/><MenuAction number="04" title="Wall Construction" body="Calculate project walls and record concrete, ingredients, steel, and stone consumed." onPress={routes.onWalls}/><MenuAction number="05" title="Waste Dump History" body="Driver counters, individual dumps, cancellations, and summaries." onPress={routes.onWaste}/><MenuAction number="06" title="Quarry Purchases" body="Incoming material, suppliers, trucks, photos, and payments." onPress={routes.onQuarry}/><MenuAction number="07" title="Fuel Ledger" body="Gauge readings, deliveries, fills, and equipment totals." onPress={routes.onFuel}/><MenuAction number="08" title="Quick Text" body="Saved company notices and printable documents." onPress={routes.onQuickText}/></ExpandableMenuSection>
      <ExpandableMenuSection title="Business Directory" hint="Projects, customers, people, equipment, and materials." tone="orange" open={open.has('directory')} onToggle={()=>toggle('directory')}><MenuAction number="01" title="Projects" body="Open project command centers and manage project status." onPress={routes.onProjects} tone="cream"/><MenuAction number="02" title="Customers" body="Customer profiles, projects, receipts, and balances." onPress={routes.onCustomers} tone="cream"/><MenuAction number="03" title="People & Equipment" body="Workers, drivers, trucks, and machines." onPress={routes.onDirectory} tone="cream"/><MenuAction number="04" title="Item Catalog" body="Categories and shared material records." onPress={routes.onCatalog} tone="cream"/></ExpandableMenuSection>
      <ExpandableMenuSection title="Finance and Corrections" hint="Balances, payments, and controlled record corrections." tone="cream" open={open.has('finance')} onToggle={()=>toggle('finance')}><MenuAction number="01" title="Payments & Balances" body="Receivables, payables, payments, and opening balances." onPress={routes.onFinancials}/><MenuAction number="02" title="Correct Confirmed Loads" body="Correct allowed load values without changing identity." onPress={routes.onCorrections}/></ExpandableMenuSection>
    </>:<>
      <ExpandableMenuSection title="Reports and Exports" hint="Project reports, PDFs, Excel workbooks, and analysis." tone="orange" open={open.has('reports')} onToggle={()=>toggle('reports')}><MenuAction number="01" title="Reports Center" body="Daily reports, completed-project PDFs, and Excel workbooks." onPress={routes.onReports} tone="cream"/></ExpandableMenuSection>
      <ExpandableMenuSection title="Setup" hint="Configure company records, security, and data protection." open={open.has('setup')} onToggle={()=>toggle('setup')}><MenuAction number="01" title="Item Catalog" body="Manage categories, materials, prices, and usage areas." onPress={routes.onCatalog}/><MenuAction number="02" title="Receipt Setup" body="Measurement units and conversion choices." onPress={routes.onReceiptSetup}/><MenuAction number="03" title="Company & VAT" body="Identity, logo, document details, and tax settings." onPress={routes.onSettings}/><MenuAction number="04" title="Backup & Restore" body="Save or restore one encrypted complete backup through Google Drive or Apple Files." onPress={routes.onBackup}/><MenuAction number="05" title="Account & Cloud" body="Future owner sign-in, synchronization, and device status." onPress={routes.onCloud}/></ExpandableMenuSection>
      <ExpandableMenuSection title="Application Tools" hint="Search, drafts, and records needing attention." tone="cream" open={open.has('tools')} onToggle={()=>toggle('tools')}><MenuAction number="01" title="Global Search" body="Search projects, loads, plates, people, materials, and documents." onPress={routes.onSearch}/><MenuAction number="02" title="Draft Center" body="Find unfinished receipts, reports, quarry, fuel, and Quick Text." onPress={routes.onDrafts}/><MenuAction number="03" title="Needs Attention" body="Open blocked, incomplete, unpriced, missing, and pending work." onPress={routes.onAttention}/></ExpandableMenuSection>
    </>}
  </ScrollView>;
}

const styles=StyleSheet.create({content:{padding:20,paddingBottom:44,gap:16},heading:{flexDirection:'row',alignItems:'flex-start',gap:12},flex:{flex:1,minWidth:0},eyebrow:{color:colors.brand,fontSize:10,fontWeight:'900',letterSpacing:1.3},title:{color:colors.ink,fontSize:30,fontWeight:'900',marginTop:3},intro:{color:colors.muted,fontSize:12,lineHeight:18,marginTop:5},search:{minWidth:68,minHeight:52,borderRadius:13,backgroundColor:colors.navy,alignItems:'center',justifyContent:'center',padding:8},searchMark:{color:'#FFF',fontSize:21,fontWeight:'900',lineHeight:22},searchText:{color:'#FFF',fontSize:9,fontWeight:'900'}});
